<div id="central-content">
    <p class="oswald" id="my-account">My Account</p>
    <aside class="oswald" id="block-left">
        <p class=" bg-white" id="hi-lateral">HI blackswaninteractive</p>
        <div id="color-fondo">

            <?php echo $this->navigation()->menu()->render(); ?>
        </div>
        <div id="linea-fondo">
        </div>
    </aside>
    <section id="block-right">
        <form id="form-profile-page" class="form-account-setting" method="post" enctype="multipart/form-data"  >
            <h2 class="h2-cms oswald">Profile Page</h2>
            <hr class="hr-gris">
            <fieldset id="business-contact"><legend class="oswald">BUSINESS CONTACT DETAILS</legend>
                <div id="div-drop-image">
                    <div><label>logo:</label></div>
                    <div class="drop-image">
                        <br/>
                         Drag and drop your logo here
                        <br/>
                        or
                        <br/>                        
                        <div class="btn-upload-image">
                            <input class="fileupload" type="file" name="logo" >
                            <span class="round-border-yellow btn-yellow examinar">click here</span>
                        </div>
                        
                    </div>
                    <div>
                        <p>This is the image we use to<br> represent you on Mexi-Go</p>
                        <p>Your logo is shown at 145 x 145 pixels:</p>
                    </div>

                </div>
                <br>
                <hr class="hr-gris">
                <label for="profileCompany">Company:</label>
                <input type="text" id="profileCompany" name="profileCompany" value="<?php echo $this->dataProfiler['company'] ?>"><br>
                <label for="profileEmail">*Email Address:</label>
                <input type="text" id="profileEmail" name="profileEmail" value="<?php echo $this->dataProfiler['email'] ?>"><span class="email-icon"></span><br>
                <label for="profileFullName">Website:</label>
                <input type="text" id="profileWebsite" name="profileWebsite" value="<?php echo $this->dataProfiler['website'] ?>"><span class="website-icon"></span><br>
                <label for="profilePhoneDescription1">Phone 1:</label>
                <input type="text" id="profileDecription1" name="profilePhoneDescription1" value="<?php echo $this->dataProfiler['phoneDes1'] != '' ? $this->dataProfiler['phoneDes1'] : 'Phone description'; ?>">
                <input type="text" id="profilePhonePre1" name="profilePhone11" value="<?php echo $this->dataProfiler['phome11'] ?>" class="campo-chico-3"> -
                <input type="text" id="profilePhone1" name="profilePhone12" value="<?php echo $this->dataProfiler['phome12'] ?>" class="campo-chico-3"> -
                <input type="text" id="profilePhonepost1" name="profilePhone13" value="<?php echo $this->dataProfiler['phome13'] ?>" class="campo-chico-3"><br>
                <label for="profilePhoneDescription2">Phone 2:</label>
                <input type="text" id="profileDecription2" name="profilePhoneDescription2" value="<?php echo $this->dataProfiler['phoneDes2'] != '' ? $this->dataProfiler['phoneDes2'] : 'Phone description'; ?>">
                <input type="text" id="profilePhonePre2" name="profilePhone21" value="<?php echo $this->dataProfiler['phome21'] ?>" class="campo-chico-3"> -
                <input type="text" id="profilePhone2" name="profilePhone22" value="<?php echo $this->dataProfiler['phome22'] ?>" class="campo-chico-3"> -
                <input type="text" id="profilePhonepost2" name="profilePhone23" value="<?php echo $this->dataProfiler['phome23'] ?>" class="campo-chico-3"><br>
                <?php if ($this->dataProfiler['phoneDes3'] != '') { ?>
                    <label for="profilePhoneDescription3">Phone 3:</label>
                    <input type="text" id="profileDecription3" name="profilePhoneDescription3" value="<?php echo $this->dataProfiler['phoneDes3'] != '' ? $this->dataProfiler['phoneDes3'] : 'Phone description'; ?>">
                    <input type="text" id="profilePhonePre3" name="profilePhone31" value="<?php echo $this->dataProfiler['phome31'] ?>" class="campo-chico-3"> -
                    <input type="text" id="profilePhone3" name="profilePhone32" value="<?php echo $this->dataProfiler['phome32'] ?>" class="campo-chico-3"> -
                    <input type="text" id="profilePhonepost3" name="profilePhone33" value="<?php echo $this->dataProfiler['phome33'] ?>" class="campo-chico-3">
                <?php } ?>
                <a href="" class="boton-gris-1 oswald">ADD ANOTHER PHONE &gt;&gt;</a><br>
                <textarea id="profileDescription" name="profileDescription"><?php
                if ($this->dataProfiler['descripcion'] != '') {
                    echo $this->dataProfiler['descripcion'];
                } else {
                    ?>Write a short description that will appear on your profile page<?php } ?>
                </textarea>

            </fieldset>
            <hr class="hr-gris">
            <fieldset id="upload-pdf"><legend class="oswald">YOUR PDF FILES</legend>
                <?php
                if (count($this->file) > 0) {
                    foreach ($this->file as $index => $value) {
                        ?>
                        <a href="<?php echo CST_Server_ServerDinamic::getUrl(); ?>/partner/profiler/file/<?php echo $value['fil_source'] ?>"> <?php echo $value['fil_title'] ?> </a>
                        <input type="file" name="fileProfiler<?php echo ($index + 1); ?>"><p></p>
                        <?php
                    }
                } else {
                    ?>
                    <input type="file" name="fileProfiler1"><p></p>
                    <?php
                }
                ?>
                <a href="" class="boton-gris-1 oswald">ADD ADDITIONAL PDF &gt;&gt;</a>
            </fieldset>
            <hr class="hr-gris">
            <fieldset id="upload-image"><legend class="oswald">IMAGE GALLERY</legend>
                <div class="preview-galery">
                    
                </div>
                <div id="upload-gallery-images" class="round-border-gris">
                    Drag and drop your photos here<br>
                    or<br>
                    <div class="btn-upload-image">
                        <input class="fileupload" type="file" name="gallery" multiple >
                        <span class="round-border-yellow btn-yellow examinar">chose photos to upload</span>
                    </div>
                </div>
            </fieldset>
            <hr class="hr-gris">
            <fieldset id="upload-videos"><legend class="oswald">VIDEO GALLERY</legend>
                <?php if (!empty($this->dataVideo)) { ?>
                    <?php foreach ($this->dataVideo as $index => $value): ?>
                        <input type="text" 
                               id="profileVideo<?php echo $index + 1 ?>" 
                               name="profileVideo<?php echo $index + 1 ?>"
                               value="<?php echo $value['vid_uri'] ?>"
                               />
                        <span class="text-gris-claro desc-subida-video">Insert your video link (vimeo or youtube)</span><br>
                    <?php
                    endforeach;
                    if (count($this->dataVideo) == 1) {
                        ?>
                        <input type="text" id="profileVideo2" name="profileVideo2" /><span class="text-gris-claro desc-subida-video">Insert your video link (vimeo or youtube)</span><br>                                
                        <?php
                    }
                    ?>
                    <?php } else { ?>
                    <input type="text" id="profileVideo1" name="profileVideo1" /><span class="text-gris-claro desc-subida-video">Insert your video link (vimeo or youtube)</span><br>                
                    <input type="text" id="profileVideo2" name="profileVideo2" /><span class="text-gris-claro desc-subida-video">Insert your video link (vimeo or youtube)</span><br>                
                    <?php } ?>
                <a href="" class="no-margen-left boton-gris-1 oswald">ADD MORE VIDEOS &gt;&gt;</a>                                
            </fieldset>
            <hr class="hr-gris">
            <fieldset id="loaction"><legend class="oswald">LOCATION</legend>
                <div style="width:370px;float:left">
                    <label for="profileLocationAddress">Address:</label>
                    <input type="text" id="profileLocationAddress" name="profileLocationAddress" value="<?php echo $this->location['address'] ?>">
                    <br>
                    <label for="profileLocationSuite">*Suite/Apt./Unit:</label>
                    <input type="text" id="profileLocationSuite" name="profileLocationSuite" value="<?php echo $this->location['site'] ?>">
                    <br>
                    <div class="combo-fix">
                        <label for="profilerLocationState">State:</label>
                        <div class="flecha-combo">
                            <select type="text" id="profilerLocationState" name="profilerLocationState">
                               <option value="" >-------</option>
                        <?php foreach($this->estados as $index=>$value):
                            $selected = $this->location['state']==$index?'Selected="Selected"':'';
                            ?>
                        <option <?php echo $selected; ?>  value="<?php echo $index?>" ><?php echo $value?></option>
                        <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <br>
                    <div class="combo-fix">
                        <label for="profileLocationCity">City:</label>
                        <div class="flecha-combo">
                            <select type="text" id="profileLocationCity" name="profileLocationCity">
                                <option value="" >-------</option>
                                <?php foreach($this->ciudades as $index=>$value):
                            $selected = $this->location['city']==$index?'Selected="Selected"':'';
                            ?>
                        <option <?php echo $selected; ?>  value="<?php echo $index?>" ><?php echo $value?></option>
                        <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <br>
                    
                    
                        <label for="profilerLocationZip">Zip/Postal Code:</label>
                        <input type="text" id="profilerLocationZip" name="profilerLocationZip" value="<?php echo $this->location['zip']?>" />
                    <br>
                </div>
                <div style="width:370px;float:left">
                    <label for="profileLocationLatitud">Latitude:</label>
                    <input type="text" id="profileLocationLatitud" name="profileLocationLatitud" value="<?php echo $this->location['latitud']?>" ><br>
                    <label for="profileLocationLongitud">Longitud:</label>
                    <input type="text" id="profileLocationLongitud" name="profileLocationLongitud" value="<?php echo $this->location['longitud']?>" /><br>

                </div>

            </fieldset>
            <div>mapa</div>
            <fieldset id="pick-categories"><legend class="oswald">PICK THE CATEGORIES WHERE YOUR PAGE WILL APPEAR</legend>
                <p>(Two sections max.)</p>
                <?php foreach($this->listingCategoria as $index=>$value): ?>
                <?php if(isset($this->listingCategoriaRel[$index])) {
                        $checked = 'checked="checked"';
                    } else{
                        $checked='';
                    } ?>
                     
                <input <?php echo $checked ?> value="<?php echo $index; ?>" id="checkCategories<?php echo $index; ?>" type="checkbox" name="profileCategoria[]">
                <label for="checkCategories<?php echo $index; ?>" class="label-check"><?php echo $value; ?></label>
                <?php endforeach; ?>
            </fieldset>
            <fieldset id="pick-subcategories"><legend class="oswald">SELECT A SUBCATEGORY</legend>
                <?php 
                $cantSubCat = count($this->listingSubCategoria);
                $cantColumn = (int)($cantSubCat/3);
                $residuo = (int)($cantSubCat%3);
                $output1 = array_slice($this->listingSubCategoria, 0,($cantColumn),true);      // returns "c", "d", and "e"
                $output2 = array_slice($this->listingSubCategoria, $cantColumn, $cantColumn,true);  // returns "d"
                $output3 = array_slice($this->listingSubCategoria, 2*$cantColumn, $cantColumn+$residuo,true);   // returns "a", "b", and "c"
                ?>
                <div class="pick-izq">
                <?php
                foreach($output1 as $index=>$value): ?>
                    <?php if(isset($this->listingSubcategoriaRel[$index])) {
                        $checked = 'checked="checked"';
                    } else{
                        $checked='';
                    } ?>
                    <input <?php echo $checked ?>  value="<?php echo $index ?>" name="profileSubCategoria[]" id="check<?php echo $index ?>" type="checkbox"><label for="check<?php echo $index ?>" class="label-check2"><?php echo $value ?></label>
                <?php endforeach; ?>
                </div>        
                <div class="pick-izq">
                <?php
                foreach($output2 as $index=>$value): ?>
                    <?php if(isset($this->listingSubcategoriaRel[$index])) {
                        $checked = 'checked="checked"';
                    } else{
                        $checked='';
                    } ?>
                    <input <?php echo $checked ?>  value="<?php echo $index ?>" name="profileSubCategoria[]" id="check<?php echo $index ?>" type="checkbox"><label for="check<?php echo $index ?>" class="label-check2"><?php echo $value ?></label>
                <?php endforeach; ?>
                </div>        
                <div class="pick-izq">
                <?php
                foreach($output3 as $index=>$value): ?>
                    <?php if(isset($this->listingSubcategoriaRel[$index])) {
                        $checked = 'checked="checked"';
                    } else{
                        $checked='';
                    } ?>
                    <input <?php echo $checked ?>  value="<?php echo $index ?>" name="profileSubCategoria[]" id="check<?php echo $index ?>" type="checkbox"><label for="check<?php echo $index ?>" class="label-check2"><?php echo $value ?></label>
                <?php endforeach; ?>
                </div>        
            </fieldset>
            <input class="boton-yellow-1 oswald" type="submit" value="SAVE &gt;&gt;">
        </form>
    </section>
</div>
<script>
    $(document).ready(function($){
            $("#div-drop-image").uploader({
                postFileUrl: '/partner/profiler/upload',
                maxFileSize:  2000, 
                maxFiles: 1,
                append: '.drop-image',
                dimensions: [145, 145],
                crop: true,
                name: 'logo',
                load:  <?php echo $this->json_logo; ?>
            });
            
            $("#upload-image").uploader({
                postFileUrl: '/partner/profiler/upload',
                maxFileSize:  2000, 
                maxFiles: 100,
                append: '.preview-galery',
                //dimensions: [295, 166], //real 590 x 332
                dimensions: [590, 332], //real 590 x 332
                crop: true,
                scalePreview: .3, // 200%
                name: 'gallery',
                load:  <?php echo $this->json_images; ?>
            });
            
            
    });
</script>