<div class="page-wrap">
    <div class="banner">
        <div class="banner-image-left" >
            <div class="banner-image-left-center">
                <h1>Work with the Best</h1>
                <div class="div-center">
                    <form method="post">
                        <h2>Login</h2>
                        <span class="banner-login-label">Type your email address</span>
                        <input type="text" class="input-login" id="email" name="mail"/>
                        <span class="banner-login-label">Type your password</span>
                        <input type="password" class="input-login" id="password" name="password"/>
                        <div class="div-center-submit">
                            <input type="checkbox" name="check_01" id="check_01" />
                            <label for="check_01">Opción</label>
                            <span class="banner-login-label">Remember me</span>
                            <input id="login-submit" class='generals-buttons' onclick="submit()" type="button" value="SUBMIT>>">
                        </div>
                    </form>
                </div>
                <h3>Create an account | Forgot your password?</h3>
            </div>
        </div>
        <div class="banner-image-right">
            <img src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/images/imagen2.png" alt="" />
        </div>
        <div class="banner-image-shadow">
            <img src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/images/imagen3.png" alt="" />
        </div>
    </div>
    <div class="col-area">
        <div class="boxes">
            <div class='div-center'>
                <fieldset>
                    <legend><h2>Mexi-Go! News</h2></legend>
                    <div class="image-frame">
                        <img src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/images/slide5.jpg" alt="" title="" />
                    </div>
                    <h3>Lore impsum dolor</h3>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec fermentum massa...
                    </p>
                    <a class="read-more" href="/partners/news.html">Read More >></a>
                </fieldset>
            </div>
        </div>
        <div class="boxes">
            <div class='div-center'>
                <h2>Work with the Best</h2>
                <div class='sing-up-box'>
                    Sing Up
                </div>
                <p>
                    Online and in print we promote the lifestyle and culture of Mexico Directly to the most qualified Canadian demographic
                </p>
                <input type='button' value='BECOME A PARTNER' class='generals-buttons' id='btn-become-partner'/>
            </div>
        </div>
        <div class="boxes">
            <div class='div-center'>
                <h2>ONLINE AND IN PRINT</h2>
                <div class='grey-box'>
                    <p>
                        Elevate and enchance your listing Impress your clients.
                        Attract Canadian buyers.							
                    </p>
                    <h4>MEXI-GO.CA ONLINE</h4>
                    <h4 class='yellow-text'>REAL ESTATES LISTINGS ONLINE ADVERTISINGS PRINT MAGAZINE</h4>
                </div>
            </div>
        </div>
        <div class="boxes boxes-right">
            <div class='div-center'>
                <h2>Magazine</h2>
                <div class='magazine-box'>
                    <img src='<?php echo CST_Server_ServerStatic::getUrl(); ?>/images/magazine.png' title='' alt=''/>
                </div>
                <div class='learn-more'>
                    <a href="/magazine.html"><input type='button' value='LEARN MORE' class='generals-buttons' id='btn-learn-more'/></a>
                </div>
            </div>
        </div>
    </div>                       <!-- /COLUMNA LEFT---------------------- -->
</div>