<div id="central-content">
    <p class="oswald" id="my-account">My Account</p>
    <aside class="oswald" id="block-left">
        <p class=" bg-white" id="hi-lateral">HI blackswaninteractive</p>
        <div id="color-fondo">

            <?php echo $this->navigation()->menu()->render();?>
        </div>
        <div id="linea-fondo">
        </div>
    </aside>
    <section id="block-right">
        <h2 class="h2-cms oswald">Agents</h2>
        <p id="number-published"><span>Your current Agents:</span> You have <span>1 of 20</span> Agents Published</p>
        <table id="tabla-agentes">
            <tbody><tr>
                    <th id="th1">PLAN DETAILS</th>
                    <th id="th2"></th>
                    <th id="th3">Time Left</th>
                    <th id="th4">Status</th>
                    <th id="th5">Subscription</th>
                </tr>
                <tr>
                    <td class="oswald" id="td1"><p>SILVER PACKAGE</p><p></p></td>
                    <td id="td2"><p>100 Listings<br>200 sales agents</p><p></p></td>
                    <td id="td3"><span>months</span> 5</td>
                    <td class="oswald" id="td4"><img src="images/black-star.png"><br>5 FEATURED</td>
                    <td class="oswald" id="td5"><a class="boton-yellow-2" href="">BUY MORE &gt;&gt;</a> </td>
                </tr>
            </tbody></table>
        <div id="registros-agentes">
            <p class="align-right"><a class="add-agents oswald" href="">Add Agents</a></p>
            <div class="paginador">
                <span class="previous"><a href="">&lt;&lt; previous</a></span>
                <span class="number"><a href="">1</a></span>
                <span class="number actual"><a href="">2</a></span>
                <span class="puntos"></span>
                <span class="number "><a href="">10</a></span>
                <span class="next"><a href="">next &gt;&gt;</a></span>
            </div>
            <hr class="hr-custom">
            <section id="published">
                <h3><span class="oswald">Published</span> (Agents currently visible)</h3>
                <table cellspacing="0" cellpadding="0">
                    <tbody><tr>
                            <th class="th1"></th>
                            <th class="th2"></th>
                            <th class="th3"></th>
                            <th class="th4"># Listings</th>
                            <th class="th5"></th>                                            
                        </tr>
                        <tr>
                            <td class="td1"><a class="delete-icon" href="">delete</a></td>
                            <td class="td2">Member's name</td>
                            <td class="td3">blackswan@bksn.mx</td>
                            <td class="td4">3</td>
                            <td class="td5">
                                <a class="boton-yellow-1 oswald" href="">EDIT &gt;&gt;</a>
                                <a class="boton-yellow-2 oswald" href="">PREVIEW &gt;&gt;</a>
                                <a class="boton-yellow-2 oswald" href="">UNPUBLISH &gt;&gt;</a>
                            </td>                                            
                        </tr>

                    </tbody></table>
            </section>
            <hr class="hr-custom">
            <section id="draft">
                <h3><span class="oswald">Published</span> (Agents currently visible)</h3>
                <table cellspacing="0" cellpadding="0">
                    <tbody><tr>
                            <th class="th1"></th>
                            <th class="th2"></th>
                            <th class="th3"></th>
                            <th class="th4"># Listings</th>
                            <th class="th5"></th>                                            
                        </tr>
                        <tr class="grey-line-under">
                            <td class="td1"><a class="delete-icon" href="">delete</a></td>
                            <td class="td2">Member's name</td>
                            <td class="td3">blackswan@bksn.mx</td>
                            <td class="td4">3</td>
                            <td class="td5">
                                <a class="boton-yellow-1 oswald" href="">EDIT &gt;&gt;</a>
                                <a class="boton-yellow-2 oswald" href="">PREVIEW &gt;&gt;</a>
                                <a class="boton-yellow-2 oswald" href="">UNPUBLISH &gt;&gt;</a>
                            </td>                                            
                        </tr>
                        <tr class="grey-line-under">
                            <td href="" <a="" class="td1">delete</td>
                            <td class="td2">Member's name</td>
                            <td class="td3">blackswan@bksn.mx</td>
                            <td class="td4">3</td>
                            <td class="td5">
                                <a class="boton-yellow-1 oswald" href="">EDIT &gt;&gt;</a>
                                <a class="boton-yellow-2 oswald" href="">PREVIEW &gt;&gt;</a>
                                <a class="boton-yellow-2 oswald" href="">UNPUBLISH &gt;&gt;</a>
                            </td>                                            
                        </tr>
                        <tr>
                            <td class="td1"><a class="delete-icon" href="">delete</a></td>
                            <td class="td2">Member's name</td>
                            <td class="td3">blackswan@bksn.mx</td>
                            <td class="td4">3</td>
                            <td class="td5">
                                <a class="boton-yellow-1 oswald" href="">EDIT &gt;&gt;</a>
                                <a class="boton-yellow-2 oswald" href="">PREVIEW &gt;&gt;</a>
                                <a class="boton-yellow-2 oswald" href="">UNPUBLISH &gt;&gt;</a>
                            </td>                                            
                        </tr>
                    </tbody></table>
            </section>
            <hr class="hr-custom">
            <div class="paginador">
                <span class="previous"><a href="">&lt;&lt; previous</a></span>
                <span class="number"><a href="">1</a></span>
                <span class="number actual"><a href="">2</a></span>
                <span class="puntos"></span>
                <span class="number "><a href="">10</a></span>
                <span class="next"><a href="">next &gt;&gt;</a></span>
            </div>
            <hr class="hr-custom">
            <p class="auto-renewal">Auto Renewal ON</p>
        </div>
    </section>
</div>