<div id="central-content">
    <p class="oswald" id="my-account">My Account</p>
    <aside class="oswald" id="block-left">
        <p class=" bg-white" id="hi-lateral">HI blackswaninteractive</p>
        <div id="color-fondo">

            <p class="lateral-selected " id="account-settings-menu"><a href="account-settings.php">ACCOUNT SETTINGS</a></p>
            <nav>
                <div class="menu-lateral-bg-gris-oscuro">
                    <p class="text-white " id="manage-your-style">Manage your</p>
                    <ul>
                        <li class="text-yellow menu-lateral-relative"><a title="go to profile page" href="profile-page.php">PROFILE PAGE</a></li>
                        <li class="lateral-selected text-yellow "><a title="go to agents" href="agents.php">AGENTS</a></li>
                        <li class="text-yellow menu-lateral-relative"><a title="go to real estate listings" href="real-estate-listings.php">REAL ESTATE LISTINGS</a></li>
                    </ul>
                </div>
                <ul>
                    <li class="text-yellow menu-lateral-bg-gris-claro" id="menu-buy"><a href="">BUY</a></li>
                    <li class="lateral-selected"><a href="">EMAIL PREFERENCES</a></li>
                    <li><a href="reset-password">ACCOUNT PASSWORD</a></li>
                    <li><a href="">SIGN OUT</a></li>
                </ul>
            </nav>    
        </div>
        <div id="linea-fondo">
        </div>
    </aside>
    <section id="block-right">
        <form id="email-preferences">
            <h2 class="oswald h2-cms">Email Preferences</h2>
            <div class="center-checkboxes">
                <div class="general-checkbox">
                    <input type="checkbox" name="check_01" id="check_01">
                    <label for="check_01">Opción</label>
                    <span class="banner-login-label">Mexi-Go! Newsletter</span>
                </div>
                <div class="general-checkbox checkbox-left">
                    <input type="checkbox" name="check_01" id="check_01">
                    <label for="check_01">Opción</label>
                    <span class="banner-login-label">Special Offers</span>
                </div>
            </div>
            <div class="clear-both"></div>
            <div class="grey-bar">
                <div class="center-content">
                    <div class="general-checkbox">
                        <input type="checkbox" name="check_01" id="check_01">
                        <label for="check_01">Opción</label>
                        <span class="banner-login-label white-label">Unsubscribe me from all Mexi-Go! emails</span>
                    </div>
                </div>
            </div>
        </form>
    </section>
</div>