<div class="page-wrap clear-both">
    <div class="colleft homecoll adv-search input-default-format omi-check"> 
        <div id="" class="oswald"><h2>Dream Home Search</h2><span id="pestaña-adv-rent" class="switchBuyRent round-corner-top-8 oswald top-box-shad">RENT</span><span id="pestaña-adv-buy" class="switchBuyRent oswald round-corner-top-8 top-box-shad ">BUY</span></div>
        <div id="pestaña-adv-buy-blk">
            <form>
                <div id="sec-div"><span class="oswald">Advanced Search</span><a href="/map-search.html" class="boton-css-gradient-grey boton-css-formato round-corner-5 oswald">MAP SEARCH >></a></div>
                <p class="redbox oswald">SELECT AREA</p>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="listingRegion">Region</label>
                    <div class="flecha-combo"><select type="text" id="listingRegion" name="listingRegion" ><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="city" class="label-special-width">City</label>
                    <div class="flecha-combo"><select type="text" id="city" name="city" ><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>


                <p class="redbox oswald">STATUS</p>
                <div class="combo-fix">
                    <label for="available">Available</label>
                    <div class="flecha-combo"><select type="text" id="available" name="available" ><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <p class="redbox oswald">SELECT PROPERTY TYPE</p>
                <div class="float-left">
                    <div class="combo-fix float-left inline-block clear-none">
                        <label for="listingStatus">Listing Status</label>
                        <div class="flecha-combo"><select type="text" id="listingStatus" name="listingStatus" ><option>Any</option><option>Yes</option><option>No</option></select></div>
                    </div>
                    <div class="combo-fix float-left inline-block clear-none">
                        <label for="propertyType" class="label-special-width">Property Type</label>
                        <div class="flecha-combo"><select type="text" id="propertyType" name="propertyType" ><option>Any</option><option>Yes</option><option>No</option></select></div>
                    </div>
                </div>
                <p class="redbox oswald">PRICE</p>
                <div class="combo-fix">
                    <label for="priceValue">$ </label>
                    <input type="text" id="priceValue" name="priceValue" class="float-left special-margen-right"/>
                    <div class="flecha-combo-chico-1"><select type="text" id="priceCoin" name="priceCoin" class="select-chico-1"><option>USD</option><option>AUS</option><option>EUR</option></select></div>
                </div>
                <p class="redbox oswald">PROPERTY DETAILS</p>
                <div class="combo-fix">
                    <label for="houseValue">House</label>
                    <input type="text" id="houseValue" name="houseValue" class="float-left special-margen-right"/>
                    <div class="flecha-combo-chico-1"><select type="text" id="houseMedida" name="houseMedida" class="select-chico-1"><option>M&sup2;</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix">
                    <label for="landValue">Land</label>
                    <input type="text" id="landValue" name="landValue" class="float-left special-margen-right"/>
                    <div class="flecha-combo-chico-1"><select type="text" id="landMedida" name="landMedida" class="select-chico-1"><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <p class="redbox oswald">SELECT FEATURES</p>
                <div class="margin-bottom-special">
                    <div class="combo-fix float-left inline-block clear-none">
                        <label for="bedroom">Bedroom</label>
                        <div class="flecha-combo"><select type="text" id="bedroom" name="bedroom" ><option>Any</option><option>1</option><option>2</option></select></div>
                    </div>
                    <div class="combo-fix float-left inline-block clear-none">
                        <label for="bathrooms" class="label-special-width">Bathrooms</label>
                        <div class="flecha-combo"><select type="text" id="bathrooms" name="bathrooms" ><option>Any</option><option>1</option><option>2</option></select></div>
                    </div>
                </div>
                <div  class="margin-bottom-special">
                    <div class="combo-fix float-left inline-block clear-none">
                        <label for="style">Style</label>
                        <div class="flecha-combo"><select type="text" id="style" name="style" ><option>Any</option><option>1</option><option>2</option></select></div>
                    </div>
                    <div class="combo-fix float-left inline-block clear-none">
                        <label for="keyword" class="label-special-width">Keyword</label>
                        <input type="text" id="keyword" name="keyword" class="float-left"/>
                    </div>
                </div>
                <div  class="margin-bottom-special">
                    <div class="combo-fix float-left inline-block clear-none">
                        <label for="garage">Garage</label>
                        <div class="flecha-combo"><select type="text" id="garage" name="garage" ><option>Any</option><option>1</option><option>2</option></select></div>
                    </div>
                    <div class="combo-fix float-left inline-block clear-none">
                        <label for="address" class="label-special-width">Address</label>
                        <input type="text" id="address" name="address" class="float-left"/>
                    </div>
                </div>
                <div class="margin-bottom-special">
                    <div class="combo-fix float-left inline-block clear-none">
                        <label for="view">View</label>
                        <div class="flecha-combo"><select type="text" id="view" name="view" ><option>Any</option><option>1</option><option>2</option></select></div>
                    </div>
                    <div class="combo-fix float-left inline-block clear-none">
                        <label for="size" class="label-special-width">Size (sq.ft.)</label>
                        <input type="text" id="size" name="size" class="float-left special-margen-right"/>
                    </div>
                </div>
                <div class="combo-fix">
                    <label for="recreation">Recreational Areas</label>
                    <div class="flecha-combo"><select type="text" id="recreation" name="recreation" ><option>Any</option><option>1</option><option>2</option></select></div>
                </div>
                <p class="redbox-center oswald showAmenitiesBuy elemHid hand">AMENITIES</p>
                <div class="contenedor-picks-1 hided-now">
                    <div class="pick-izq-2">
                        <label for="checkBBQ" id="label-checkBBQ" class="label-check3 check-special">BBQ Area</label><input id="checkBBQ" name="checkBBQ" type="checkbox" />
                        <label for="checkBeach" id="label-checkBeach" class=" label-check3 check-special">Beach Club</label><input id="checkBeach" type="checkbox" />
                        <label for="checkBeamed" id="label-checkBeamed" class="label-check3 check-special">Beamed Ceilings</label><input id="checkBeamed" type="checkbox" />
                        <label for="checkBreakfast" id="label-checkBreakfast" class="label-check3 check-special">Breakfast Nook</label><input id="checkBreakfast" type="checkbox" />
                        <label for="checkCable" id="label-checkCable" class="label-check3 check-special">Cable Television</label><input id="checkCable" type="checkbox" />
                        <label for="checkCathedral" id="label-checkCathedral" class="label-check3 check-special">Cathedral Ceilings</label><input id="checkCathedral" type="checkbox" />
                        <label for="checkDeck" id="label-checkDeck" class="label-check3 check-special">Deck</label><input id="checkDeck" type="checkbox" />
                        <label for="checkFence" id="label-checkFence" class="label-check3 check-special">Fence / Wall</label><input id="checkFence" type="checkbox" />
                        <label for="checkFireplace" id="label-checkFireplace" class="label-check3 check-special">Fireplace</label><input id="checkFireplace" type="checkbox" />
                        <label for="checkFountain" id="label-checkFountain" class="label-check3 check-special">Fountain</label><input id="checkFountain" type="checkbox" />
                        <label for="checkGames" id="label-checkGames" class="label-check3 check-special">Games Room</label><input id="checkGames" type="checkbox" />
                    </div>
                    <div class="pick-med-2">
                        <label for="checkGarden" id="label-checkGarden" class="label-check3 check-special">Garden</label><input id="checkGarden" name="checkGarden" type="checkbox" />
                        <label for="checkGated" id="label-checkGated" class="label-check3 check-special">Gated</label><input id="checkGated" type="checkbox" />
                        <label for="checkGuarded" id="label-checkGuarded" class="label-check3 check-special">Guarded</label><input id="checkGuarded" type="checkbox" />
                        <label for="checkGym" id="label-checkGym" class="label-check3 check-special">Gym</label><input id="checkGym" type="checkbox" />
                        <label for="checkHighInternet" id="label-checkHighInternet" class="label-check3 check-special">High Speed Internet</label><input id="checkHighInternet" type="checkbox" />
                        <label for="checkHotTub" id="label-checkHotTub" class="label-check3 check-special">Hot Tub</label><input id="checkHotTub" type="checkbox" />
                        <label for="checkPalapa" id="label-checkPalapa" class="label-check3 check-special">Palapa</label><input id="checkPalapa" type="checkbox" />
                        <label for="checkPatio" id="label-checkPatio" class="label-check3 check-special">Patio</label><input id="checkPatio" type="checkbox" />
                        <label for="checkPool" id="label-checkPool" class="label-check3 check-special">Pool</label><input id="checkPool" type="checkbox" />
                        <label for="checkElevator" id="label-checkElevator" class="label-check3 check-special">Private Elevator</label><input id="checkElevator" type="checkbox" />
                        <label for="checkRoofTerrace" id="label-checkRoofTerrace" class="label-check3 check-special">Roof Top Terrace</label><input id="checkRoofTerrace" type="checkbox" />
                    </div>
                    <div class="pick-der-2">
                        <label for="checkSatelite" id="label-checkSatelite" class="label-check3 check-special">Satellite Television</label><input id="checkSatelite" name="checkSatelite" type="checkbox" />
                        <label for="checkSauna" id="label-checkSauna" class="label-check3 check-special">Sauna</label><input id="checkSauna" type="checkbox" />
                        <label for="checkSecondKitchen" id="label-checkSecondKitchen" class="label-check3 check-special">Second Kitchen</label><input id="checkSecondKitchen" type="checkbox" />
                        <label for="checkSpa" id="label-checkSpa" class="label-check3 check-special">Spa</label><input id="checkSpa" type="checkbox" />
                        <label for="checkStorage" id="label-checkStorage" class="label-check3 check-special">Storage Area</label><input id="checkStorage" type="checkbox" />
                        <label for="checkSwimBar" id="label-checkSwimBar" class="label-check3 check-special">Swim-up Bar</label><input id="checkSwimBar" type="checkbox" />
                        <label for="checkTennis" id="label-checkTennis" class="label-check3 check-special">Tennis Court</label><input id="checkTennis" type="checkbox" />
                        <label for="checkTerrace" id="label-checkTerrace" class="label-check3 check-special">Terrace</label><input id="checkTerrace" type="checkbox" />
                        <label for="checkTheater" id="label-checkTheater" class="label-check3 check-special">Theater</label><input id="checkTheater" type="checkbox" />
                        <label for="checkWineCellar" id="label-checkWineCellar" class="label-check3 check-special">Wine Cellar</label><input id="checkWineCellar" type="checkbox" />
                        <label for="checkWifi" id="label-checkWifi" class="label-check3 check-special">Wireless Internet</label><input id="checkWifi" type="checkbox" />

                    </div>
                </div>
                <p class="redbox-center oswald showOutBuildingsBuy elemHid hand">OUT BUILDINGS</p>
                <div class="contenedor-picks-2 hided-now">
                    <div class="pick-izq-2">
                        <label for="checkBarn" id="label-checkBarn" class="label-check3 check-special">Barn / Stable</label><input id="checkBarn" name="checkBBQ" type="checkbox" />
                        <label for="checkBoatLift" id="label-checkBoatLift" class="label-check3 check-special">Boatlift</label><input id="checkBoatLift" type="checkbox" />
                        <label for="checkCarPort" id="label-checkCarPort" class="label-check3 check-special">Car Port</label><input id="checkCarPort" type="checkbox" />
                        <label for="checkCasita" id="label-checkCasita" class="label-check3 check-special">Casita</label><input id="checkCasita" type="checkbox" />

                    </div>
                    <div class="pick-med-2">
                        <label for="checkDock" id="label-checkDock" class="label-check3 check-special">Dock / Pier</label><input id="checkDock" name="checkDock" type="checkbox" />
                        <label for="checkGazebo" id="label-checkGazebo" class="label-check3 check-special">Gazebo</label><input id="checkGazebo" type="checkbox" />
                        <label for="checkMaidsQuarters" id="label-checkMaidsQuarters" class="label-check3 check-special">Maids Quarters</label><input id="checkMaidsQuarters" type="checkbox" />
                        <label for="checkPergola" id="label-checkPergola" class="label-check3 check-special">Pergola</label><input id="checkPergola" type="checkbox" />								
                    </div>
                    <div class="pick-der-2">
                        <label for="checkPoolHouse" id="label-checkPoolHouse" class="label-check3 check-special">Pool House</label><input id="checkPoolHouse" name="checkPoolHouse" type="checkbox" />
                        <label for="checkStudio" id="label-checkStudio" class="label-check3 check-special">Studio</label><input id="checkStudio" type="checkbox" />


                    </div>
                </div>
                <p class="redbox-center oswald showAppliancesBuy elemHid hand">APPLIANCES</p>
                <div  class="contenedor-picks-3 hided-now">
                    <div class="pick-izq-2">
                        <label for="checkAirConditioning" id="label-checkAirConditioning" class="label-check3 check-special">Air Conditioning</label><input id="checkBBQ" name="checkAirConditioning" type="checkbox" />
                        <label for="checkCeilingFan" id="label-checkCeilingFan" class="label-check3 check-special">Ceiling Fans</label><input id="checkCeilingFan" type="checkbox" />
                        <label for="checkCentralVac" id="label-checkCentralVac" class="label-check3 check-special">Central Vac</label><input id="checkCentralVac" type="checkbox" />
                        <label for="checkClothesDryer" id="label-checkClothesDryer" class="label-check3 check-special">Clothes Dryer</label><input id="checkClothesDryer" type="checkbox" />
                        <label for="checkClothesWasher" id="label-checkClothesWasher" class="label-check3 check-special">Clothes washer</label><input id="checkClothesWasher" type="checkbox" />
                        <label for="checkCompactorVac" id="label-checkCompactorVac" class="label-check3 check-special">Compactor Vac</label><input id="checkCompactorVac" type="checkbox" />
                        <label for="checkDish" id="label-checkDish" class="label-check3 check-special">Dishwasher</label><input id="checkDish" type="checkbox" />
                    </div>
                    <div class="pick-med-2">
                        <label for="checkDisposal" id="label-checkDisposal" class="label-check3 check-special">Disposal</label><input id="checkDisposal" name="checkGarden" type="checkbox" />
                        <label for="checkFreezer" id="label-checkFreezer" class="label-check3 check-special">Freezer</label><input id="checkFreezer" type="checkbox" />
                        <label for="checkIceMaker" id="label-checkIceMaker" class="label-check3 check-special">Ice Maker</label><input id="checkIceMaker" type="checkbox" />
                        <label for="checkMicrowave" id="label-checkMicrowave" class="label-check3 check-special">Microwave</label><input id="checkMicrowave" type="checkbox" />
                        <label for="checkMiniSplit" id="label-checkMiniSplit" class="label-check3 check-special">Mini-Split</label><input id="checkMiniSplit" type="checkbox" />
                        <label for="checkOvenElectric" id="label-checkOvenElectric" class="label-check3 check-special">Oven: Electric</label><input id="checkOvenElectric" type="checkbox" />
                        <label for="checkOvenGas" id="label-checkOvenGas" class="label-check3 check-special">Oven: Gas</label><input id="checkOvenGas" type="checkbox" />
                    </div>
                    <div class="pick-der-2">
                        <label for="checkRangeElectric" id="label-checkRangeElectric" class="label-check3 check-special">Range: Electric</label><input id="checkRangeElectric" name="checkSatelite" type="checkbox" />
                        <label for="checkRangeGas" id="label-checkRangeGas" class="label-check3 check-special">Range: Gas</label><input id="checkRangeGas" type="checkbox" />
                        <label for="checkRefrigerator" id="label-checkRefrigerator" class="label-check3 check-special">Refrigerator</label><input id="checkRefrigerator" type="checkbox" />
                        <label for="checkWaterHeater" id="label-checkWaterHeater" class="label-check3 check-special">Water Heater</label><input id="checkWaterHeater" type="checkbox" />
                        <label for="checkWaterPurification" id="label-checkWaterPurification" class="label-check3 check-special">Water Purification</label><input id="checkWaterPurification" type="checkbox" />
                        <label for="checkWineFridge" id="label-checkWineFridge" class="label-check3 check-special">Wine Fridge</label><input id="checkWineFridge" type="checkbox" />

                    </div>
                    <input class="boton-css-gradient-grey boton-css-formato round-corner-5 oswald" type="submit" value="SEARCH>>">

                </div>
            </form>
        </div>
        <div id="pestaña-adv-rent-blk" class="hided-now"><!-- bloke rent -->
            <div id="sec-div"><a href="/map-search.html" class="boton-css-gradient-grey boton-css-formato round-corner-5 oswald">MAP SEARCH >></a></div>
            <p class="redbox oswald">SELECT AREA</p>
            <div class="combo-fix float-left inline-block clear-none">
                <label for="listingRegionRent">Region</label>
                <div class="flecha-combo"><select type="text" id="listingRegionRent" name="listingRegionRent" ><option>Any</option><option>Yes</option><option>No</option></select></div>
            </div>
            <div class="combo-fix float-left inline-block clear-none">
                <label for="cityRent" class="label-special-width">City</label>
                <div class="flecha-combo"><select type="text" id="cityRent" name="cityRent" ><option>Any</option><option>Yes</option><option>No</option></select></div>
            </div>


            <p class="redbox oswald">STATUS</p>
            <div class="float-left mar-top-bot-10">
                <label for="checkDailyRent" id="label-checkDailyRent" class="check-special-dark-black">Rent Daily</label><input id="checkDailyRent" name="checkDailyRent" type="checkbox" />
                <label for="checkMonthlyRent" id="label-checkMonthlyRent" class="check-special-dark-black">Rent Monthly</label><input id="checkMonthlyRent" name="checkMonthlyRent" type="checkbox" />
                <label for="checkAnnualyRent" id="label-checkAnnualyRent" class="check-special-dark-black">Rent Annualy</label><input id="checkAnnualyRent" name="checkAnnualyRent" type="checkbox" />
            </div>
            <div class="float-left mar-top-bot-10">
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="checkIn">Travel dates</label>
                    <div class="flecha-combo-inter"><select name="checkIn" id="checkIn" type="text"><option>Check in</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none mar-lef-10">
                    <div class="flecha-combo-inter"><select name="checkOut" id="checkOut" type="text"><option>Check out</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none mar-lef-20">
                    <label style="width:105px !important" for="numberBedsRent">Number of Beds</label>
                    <div class="flecha-combo-chico-1"><select class="select-chico-1" name="numberBedsRent" id="numberBedsRent" type="text"><option>4</option><option>2</option><option>3</option></select></div>
                </div>
            </div>
            <p class="redbox oswald">SELECT PROPERTY TYPE</p>
            <div class="float-left">
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="listingStatusRent">Listing Status</label>
                    <div class="flecha-combo"><select type="text" id="listingStatusRent" name="listingStatusRent" ><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="propertyTypeRent" class="label-special-width">Property Type</label>
                    <div class="flecha-combo"><select type="text" id="propertyTypeRent" name="propertyTypeRent" ><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
            </div>
            <p class="redbox oswald">PRICE</p>
            <div class="combo-fix">
                <label for="priceValueRent">$ </label>
                <input type="text" id="priceValueRent" name="priceValueRent" class="float-left special-margen-right"/>
                <div class="flecha-combo-chico-1"><select type="text" id="priceCoinRent" name="priceCoinRent" class="select-chico-1"><option>USD</option><option>AUS</option><option>EUR</option></select></div>
            </div>
            <p class="redbox oswald">PROPERTY DETAILS</p>
            <div class="combo-fix">
                <label for="houseValue">House</label>
                <input type="text" id="houseValueRent" name="houseValueRent" class="float-left special-margen-right"/>
                <div class="flecha-combo-chico-1"><select type="text" id="houseMedidaRent" name="houseMedidaRent" class="select-chico-1"><option>M&sup2;</option><option>Yes</option><option>No</option></select></div>
            </div>
            <div class="combo-fix">
                <label for="landValueRent">Land</label>
                <input type="text" id="landValueRent" name="landValueRent" class="float-left special-margen-right"/>
                <div class="flecha-combo-chico-1"><select type="text" id="landMedidaRent" name="landMedidaRent" class="select-chico-1"><option>Any</option><option>Yes</option><option>No</option></select></div>
            </div>
            <p class="redbox oswald">SELECT FEATURES</p>
            <div class="margin-bottom-special">
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="bedroomRent">Bedroom</label>
                    <div class="flecha-combo"><select type="text" id="bedroomRent" name="bedroomRent" ><option>Any</option><option>1</option><option>2</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="bathroomsRent" class="label-special-width">Bathrooms</label>
                    <div class="flecha-combo"><select type="text" id="bathroomsRent" name="bathroomsRent" ><option>Any</option><option>1</option><option>2</option></select></div>
                </div>
            </div>
            <div  class="margin-bottom-special">
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="styleRent">Style</label>
                    <div class="flecha-combo"><select type="text" id="styleRent" name="styleRent" ><option>Any</option><option>1</option><option>2</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="keywordRent" class="label-special-width">Keyword</label>
                    <input type="text" id="keywordRent" name="keywordRent" class="float-left"/>
                </div>
            </div>
            <div  class="margin-bottom-special">
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="garageRent">Garage</label>
                    <div class="flecha-combo"><select type="text" id="garageRent" name="garageRent" ><option>Any</option><option>1</option><option>2</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="addressRent" class="label-special-width">Address</label>
                    <input type="text" id="addressRent" name="addressRent" class="float-left"/>
                </div>
            </div>
            <div class="margin-bottom-special">
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="viewRent">View</label>
                    <div class="flecha-combo"><select type="text" id="viewRent" name="viewRent" ><option>Any</option><option>1</option><option>2</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="sizeRent" class="label-special-width">Size (sq.ft.)</label>
                    <input type="text" id="sizeRent" name="sizeRent" class="float-left special-margen-right"/>
                </div>
            </div>
            <div class="combo-fix">
                <label for="recreationRent">Recreational Areas</label>
                <div class="flecha-combo"><select type="text" id="recreationRent" name="recreationRent" ><option>Any</option><option>1</option><option>2</option></select></div>
            </div>
            <p class="redbox-center oswald showAmenitiesBuy elemHid hand">AMENITIES</p>
            <div class="contenedor-picks-1 hided-now">
                <div class="pick-izq-2">
                    <label for="checkBBQRent" id="label-checkBBQRent" class="label-check3 check-special">BBQ Area</label><input id="checkBBQRent" name="checkBBQRent" type="checkbox" />
                    <label for="checkBeachRent" id="label-checkBeachRent" class=" label-check3 check-special">Beach Club</label><input id="checkBeachRent" type="checkbox" />
                    <label for="checkBeamedRent" id="label-checkBeamedRent" class="label-check3 check-special">Beamed Ceilings</label><input id="checkBeamedRent" type="checkbox" />
                    <label for="checkBreakfastRent" id="label-checkBreakfastRent" class="label-check3 check-special">Breakfast Nook</label><input id="checkBreakfastRent" type="checkbox" />
                    <label for="checkCableRent" id="label-checkCableRent" class="label-check3 check-special">Cable Television</label><input id="checkCableRent" type="checkbox" />
                    <label for="checkCathedralRent" id="label-checkCathedralRent" class="label-check3 check-special">Cathedral Ceilings</label><input id="checkCathedralRent" type="checkbox" />
                    <label for="checkDeckRent" id="label-checkDeckRent" class="label-check3 check-special">Deck</label><input id="checkDeckRent" type="checkbox" />
                    <label for="checkFenceRent" id="label-checkFenceRent" class="label-check3 check-special">Fence / Wall</label><input id="checkFenceRent" type="checkbox" />
                    <label for="checkFireplaceRent" id="label-checkFireplaceRent" class="label-check3 check-special">Fireplace</label><input id="checkFireplaceRent" type="checkbox" />
                    <label for="checkFountainRent" id="label-checkFountainRent" class="label-check3 check-special">Fountain</label><input id="checkFountainRent" type="checkbox" />
                    <label for="checkGamesRent" id="label-checkGamesRent" class="label-check3 check-special">Games Room</label><input id="checkGamesRent" type="checkbox" />
                </div>
                <div class="pick-med-2">
                    <label for="checkGardenRent" id="label-checkGardenRent" class="label-check3 check-special">Garden</label><input id="checkGardenRent" name="checkGarden" type="checkbox" />
                    <label for="checkGatedRent" id="label-checkGatedRent" class="label-check3 check-special">Gated</label><input id="checkGatedRent" type="checkbox" />
                    <label for="checkGuardedRent" id="label-checkGuardedRent" class="label-check3 check-special">Guarded</label><input id="checkGuardedRent" type="checkbox" />
                    <label for="checkGymRent" id="label-checkGymRent" class="label-check3 check-special">Gym</label><input id="checkGymRent" type="checkbox" />
                    <label for="checkHighInternetRent" id="label-checkHighInternetRent" class="label-check3 check-special">High Speed Internet</label><input id="checkHighInternetRent" type="checkbox" />
                    <label for="checkHotTubRent" id="label-checkHotTubRent" class="label-check3 check-special">Hot Tub</label><input id="checkHotTubRent" type="checkbox" />
                    <label for="checkPalapaRent" id="label-checkPalapaRent" class="label-check3 check-special">Palapa</label><input id="checkPalapaRent" type="checkbox" />
                    <label for="checkPatioRent" id="label-checkPatioRent" class="label-check3 check-special">Patio</label><input id="checkPatioRent" type="checkbox" />
                    <label for="checkPoolRent" id="label-checkPoolRent" class="label-check3 check-special">Pool</label><input id="checkPoolRent" type="checkbox" />
                    <label for="checkElevatorRent" id="label-checkElevatorRent" class="label-check3 check-special">Private Elevator</label><input id="checkElevatorRent" type="checkbox" />
                    <label for="checkRoofTerraceRent" id="label-checkRoofTerraceRent" class="label-check3 check-special">Roof Top Terrace</label><input id="checkRoofTerraceRent" type="checkbox" />
                </div>
                <div class="pick-der-2">
                    <label for="checkSateliteRent" id="label-checkSateliteRent" class="label-check3 check-special">Satellite Television</label><input id="checkSateliteRent" name="checkSatelite" type="checkbox" />
                    <label for="checkSaunaRent" id="label-checkSaunaRent" class="label-check3 check-special">Sauna</label><input id="checkSaunaRent" type="checkbox" />
                    <label for="checkSecondKitchenRent" id="label-checkSecondKitchenRent" class="label-check3 check-special">Second Kitchen</label><input id="checkSecondKitchenRent" type="checkbox" />
                    <label for="checkSpaRent" id="label-checkSpaRent" class="label-check3 check-special">Spa</label><input id="checkSpaRent" type="checkbox" />
                    <label for="checkStorageRent" id="label-checkStorageRent" class="label-check3 check-special">Storage Area</label><input id="checkStoragevRent" type="checkbox" />
                    <label for="checkSwimBarRent" id="label-checkSwimBarRent" class="label-check3 check-special">Swim-up Bar</label><input id="checkSwimBarvRent" type="checkbox" />
                    <label for="checkTennisRent" id="label-checkTennisRent" class="label-check3 check-special">Tennis Court</label><input id="checkTennisRent" type="checkbox" />
                    <label for="checkTerracev" id="label-checkTerraceRent" class="label-check3 check-special">Terrace</label><input id="checkTerraceRent" type="checkbox" />
                    <label for="checkTheaterRent" id="label-checkTheaterRent" class="label-check3 check-special">Theater</label><input id="checkTheaterRent" type="checkbox" />
                    <label for="checkWineCellarRent" id="label-checkWineCellarRent" class="label-check3 check-special">Wine Cellar</label><input id="checkWineCellarRent" type="checkbox" />
                    <label for="checkWifiRent" id="label-checkWifiRent" class="label-check3 check-special">Wireless Internet</label><input id="checkWifiRent" type="checkbox" />

                </div>
            </div>
            <p class="hand redbox-center oswald showOutBuildingsBuy elemHid">OUT BUILDINGS</p>
            <div class="contenedor-picks-2 hided-now">
                <div class="pick-izq-2">
                    <label for="checkBarnRent" id="label-checkBarnRent" class="label-check3 check-special">Barn / Stable</label><input id="checkBarnRent"  type="checkbox" />
                    <label for="checkBoatLiftRent" id="label-checkBoatLiftRent" class="label-check3 check-special">Boatlift</label><input id="checkBoatLiftRent" type="checkbox" />
                    <label for="checkCarPortRent" id="label-checkCarPortRent" class="label-check3 check-special">Car Port</label><input id="checkCarPortRent" type="checkbox" />
                    <label for="checkCasitaRent" id="label-checkCasitaRent" class="label-check3 check-special">Casita</label><input id="checkCasitaRent" type="checkbox" />

                </div>
                <div class="pick-med-2">
                    <label for="checkDockRent" id="label-checkDockRent" class="label-check3 check-special">Dock / Pier</label><input id="checkDockRent" name="checkDockRent" type="checkbox" />
                    <label for="checkGazeboRent" id="label-checkGazeboRent" class="label-check3 check-special">Gazebo</label><input id="checkGazeboRent" type="checkbox" />
                    <label for="checkMaidsQuartersRent" id="label-checkMaidsQuartersRent" class="label-check3 check-special">Maids Quarters</label><input id="checkMaidsQuartersRent" type="checkbox" />
                    <label for="checkPergolaRent" id="label-checkPergolaRent" class="label-check3 check-special">Pergola</label><input id="checkPergolaRent" type="checkbox" />								
                </div>
                <div class="pick-der-2">
                    <label for="checkPoolHouseRent" id="label-checkPoolHouseRent" class="label-check3 check-special">Pool House</label><input id="checkPoolHouseRent" name="checkPoolHouseRent" type="checkbox" />
                    <label for="checkStudioRent" id="label-checkStudioRent" class="label-check3 check-special">Studio</label><input id="checkStudioRent" type="checkbox" />


                </div>
            </div>
            <p class="redbox-center oswald showAppliancesBuy elemHid hand">APPLIANCES</p>
            <div  class="contenedor-picks-3 hided-now">
                <div class="pick-izq-2">
                    <label for="checkAirConditioningRent" id="label-checkAirConditioningRent" class="label-check3 check-special">Air Conditioning</label><input id="checkAirConditioningRent" name="checkAirConditioningRent" type="checkbox" />
                    <label for="checkCeilingFanRent" id="label-checkCeilingFanRent" class="label-check3 check-special">Ceiling Fans</label><input id="checkCeilingFanRent" type="checkbox" />
                    <label for="checkCentralVacRent" id="label-checkCentralVacRent" class="label-check3 check-special">Central Vac</label><input id="checkCentralVacRent" type="checkbox" />
                    <label for="checkClothesDryeRentr" id="label-checkClothesDryerRent" class="label-check3 check-special">Clothes Dryer</label><input id="checkClothesDryerRent" type="checkbox" />
                    <label for="checkClothesWasherRent" id="label-checkClothesWasherRent" class="label-check3 check-special">Clothes washer</label><input id="checkClothesWasherRent" type="checkbox" />
                    <label for="checkCompactorVacRent" id="label-checkCompactorVacRent" class="label-check3 check-special">Compactor Vac</label><input id="checkCompactorVacRent" type="checkbox" />
                    <label for="checkDisRenth" id="label-checkDishRent" class="label-check3 check-special">Dishwasher</label><input id="checkDishRent" type="checkbox" />
                </div>
                <div class="pick-med-2">
                    <label for="checkDisposalRent" id="label-checkDisposalRent" class="label-check3 check-special">Disposal</label><input id="checkDisposalRent"  type="checkbox" />
                    <label for="checkFreezerRent" id="label-checkFreezerRent" class="label-check3 check-special">Freezer</label><input id="checkFreezeRentr" type="checkbox" />
                    <label for="checkIceMakerRent" id="label-checkIceMakerRent" class="label-check3 check-special">Ice Maker</label><input id="checkIceMakerRent" type="checkbox" />
                    <label for="checkMicrowaveRent" id="label-checkMicrowaveRent" class="label-check3 check-special">Microwave</label><input id="checkMicrowaveRent" type="checkbox" />
                    <label for="checkMiniSplitRent" id="label-checkMiniSplitv" class="label-check3 check-special">Mini-Split</label><input id="checkMiniSplitRent" type="checkbox" />
                    <label for="checkOvenElectricRent" id="label-checkOvenElectricRent" class="label-check3 check-special">Oven: Electric</label><input id="checkOvenElectricRent" type="checkbox" />
                    <label for="checkOvenGasRent" id="label-checkOvenGasRent" class="label-check3 check-special">Oven: Gas</label><input id="checkOvenGasRent" type="checkbox" />
                </div>
                <div class="pick-der-2">
                    <label for="checkRangeElectricRent" id="label-checkRangeElectricRent" class="label-check3 check-special">Range: Electric</label><input id="checkRangeElectricRent"  type="checkbox" />
                    <label for="checkRangeGasRent" id="label-checkRangeGasRent" class="label-check3 check-special">Range: Gas</label><input id="checkRangeGasRent" type="checkbox" />
                    <label for="checkRefrigeratorRent" id="label-checkRefrigeratorRent" class="label-check3 check-special">Refrigerator</label><input id="checkRefrigeratorRent" type="checkbox" />
                    <label for="checkWaterHeaterRent" id="label-checkWaterHeaterRent" class="label-check3 check-special">Water Heater</label><input id="checkWaterHeaterRent" type="checkbox" />
                    <label for="checkWaterPurificationRent" id="label-checkWaterPurificationRent" class="label-check3 check-special">Water Purification</label><input id="checkWaterPurificationRent" type="checkbox" />
                    <label for="checkWineFridgeRent" id="label-checkWineFridgeRent" class="label-check3 check-special">Wine Fridge</label><input id="checkWineFridgeRent" type="checkbox" />

                </div>
            </div>

        </div>                                      <!-- /COLUMNA LEFT---------------------- -->
    </div>

    <div class="colright homecoll">           <!-- COLUMNA RIGHT---------------------- -->
        <?php echo $this->MenuLateral('lateral-entero');?>

    </div>
</div>