        
<div id="central-content">
    <section id="left-content" class="contact-agent">
        <h3 class="no-margin h3-cms oswald oswald-pink font-18"  style="padding-left: 7px;">FIND AGENTS</h3>
        <div id="agent-search">
            <p class="grey-bar-style-2 font-18 oswald">Compliment Us/Make a Suggestion</p>
            <form id="search-real-state-agents">
                <div class="left-column">
                    <p><label>First Name</label><input type="text"></p>
                    <p><label>Last Name</label><input type="text"></p>
                    <p><label>Brokerage</label><input type="text"></p>
                    <p><label>Keyword</label><input type="text"></p>
                </div>
                <div class="right-column">
                    <div class="combo-fix">
                        <label for="accountCountry">City or Country:</label>
                        <div class="flecha-combo"><select type="text" id="accountCountry" name="accountCountry" ><option>Uruguay</option><option>Brasil</option></select></div>
                    </div>
                    <div class="combo-fix">
                        <label for="accountCountry">Region:</label>
                        <div class="flecha-combo"><select type="text" id="accountCountry" name="accountCountry" ><option>Uruguay</option><option>Brasil</option></select></div>
                    </div>
                    <p><label>Address</label><input type="text"></p>
                </div>
                <div class="clear-both"></div>
                <div class="separator-20"></div>
                <div id="search-agent-submit">
                    <a class="boton-gris-basico button-light-shadow oswald" href="">SEARCH >></a>
                </div>

            </form>
            <img src="/front/images/contact-form-drop-shadow.png" class="general-drop-shadow">
        </div>
        <div class="separator-20"></div>
        <hr class="hr-gris-black-dashed">
        <div class="separator-10"></div>
        <p style="float: left;"> <span class="letter-pink bold">10</span> Agents Found | View 10 per page</p>
        <div class="paginador">
            <span class="previous"><a href="">&lt;&lt; previous</a></span>
            <span class="number"><a href="">1</a></span>
            <span class="number actual"><a href="">2</a></span>
            <span class="puntos"></span>
            <span class="number "><a href="">10</a></span>
            <span class="next"><a href="">next &gt;&gt;</a></span>
        </div>
        <h3 class="float-left separator-10 font-j1 font-jred oswald">Agents</h3>
        <table id="table-agents" class="agents-2">
            <tbody>
                <tr>
                    <td>
                        <div class="photo-frame">
                            <img src="/front/images/grey-background.jpg"/>
                        </div>
                        <div class="align-left contact-photos">
                            <h3 class="h3-cms font-18 oswald oswald-pink">MICHAEL MURPHY</h3>
                            <h3 class="h3-cms font-18 oswald oswald-grey">MEXICO / BRUCERIAS</h3>
                            <p>Certified international property Specialist</p>
                            <a class="read-more">View Details >></a>
                        </div>
                    </td>
                    <td>
                        <div class="photo-frame">
                            <img src="/front/images/grey-background.jpg"/>
                        </div>
                        <div class="align-left contact-photos">
                            <h3 class="h3-cms font-18 oswald oswald-pink">MICHAEL MURPHY</h3>
                            <h3 class="h3-cms font-18 oswald oswald-grey">MEXICO / BRUCERIAS</h3>
                            <p>Certified international property Specialist</p>
                            <a class="read-more">View Details >></a>
                        </div>
                    </td>
                    <td>
                        <div class="photo-frame">
                            <img src="/front/images/grey-background.jpg"/>
                        </div>
                        <div class="align-left contact-photos">
                            <h3 class="h3-cms font-18 oswald oswald-pink">MICHAEL MURPHY</h3>
                            <h3 class="h3-cms font-18 oswald oswald-grey">MEXICO / BRUCERIAS</h3>
                            <p>Certified international property Specialist</p>
                            <a class="read-more">View Details >></a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="photo-frame">
                            <img src="/front/images/grey-background.jpg"/>
                        </div>
                        <div class="align-left contact-photos">
                            <h3 class="h3-cms font-18 oswald oswald-pink">MICHAEL MURPHY</h3>
                            <h3 class="h3-cms font-18 oswald oswald-grey">MEXICO / BRUCERIAS</h3>
                            <p>Certified international property Specialist</p>
                            <a class="read-more">View Details >></a>
                        </div>
                    </td>
                    <td>
                        <div class="photo-frame">
                            <img src="/front/images/grey-background.jpg"/>
                        </div>
                        <div class="align-left contact-photos">
                            <h3 class="h3-cms font-18 oswald oswald-pink">MICHAEL MURPHY</h3>
                            <h3 class="h3-cms font-18 oswald oswald-grey">MEXICO / BRUCERIAS</h3>
                            <p>Certified international property Specialist</p>
                            <a class="read-more">View Details >></a>
                        </div>
                    </td>
                    <td>
                        <div class="photo-frame">
                            <img src="/front/images/grey-background.jpg"/>
                        </div>
                        <div class="align-left contact-photos">
                            <h3 class="h3-cms font-18 oswald oswald-pink">MICHAEL MURPHY</h3>
                            <h3 class="h3-cms font-18 oswald oswald-grey">MEXICO / BRUCERIAS</h3>
                            <p>Certified international property Specialist</p>
                            <a class="read-more">View Details >></a>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="paginador">
            <span class="previous"><a href="">&lt;&lt; previous</a></span>
            <span class="number"><a href="">1</a></span>
            <span class="number actual"><a href="">2</a></span>
            <span class="puntos"></span>
            <span class="number "><a href="">10</a></span>
            <span class="next"><a href="">next &gt;&gt;</a></span>
        </div>
        <hr class="hr-gris-black-dashed clear-both" style="float: left; margin: 110px 0px;">
        <div class="separator-20"></div>
    </section>
    <div class="news-box col col_5">
        <?php echo $this->MenuLateral('busqueda-lateral'); ?>
    </div>
</div>