       
<div id="central-content">
    <section id="left-content" class="contact-agent">
        <h3 class="no-margin h3-cms oswald oswald-pink font-18"  style="padding-left: 7px;">FIND AGENTS</h3>
        <div id="agent-search">
            <p class="grey-bar-style-2 font-18 oswald">Compliment Us/Make a Suggestion</p>
            <form id="search-real-state-agents">
                <div class="left-column">
                    <p><label>First Name</label><input type="text"></p>
                    <p><label>Last Name</label><input type="text"></p>
                    <p><label>Brokerage</label><input type="text"></p>
                    <p><label>Keyword</label><input type="text"></p>
                </div>
                <div class="right-column">
                    <div class="combo-fix">
                        <label for="accountCountry">City or Country:</label>
                        <div class="flecha-combo"><select type="text" id="accountCountry" name="accountCountry" ><option>Uruguay</option><option>Brasil</option></select></div>
                    </div>
                    <div class="combo-fix">
                        <label for="accountCountry">Region:</label>
                        <div class="flecha-combo"><select type="text" id="accountCountry" name="accountCountry" ><option>Uruguay</option><option>Brasil</option></select></div>
                    </div>
                    <p><label>Address</label><input type="text"></p>
                </div>
                <div class="clear-both"></div>
                <div class="separator-20"></div>
                <div id="search-agent-submit">
                    <a class="boton-gris-basico button-light-shadow oswald" href="">SEARCH >></a>
                </div>

            </form>
            <img src="/front/images/contact-form-drop-shadow.png" class="general-drop-shadow">
        </div>
        <div class="separator-20"></div>
        <hr class="hr-gris-black-dashed">
        <div class="separator-10"></div>
        <div class="" id="show-agent-listings-div">
            <h3 class="float-left separator-10 font-j1 font-jred oswald">Featured Listing</h3>
            <a class="read-more"><span><<</span>VIEW ALL</a>
            <div id="show-agent-listings-hiddable">
                <div class="property-box no-padd-left">
                    <div class="property-image-frame">
                        <img src="/front/images/property1.jpg" alt="" title="">
                    </div>
                    <div class="alto-frmt">
                        <h3 class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa</p>
                    </div>
                    <ul class="iconos-uls">
                        <li> <span class="icon-add-this"></span></li>    
                        <li> <span class="icon-letter"></span></li>
                        <li> <span class="icon-heart"></span></li>
                        <li><span class="icon-pfd"></span></li>
                    </ul>
                    <p><a href="" class="view-details-property">View Details &gt;&gt;</a></p>
                    <div class="float-right clear-both">Add to message<input type="checkbox"></div>

                </div>
                <div class="property-box">
                    <div class="property-image-frame">
                        <img src="/front/images/property1.jpg" alt="" title="">
                    </div>
                    <div class="alto-frmt">
                        <h3 class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa  </p>
                        <p class="letter-pink"> USD $ 1,350,00 </p>

                    </div>
                    <ul class="iconos-uls">
                        <li> <span class="icon-add-this"></span></li>    
                        <li> <span class="icon-letter"></span></li>
                        <li> <span class="icon-heart"></span></li>
                        <li><span class="icon-pfd"></span></li>
                    </ul>
                    <p><a href="" class="view-details-property">View Details &gt;&gt;</a></p>
                    <div class="float-right clear-both">Add to message<input type="checkbox"></div>
                </div>
                <div class="property-box no-padd-right">
                    <div class="property-image-frame">
                        <img src="/front/images/property1.jpg" alt="" title="">
                    </div>
                    <div class="alto-frmt">
                        <h3 class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa</p>
                    </div>
                    <ul class="iconos-uls">
                        <li> <span class="icon-add-this"></span></li>    
                        <li> <span class="icon-letter"></span></li>
                        <li> <span class="icon-heart"></span></li>
                        <li><span class="icon-pfd"></span></li>
                    </ul>
                    <p><a href="" class="view-details-property ">View Details &gt;&gt;</a></p>
                    <div class="float-right clear-both">Add to message<input type="checkbox"></div>
                </div>
            </div>
        </div>

        <hr class="hr-gris-black-dashed clear-both" style="float: left; margin: 110px 0px;">
        <div class="separator-20"></div>
    </section>
    <div class="news-box col col_5">
        <?php echo $this->MenuLateral('busqueda-lateral'); ?>
    </div>
</div>