
<div class="page-wrap clear-both detalle-agente-wrap">
    <div id="homes-detail-div" class="columnaleft">                                    <!-- COLUMNA LEFT---------------------- -->
        <p class="red-tittle-p oswald" >Dream Home Search<a class="float-right font-jred oswald font-j3" href="">BACK TO RESULTS</a></p>
        <div id="agent-detail-info-hiddable">
            <section class="tipo-detail-agente-left">
                <div id="foto-agent-id" class="foto-agent-1">
                    <img src="/front/images/agent-photo.jpg"/>
                </div>


            </section>

            <section class="tipo-detail-agente-right">
                <h3  class="mar-top-20 font-j1 font-jred oswald">Agent Details</h3>
                <p class="mar-top-bot-5"> <span class="font-j1 font-jred oswald">MICHELE MURPHY</span><br/>
                    <span class="line-height-14 font-j2 font-jlightgrey oswald">MEXICO / BUCERIAS</span></p>
                <p class="oswald mar-top-bot-10">Visit Website</p>
                <p class="mar-top-bot-10">Brokerage:<br/>Bienvenidos Real Estate</p>                        
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nunc diam, gravida ac fringilla vel, dignissim vel eros. Nulla sit amet quam ut nisi dapibus ullamcorper. In eu justo et metus ullamcorper lacinia. In faucibus molestie purus, sed pulvinar nibh porttitor eget. Ut pulvinar pellentesque leo vel lacinia. Suspendisse sagittis urna non dui dignissim volutpat interdum arcu porttitor. Mauris facilisis euismod tempor. Nunc scelerisque nisi vel sapien sagittis porta vel sit amet mauris. Cras vestibulum, velit vel malesuada interdum, sapien dui lacinia eros, ac imperdiet dolor massa vel sapien. Ut commodo sem eu augue ullamcorper scelerisque. Donec turpis tellus, ornare ac tristique vel, commodo suscipit metus.</p>
                <p class="mar-top-bot-10"><span class="font-jred bold">Address: </span>500 Lazaro Cardenas / Bucerias /Mexico  </p>
                <p class="mar-top-bot-10"><span class="font-jred bold">Phone Number: </span><span class="">322-2323</span></p>
                <p class="mar-top-bot-10"><span class="font-jred bold">Fax: </span><span class="">322-2323</span></p>
                <p class="mar-top-bot-10"><span class="font-jred bold">Mobile Phone: </span><span class="">322-2323</span></p>
                <div id="nav-agent-icons" class="mar-top-bot-20">
                    <nav>
                        <ul>
                            <li><a href=""><img src="/front/images/website-icon.png" /></a></li>
                            <li><a href=""><img src="/front/images/email-icon.png" /></a></li>
                            <li><a href=""><img src="/front/images/home-icon.png" /></a></li>
                            <li><a href=""><img src="/front/images/profile-icon.png" /></a></li>
                        </ul>
                    </nav>
                </div>






            </section>
        </div>
        <div id="agent-detail-info" class="trigger-sh float-left greybac ad-greyfrm">
            <div class="hide_option"></div>                 
        </div>
        <div>
            <span class="font-jred pad-lef-rig-10">10</span>Properties found | View 3 per page
            <div class="float-right paginador">
                <span class="previous"><a href="">&lt;&lt; previous</a></span>
                <span class="number"><a href="">1</a></span>
                <span class="number actual"><a href="">2</a></span>
                <span class="puntos"></span>
                <span class="number "><a href="">10</a></span>
                <span class="next"><a href="">next &gt;&gt;</a></span>
            </div>
        </div>
        <p class="barra-roja-texto oswald  font-j2">MICHAEL MURPHY Listings</p>
        <div id="show-agent-listings-div" class="">
            <div id="show-agent-listings-hiddable" >
                <div class="property-box no-padd-left">
                    <div class="property-image-frame">
                        <img title="" alt="" src="/front/images/property1.jpg">
                    </div>
                    <div class="alto-frmt">
                        <h3 class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa</p>
                    </div>
                    <ul class="iconos-uls">
                        <li> <span class="icon-add-this"></span></li>    
                        <li> <span class="icon-letter"></span></li>
                        <li> <span class="icon-heart"></span></li>
                        <li><span class="icon-pfd"></span></li>
                    </ul>
                    <p><a class="view-details-property" href="">View Details >></a></p>
                    <div class="float-right clear-both">Add to message<input type="checkbox" /></div>

                </div>
                <div class="property-box">
                    <div class="property-image-frame">
                        <img title="" alt="" src="/front/images/property1.jpg">
                    </div>
                    <div class="alto-frmt">
                        <h3 class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa  </p>
                        <p class="letter-pink"> USD $ 1,350,00 </p>

                    </div>
                    <ul class="iconos-uls">
                        <li> <span class="icon-add-this"></span></li>    
                        <li> <span class="icon-letter"></span></li>
                        <li> <span class="icon-heart"></span></li>
                        <li><span class="icon-pfd"></span></li>
                    </ul>
                    <p><a class="view-details-property" href="">View Details >></a></p>
                    <div class="float-right clear-both">Add to message<input type="checkbox" /></div>
                </div>
                <div class="property-box no-padd-right">
                    <div class="property-image-frame">
                        <img title="" alt="" src="/front/images/property1.jpg">
                    </div>
                    <div class="alto-frmt">
                        <h3 class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa</p>
                    </div>
                    <ul class="iconos-uls">
                        <li> <span class="icon-add-this"></span></li>    
                        <li> <span class="icon-letter"></span></li>
                        <li> <span class="icon-heart"></span></li>
                        <li><span class="icon-pfd"></span></li>
                    </ul>
                    <p><a class="view-details-property " href="">View Details >></a></p>
                    <div class="float-right clear-both">Add to message<input type="checkbox" /></div>
                </div>
            </div>
        </div>
        <div>
            <span class="font-jred pad-lef-rig-10">10</span>Properties found | View 3 per page
            <div class="float-right paginador">
                <span class="previous"><a href="">&lt;&lt; previous</a></span>
                <span class="number"><a href="">1</a></span>
                <span class="number actual"><a href="">2</a></span>
                <span class="puntos"></span>
                <span class="number "><a href="">10</a></span>
                <span class="next"><a href="">next &gt;&gt;</a></span>
            </div>
        </div>
        <p class="barra-negra-texto oswald font-j2">Added Homes</p>
        <div id="added-homes-wrap">
            <form>
                <div class="added-home-contacto">
                    <div class="added-thumb"><img src="/front/images/thumb-chico-casa.png" /></div>
                    <div class="added-desc">
                        <p class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa </p>
                        <p class="letter-pink"> USD $ 1,350,00 </p>
                    </div>
                    <div class="delete-added"><a href="">Remove this home x</a></div>
                </div>
                <div class="added-home-contacto">
                    <div class="added-thumb"><img src="/front/images/thumb-chico-casa.png" /></div>
                    <div class="added-desc">
                        <p class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa </p>
                        <p class="letter-pink"> USD $ 1,350,00 </p>
                    </div>
                    <div class="delete-added"><a href="">Remove this home x</a></div>
                </div>
                <div class="added-home-contacto">
                    <div class="added-thumb"><img src="/front/images/thumb-chico-casa.png" /></div>
                    <div class="added-desc">
                        <p class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa </p>
                        <p class="letter-pink"> USD $ 1,350,00 </p>
                    </div>
                    <div class="delete-added"><a href="">Remove this home x</a></div>
                </div>
                <div id="form-ctct">
                    <div><label for="">*Name:</label><input id="" name="" type="text" /></div>
                    <div><label for="">*Your E-mail:</label><input id="" name="" type="text" /></div>
                    <div><label for="">Phone number:</label><input id="" name="" type="text" /></div>
                    <div><label for="">*Your Message:</label><textarea></textarea></div>   
                    <input type="submit" value="SEND &gt;&gt;" class="boton-css-gradient-grey boton-css-formato round-corner-5 oswald" id="send-form">

                </div>
            </form>


        </div>
        <div class="custom-dashed-line mar-top-bot-20"></div>
    </div>                                      <!-- /COLUMNA LEFT---------------------- -->


    <div class="columnaright">           <!-- COLUMNA RIGHT---------------------- -->
        <?php echo $this->MenuLateral('busqueda-lateral'); ?>
    </div>
</div>