<div class="page-wrap clear-both">
    <div class="columnaleft bg-sombra-ajoba-buying">     <!-- COLUMNA LEFT---------------------- -->
        <p class="mar-top-20 red-tittle-p /*mar-bot-25*/ mar-rig-25">Buying Real Estate</p>
        <div class="linea-dash-largo pad-top-25">
            <div class="solo-sombra-fix">
                <div class="bg-buying-menu">
                    <div class="left-col-buying">
                        <?php echo $this->MenuLateral('menu-buying');?>
                    </div>
                    <div class="right-col-buying h4-odd-even">
                        <div class="mar-lef-25 image-wrapper-buying-selling"><img src="/front/images/closing-costs.jpg" /></div>
                        <h3 class="h3-buying mar-lef-25 font-j1 font-jred oswald">COSTS ASSOCIATED WITH PURCHASING A PROPERTY</h3>
                        <div id="" class="">
                            <p class="mar-lef-25 buying-grey-p">If you've been involved in a transaction in Mexico, you've probably been shocked at the closing costs. If you haven't, then you probably will be. This is a brief explanation of what they are, and why they are what they are. </p>
                            <p class="mar-lef-25 buying-black-p">If you've been involved in a transaction in Mexico, you've probably been shocked at the closing costs. If you haven't, then you probably will be. This is a brief explanation of what they are, and why they are what they are. </p>
                            <p class="mar-lef-25 buying-black-p">The first thing you should know as a buyer/investor in Mexico is that closing costs are relatively high, and virtually all are paid by the buyer. This is true for Mexican citizens as well, and especially true for those financing their properties.
                            </p>
                            <p class="mar-lef-25 buying-black-p">These higher costs, which in every case include an acquisition tax of 2%, are offset over a fairly short period of time by the minimal levels of annual property tax, in comparison to the property tax rates you're accustomed to up North.</p>
                            <p class="mar-lef-25 buying-black-p">For cash transactions, closing costs include a trustee fee, insurance, a tax appraisal fee, that pesky acquisition tax as well as a number of smaller fixed fees including a title search. For those financing, add to these costs fees for title insurance (this is optional), escrow fees, various loan fees, and a U.S. market appraisal.</p>
                            <p class="mar-lef-25 buying-black-p">Some of the costs are fixed, and others are related to the price being paid. The biggest item will be the acquisition tax (“ISABI”), which is a flat 2% of the price stated in pesos as of the date of closing, which is charged to the buyer. Since most purchase agreements are specified in dollars, the exact amount cannot be known until closing, when the current exchange rate between pesos and dollars is known, and applied to the dollar figure, and that result is multiplied by .02.</p>
                            <p class="mar-lef-25 buying-black-p">Other variable amounts, typically charged as a percentage of sales price in pesos include: Notary fees, appraiser's fee, and various registration fees at the public registry.</p>
                            <p class="mar-lef-25 buying-black-p">Fixed fees include: Foreign Affairs Ministry permit and registration, and foreign investment commission, preventive notice, certificates of no liens and of property taxes paid, trustee bank’s acceptance fee and first year’s fee, closing coordinator’s fee, US bank escrow fee for purchase money control, and a preliminary report.</p>
                            <p class="mar-lef-25 buying-black-p">Your closing coordinator will prepare and furnish the buyer an estimate of closing costs as soon as the bargain is reached. The buyer will then be asked to deposit 50% of these costs immediately into the special trust account we maintains for handling closing costs. The advance payment of 50% and the direct furnishing of funds for the closing office to disburse is necessary because, in contrast to US and Canada practice, substantial sums must be paid out in advance of closing, in order to start the process and move it toward that closing.
                            </p>
                            <p class="mar-lef-25 buying-black-p">The second half of the costs are then typically due a few days before the scheduled signing. The final exact total of costs is not typically known until some weeks after the signing when the fideicomiso is finally presented to the public registry. All the costs and all proceeds are of course accounted for in detail in the parties' final closing costs statements, and an appropriate refund is made if applicable.
                            </p>
                            <p class="mar-lef-25 buying-black-p">The total closing costs generally run 4.5-5.5% of the purchase price. To aid you in calculating your potential closing costs, keep in mind that the lower the price of the home, the higher the closing percentage because many fees are fixed and added to the 2% acquisition tax. This would mean, for example, that a lot costing $60,000 will probably garner closing costs of up to 10%, while an $8 million villa will run approximately 2.5%, including title insurance.</p>
                            <p class="mar-lef-25 buying-black-p">There are certain standard costs associated with closing the sale of a house. These fees are split between the buyer and the seller, as spelled out in the sales contract.</p>

                        </div>
                        <h4 id="display-div-2" class="h4-desplegable p-desplegable-hiden hand oswald">GOOD FAITH ESTIMATE</h4>
                        <div id="is-div-2" class="hided-now">
                            <p class="mar-lef-25 buying-black-p">Buyers will receive a "Good Faith Estimate" of closing costs at the time the loan application is submitted to the lender. The estimate is based on the loan officer's past experience and may not include all the closing costs.
                            </p>  
                        </div>
                        <h4 id="display-div-3" class="h4-desplegable p-desplegable-hiden hand oswald">STANDARD CLOSING COSTS</h4>
                        <div id="is-div-3" class="hided-now">
                            <p class="mar-lef-25 buying-red-p">Loan-Related Costs</p>
                            <ul class="mar-lef-25 mar-bot-15">
                                <li>:: Loan Origination Fee</li>
                                <li>:: Points (optional)</li>
                                <li>:: Appraisal Fee</li>
                                <li>:: Credit Report</li>
                                <li>:: Interest Payment</li>
                                <li>:: Escrow Account</li>
                            </ul>
                            <p class="mar-lef-25 buying-red-p">Taxes</p>
                            <ul class="mar-lef-25 mar-bot-15">
                                <li>:: Property Taxes</li>
                                <li>:: Transfer Taxes and recordin Fees</li>
                            </ul>
                            <p class="mar-lef-25 buying-red-p">Taxes</p>
                            <ul class="mar-lef-25 mar-bot-15">
                                <li>:: Homeowners Insurance</li>
                                <li>:: Flood or Quake Insurance</li>
                                <li>:: Private Mortgage Insurance (PMI)</li>
                                <li>:: Title Insurance</li>
                            </ul>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>   
    <div class="columnaright linea-dash-">           <!-- COLUMNA RIGHT---------------------- -->
        <?php echo $this->MenuLateral('busqueda-lateral');?>
    </div>

</div>