<div id="central-content">
    <section id="left-content" class="contact-agent">
        <h3 class="h3-cms oswald no-margin">Agent Details</h3>
        <div id="box-contact-form">
            <hr class="hr-gris-style2">
            <p class="yellow-bar font-23 oswald">Compliment Us/Make a Suggestion</p>
            <form class="form-account-setting" id="form-contact-page" method="POST" action="">
                <fieldset id="agent-contact-details">
                    <label for="profileFirstName">*Full Name:</label>
                    <input type="text" name="name" class="input-large required" id="contactFullName" title="Full Name">
                    <label for="profileLastName">*Email Address:</label>
                    <input type="text" name="email" id="contactEmail" class="required_email" title="E-mail">
                    <label for="profileLastName">Phone:</label>
                    <input type="text" name="profileCompany" id="contactEmail">
                    <label for="profileLastName">To:</label>
                    <input type="text" name="profileCompany" id="contactEmail">
                    <label for="profileLastName">Subject:</label>
                    <input type="text" name="profileCompany" id="contactEmail">
                    <table id="agent-description-table">
                        <tbody>
                            <tr>
                                <td>
                                    <label for="profileAgentProfile">Message To:</label>
                                </td>
                                <td>
                                    <textarea name="message" class="required" id="agentDescription" title="Message">Write a short description that will appear on your profile.</textarea>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="separator-20"></div>
                    <div class="align-right">
                        <input class="white-shadow boton-css-formato boton-css-gradient-yellow oswald round-corner-3 hand" type="submit" value="SUBMIT >>">
                    </div>
                </fieldset>
        </div>
        <img class="contact-form-drop-shadow" src="/front/images/contact-form-drop-shadow.png">
        </form>


        <div class="clear-both"></div>
        <table id="table-agents">
            <tbody>
                <tr>
                    <td class="border-right">
                        <div class="photo-frame">
                            <img src="/front/images/grey-background.jpg"/>
                        </div>
                        <div class="align-left contact-photos">
                            <img src="/front/images/email-icon.png">
                            <h3 class="h3-cms oswald oswald-pink">Madeline Milne</h3>
                            <h3 class="h3-cms font-18 oswald oswald-grey">CHEF & CHIEF EDITOR</h3>
                            <h3 class="font-14 oswald oswald-pink">Phone</h3>
                            <p>604.757.3835</p>
                        </div>
                    </td>
                    <td class="border-right">
                        <div class="photo-frame">
                            <img src="/front/images/grey-background.jpg"/>
                        </div>
                        <div class="align-left contact-photos">
                            <img src="/front/images/email-icon.png">
                            <h3 class="h3-cms oswald oswald-pink">Madeline Milne</h3>
                            <h3 class="h3-cms font-18 oswald oswald-grey">CHEF & CHIEF EDITOR</h3>
                            <h3 class="font-14 oswald oswald-pink">Phone</h3>
                            <p>604.757.3835</p>
                        </div>
                    </td>
                    <td>
                        <div class="photo-frame">
                            <img src="/front/images/grey-background.jpg"/>
                        </div>
                        <div class="align-left contact-photos">
                            <img src="/front/images/email-icon.png">
                            <h3 class="h3-cms oswald oswald-pink">Madeline Milne</h3>
                            <h3 class="h3-cms font-18 oswald oswald-grey">CHEF & CHIEF EDITOR</h3>
                            <h3 class="font-14 oswald oswald-pink">Phone</h3>
                            <p>604.757.3835</p>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td class="border-right">
                        <div class="border-top"></div>
                        <div class="separator-20"></div>
                        <div class="photo-frame">
                            <img src="/front/images/grey-background.jpg"/>
                        </div>
                        <div class="align-left contact-photos">
                            <img src="/front/images/email-icon.png">
                            <h3 class="h3-cms oswald oswald-pink">Madeline Milne</h3>
                            <h3 class="h3-cms font-18 oswald oswald-grey">CHEF & CHIEF EDITOR</h3>
                            <h3 class="font-14 oswald oswald-pink">Phone</h3>
                            <p>604.757.3835</p>
                        </div>
                        <div class="border-bottom"></div>
                    </td>
                    <td class="border-right">
                        <div class="border-top"></div>
                        <div class="separator-20"></div>
                        <div class="photo-frame">
                            <img src="/front/images/grey-background.jpg"/>
                        </div>
                        <div class="align-left contact-photos">
                            <img src="/front/images/email-icon.png">
                            <h3 class="h3-cms oswald oswald-pink">Madeline Milne</h3>
                            <h3 class="h3-cms font-18 oswald oswald-grey">CHEF & CHIEF EDITOR</h3>
                            <h3 class="font-14 oswald oswald-pink">Phone</h3>
                            <p>604.757.3835</p>
                        </div>
                        <div class="border-bottom"></div>
                    </td>
                    <td>
                        <div class="border-top"></div>
                        <div class="separator-20"></div>
                        <div class="photo-frame">
                            <img src="/front/images/grey-background.jpg"/>
                        </div>
                        <div class="align-left contact-photos">
                            <img src="/front/images/email-icon.png">
                            <h3 class="h3-cms oswald oswald-pink">Madeline Milne</h3>
                            <h3 class="h3-cms font-18 oswald oswald-grey">CHEF & CHIEF EDITOR</h3>
                            <h3 class="font-14 oswald oswald-pink">Phone</h3>
                            <p>604.757.3835</p>
                        </div>
                        <div class="border-bottom"></div>
                    </td>
                </tr>
            </tbody>
        </table>
    </section>
    <div class="news-box col col_5">
        <? echo $this->MenuLateral('busqueda-lateral'); ?>
    </div>
</div>