<div class="page-wrap clear-both">
    <section id="search-slider" class="page-wrap">

        <div id="slider-principal">  <!--  Meter el slider -->
            <div>
                <div class="box_skitter box_skitter_large">
                    <ul>
                        <li>
                            <a href="#cube"><img src="/front/images/slide1.jpg" class="cube" /></a>
                            <div class="label_text">
                                <p id="dialogo1">We Connect you<br>
                                    With the Mexico<br> 
                                    <span>Real Estate information</span></p>
                            </div>
                        </li>
                        <li><a href="#cubeRandom"><img src="/front/images/slide2.jpg" class="cubeRandom" /></a><div class="label_text ">
                                <p id="dialogo2">
                                    Your total guide to<br> Mexico<br>

                                    <span> SMART. SIMPLE. INFORMATIVE</span></p>
                            </div></li>
                        <li>
                            <a href="#block"><img src="/front/images/slide3.jpg" class="block" /></a>
                            <div class="label_text">
                                <p id="dialogo3">
                                    Live your dream online<br> and make it real<br>
                                    <span> visit Mexi-go</span>
                                </p>
                            </div>
                        </li>
                        <li>
                            <a href="#block"><img src="/front/images/slide4.jpg" class="block" /></a>
                            <div class="label_text">
                                <p id="dialogo4">
                                    BUY  / RENT / SELL <br> <span>visit Mexi-go</span></p>

                            </div>
                        </li>

                    </ul>
                </div>
            </div>

        </div>

        <? echo $this->MenuLateral('busqueda-slider'); ?>


    </section>

    <div class="colleft homecoll">                                    <!-- COLUMNA LEFT---------------------- -->

        <!-- div class="linea-punteada"></div -->

        <div class="seccion partnerslist dash-top-black"> <!--  Partners -->

            <div><h2 class="font-j1 owsald ">Partners</h2><a href="" >>> View all</a></div>


            <div class="wrap-partnerslist-style">
                <a href="" >
                    <img src="" width="" height="" title="" alt="" />
                </a>
            </div>
            <div class="wrap-partnerslist-style">
                <a href="" >
                    <img src="" width="" height="" title="" alt="" />
                </a>
            </div>
            <div class="wrap-partnerslist-style">
                <a href="" >
                    <img src="" width="" height="" title="" alt="" />
                </a>
            </div>
            <div class="wrap-partnerslist-style">
                <a href="" >
                    <img src="" width="" height="" title="" alt="" />
                </a>
            </div>
            <div class="wrap-partnerslist-style">
                <a href="" >
                    <img src="" width="" height="" title="" alt="" />
                </a>
            </div>
        </div>


        <!--</div>-->

        <div class="seccion featured-listing dash-top-black"> <!-- Featured listings :::::::::::::::::::::: Revisar si se deja como DIV o Section -->
            <div><h2 class="font-j1 owsald ">Featured listings</h2><a href="" >>> View all</a></div>


            <div id="show-agent-listings-div" class="">
                <div class="property-box no-padd-left">
                    <div class="property-image-frame">
                        <img title="" alt="" src="/front/images/property1.jpg">
                    </div>
                    <div class="alto-frmt">
                        <h3 class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa</p>
                    </div>
                    <ul class="iconos-uls">
                        <li> <span class="icon-add-this"></span></li>    
                        <li> <span class="icon-letter"></span></li>
                        <li> <span class="icon-heart"></span></li>
                        <li><span class="icon-pfd"></span></li>
                    </ul>
                    <p><a class="view-details-property" href="">View Details >></a></p>                                
                </div>
                <div class="property-box">
                    <div class="property-image-frame">
                        <img title="" alt="" src="/front/images/property1.jpg">
                    </div>
                    <div class="alto-frmt">
                        <h3 class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa  </p>
                        <p class="letter-pink"> USD $ 1,350,00 </p>

                    </div>
                    <ul class="iconos-uls">
                        <li> <span class="icon-add-this"></span></li>    
                        <li> <span class="icon-letter"></span></li>
                        <li> <span class="icon-heart"></span></li>
                        <li><span class="icon-pfd"></span></li>
                    </ul>
                    <p><a class="view-details-property" href="">View Details >></a></p>
                </div>
                <div class="property-box no-padd-right">
                    <div class="property-image-frame">
                        <img title="" alt="" src="/front/images/property1.jpg">
                    </div>
                    <div class="alto-frmt">
                        <h3 class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa</p>
                    </div>
                    <ul class="iconos-uls">
                        <li> <span class="icon-add-this"></span></li>    
                        <li> <span class="icon-letter"></span></li>
                        <li> <span class="icon-heart"></span></li>
                        <li><span class="icon-pfd"></span></li>
                    </ul>
                    <p><a class="view-details-property " href="">View Details >></a></p>
                </div>

            </div>



        </div>

        <div class="seccion recent-blog dash-top-black">

            <div><h2 class="font-j1 owsald txtnegro">Featured listings</h2><a href="" >>> View all</a></div>


            <article class="blog-ntry">
                <div class="blog-thumb-frame">
                    <img title="" alt="" src="/front/images/blog-thumb/blog-thumb-demo.jpg">
                </div>

                <header>
                    <h1>Hojalata tradicional art in mexico!</h1>
                </header>

                <p>
                    Stunning El nivel de compromiso, colaboración y ayuda que existe en el equipo para promiso, colaboración y ayuda que existe en el equipo para 
                </p>                    

                <footer>                        
                    <a href="">read more</a>
                </footer>
            </article>
            <article class="blog-ntry">
                <div class="blog-thumb-frame">
                    <img title="" alt="" src="/front/images/blog-thumb/blog-thumb-demo.jpg">
                </div>

                <header>
                    <h1>Hojalata tradicional art in mexico!</h1>
                </header>

                <p>
                    Stunning El nivel de compromiso, colaboración y ayuda que existe en el equipo para promiso, colaboración y ayuda que existe en el equipo para 
                </p>                    

                <footer>                        
                    <a href="">read more</a>
                </footer>
            </article>
            <article class="blog-ntry">
                <div class="blog-thumb-frame">
                    <img title="" alt="" src="/front/images/blog-thumb/blog-thumb-demo.jpg">
                </div>

                <header>
                    <h1>Hojalata tradicional art in mexico!</h1>
                </header>

                <p>
                    Stunning El nivel de compromiso, colaboración y ayuda que existe en el equipo para promiso, colaboración y ayuda que existe en el equipo para 
                </p>                    

                <footer>                        
                    <a href="">read more</a>
                </footer>
            </article>


        </div>


    </div>                                      <!-- /COLUMNA LEFT---------------------- -->


    <div class="colright homecoll">           <!-- COLUMNA RIGHT---------------------- -->

        <?php echo $this->MenuLateral('lateral-subscribe-newsletter'); ?>
        <div class="dashed"></div>
        <?php echo $this->MenuLateral('lateral-magazine'); ?>
        <div class="dashed"></div>



    </div>
</div>
