<div id="central-content">
    <section id="left-content" class="contact-agent">
        <div>
            <h3 class="h3-cms oswald no-margin">Magazine</h3>
            <div id="box-magazine-subscribe-form">
                <hr class="hr-gris-style2">
                <p class="black-bar font-18 text-white oswald">SUBSCRIBE / ENTER YOUR INFORMATION BELOW:</p>
                <div class="separator-10"></div>

                <form class="form-account-setting" id="form-contact-page">
                    <div class="separator-20"></div>
                    <img src="/front/images/magazine-front.jpg">
                    <div class="separator-20"></div>
                    <p>MAGAZINE DELIVERED TO YOUR DOOR</p>
                    <a class="boton-gris-basico button-light-shadow oswald" href="/magazine-subscribe.html">SUBSCRIBE!!</a>
                    <div class="separator-20"></div>
                    <p class="yellow-bar font-23 oswald">MEXI-GO! MAGAZINE</p>
                    <p>Is a 64 page glossy magazine distributed in Canada and in select regions in Mexico. Editorial focus is on retirement, lifestyle and culture in Mexico. We encourage travel, investment and eventual retirement to Mexico through our magazine, website, tradeshow and traveling road show. To learn more about Mexi-Go! contact magazine@mexi-go.ca.</p>
                    <div class="separator-20"></div>
                    <img class="contact-form-drop-shadow" src="/front/images/contact-form-drop-shadow.png">
                </form>
            </div>

            <div class="clear-both"></div>
            <table id="table-magazine">
                <tbody>
                    <tr>
                        <td>
                            <img src="/front/images/magazine-front-little.jpg">
                        </td>
                        <td>
                            <img src="/front/images/magazine-front-little.jpg">
                        </td>
                        <td>
                            <img src="/front/images/magazine-front-little.jpg">
                        </td>
                        <td>
                            <img src="/front/images/magazine-front-little.jpg">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="/front/images/magazine-front-little.jpg">
                        </td>
                        <td>
                            <img src="/front/images/magazine-front-little.jpg">
                        </td>
                        <td>
                            <img src="/front/images/magazine-front-little.jpg">
                        </td>
                        <td>
                            <img src="/front/images/magazine-front-little.jpg">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="/front/images/magazine-front-little.jpg">
                        </td>
                        <td>
                            <img src="/front/images/magazine-front-little.jpg">
                        </td>
                        <td>
                            <img src="/front/images/magazine-front-little.jpg">
                        </td>
                        <td>
                            <img src="/front/images/magazine-front-little.jpg">
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="separator-20"></div>
    </section>
    <div class="news-box col col_5">
        <? echo $this->MenuLateral('busqueda-lateral');?>
    </div>
</div>