<div class="page-wrap clear-both">
    <div class="columnaleft">     <!-- COLUMNA LEFT---------------------- -->
        <div class="general_content">
            <div class="living_header">
                <h2 class="oswald violet">Parteners</h2>
                <div class="search-field-d oswald">
                    <span>
                        <form><input type="text" value="   Search"><input type="submit"></form>
                    </span>
                </div>                                      
            </div>
            <div class="filter_opt">
                <div class="living_content_title">
                    <h2 class="oswald violet">Filters</h2>
                </div>
                <div class="input_middle" style="margin-left:20px">
                    <select name="d" class="mydds">
                        <option value="0" selected="selected_drop">Alphabetical</option>
                        <option value="1">Alphabetical one</option>
                        <option value="2">Alphabetical two</option>
                    </select>                   
                </div>
                <div class="input_middle">
                    <select name="d" class="mydds">
                        <option value="0" selected="selected_drop">Alphabetical</option>
                        <option value="1">Alphabetical one</option>
                        <option value="2">Alphabetical two</option>
                    </select>                   
                </div>

            </div>
            <!--    CATEGORIES START --> 					
            <div class="filter_opt">
                <div class="living_content_title">
                    <h2 class="oswald violet_cat2">CATEGORIES</h2>
                </div>
                <div class="input_middle" style="margin-left:0px !important">
                    <select name="d" class="mydds">
                        <option value="0" selected="selected_drop">Alphabetical</option>
                        <option value="1">Alphabetical one</option>
                        <option value="2">Alphabetical two</option>
                    </select>                   
                </div>
                <div class="input_middle">
                    <select name="d" class="mydds">
                        <option value="0" selected="selected_drop">Alphabetical</option>
                        <option value="1">Alphabetical one</option>
                        <option value="2">Alphabetical two</option>
                    </select>                   
                </div>

            </div>			
            <!--    CATEGORIES END--> 
            <div class="living_content">
                <div class="living_content_inner">

                    <div class="living_content_table">                         
                        <table width="600" id="newspaper-a" border="2">
                            <tbody class="violetr">
                                <tr class="odd">
                                    <td>Accounting</td>
                                    <td>30.5</td>
                                    <td>23.5</td>
                                </tr>
                                <tr class="even">
                                    <td>50.2</td>
                                    <td>40.63</td>
                                    <td>45.23</td>
                                </tr>
                                <tr class="odd">
                                    <td>20.3</td>
                                    <td>30.5</td>
                                    <td>23.5</td>
                                </tr>
                                <tr class="even">
                                    <td>50.2</td>
                                    <td>40.63</td>
                                    <td>45.23</td>
                                </tr> 
                                <tr class="odd">
                                    <td>20.3</td>
                                    <td>30.5</td>
                                    <td>23.5</td>
                                </tr>
                                <tr class="even">
                                    <td>50.2</td>
                                    <td>40.63</td>
                                    <td>45.23</td>
                                </tr> 
                                <tr class="odd">
                                    <td>20.3</td>
                                    <td>30.5</td>
                                    <td>23.5</td>
                                </tr>
                                <tr class="even">
                                    <td>50.2</td>
                                    <td>40.63</td>
                                    <td>45.23</td>
                                </tr> 
                                <tr class="odd">
                                    <td>20.3</td>
                                    <td>30.5</td>
                                    <td>23.5</td>
                                </tr>
                                <tr class="even">
                                    <td>50.2</td>
                                    <td>40.63</td>
                                    <td>45.23</td>
                                </tr>
                                <tr class="odd">
                                    <td>20.3</td>
                                    <td>30.5</td>
                                    <td>23.5</td>
                                </tr>
                                <tr class="even">
                                    <td>50.2</td>
                                    <td>40.63</td>
                                    <td>45.23</td>
                                </tr> 
                                <tr class="odd">
                                    <td>20.3</td>
                                    <td>30.5</td>
                                    <td>23.5</td>
                                </tr> 

                            </tbody>
                        </table>                        
                    </div>
                    <div class="reset_results"></div> 
                </div> 

            </div>

            <div class="living_footer violetbac">
                <div class="hide_option"></div>                 
            </div>

            <div class="result">
                <h2 class="oswald violet">Accounting</h2>
                <div class="result_content">
                    <ul>
                        <li></li>
                        <div class="line_result"></div>
                        <li></li>
                        <div class="line_result"></div>
                        <li></li>
                        <div class="line_result"></div>
                        <li></li>
                        <div class="line_result_width"></div>
                        <li></li>
                        <div class="line_result"></div>
                        <li></li>
                        <div class="line_result"></div>
                        <li></li>
                        <div class="line_result"></div>
                        <li></li>
                        <div class="line_result_width"></div>                          
                        <li></li>
                        <div class="line_result"></div>
                        <li></li>
                        <div class="line_result"></div>
                        <li></li>
                        <div class="line_result"></div>
                        <li></li>
                        <div class="line_result_width"></div>                          
                        <li></li>
                        <div class="line_result"></div>
                        <li></li>
                        <div class="line_result"></div>
                        <li></li>
                        <div class="line_result"></div>
                        <li></li>                                       
                    </ul>
                </div>
            </div>                
        </div>





    </div>                                      <!-- /COLUMNA LEFT---------------------- -->



    <div class="columnaright">           <!-- COLUMNA RIGHT---------------------- -->

        <?php echo $this->MenuLateral('busqueda-lateral'); ?>
        <?php echo $this->MenuLateral('lateral-entero'); ?>



    </div>
</div>