<div class="page-wrap clear-both">
    <div id="homes-detail-div" class="columnaleft">                                    <!-- COLUMNA LEFT---------------------- -->
        <p class="red-tittle-p oswald" >Dream Home Search</p>
        <p id="view-map-p"><span>Property search results<span><a href=""  class="oswald float-right">VIEW MAP</a></span></p>
        <div>
            <span><a id="back-to-result-a" class="oswald" href="">BACK TO RESULTS</a></span>
            <div class="paginador">
                <span class="previous"><a href=""><< previous</a></span>
                <span class="number"><a href="">1</a></span>
                <span class="number actual"><a href="">2</a></span>
                <span class="puntos"></span>
                <span class="number "><a href="">10</a></span>
                <span class="next"><a href="">next >></a></span>
            </div>
        </div>
        <div id="gall-wrap">
            <div class="clear-both oswald" id="featured-gall">FEATURED<div id="view-image-video" class="oswald"><span id="show-image-gal-btn" class="oswald hand">VIEW IMAGES</span> | <span id="show-video-gal-btn" class="oswald hand">VIEW VIDEO</span></div></div>
            <?php include 'layout/galeria-imagenes-homes.php'; ?> 
            <?php include 'layout/galeria-videos-homes.php'; ?> 
        </div>
        <section class="tipo-profile-agente-left">
            <h3 class="font-j1 font-jred oswald mar-bot-5">AGENT DETAILS</h3>
            <div id="foto-agent-id" class="foto-agent-1">
                <img src="/front/images/agent-photo.jpg"/>
            </div>
            <p class="oswald mar-top-bot-5">Brokerage</p>
            <p class="mar-top-bot-5"> <span class="font-j1 font-jred oswald">MICHELE MURPHY</span><br/>
                <span class="font-j2 font-jlightgrey oswald">MEXICO / BUCERIAS</span></p>
            <p class="mar-top-bot-5"><span class="font-jred">Mobile Phone:</span><br/><span class="">322-2323</span></p>
            <p class="mar-top-bot-5">Jhon is a certidied property specialist the settlement comp is mexicos oldest and little...</p>
            <div id="nav-agent-icons" class="mar-bot-20 mar-top-50">
                <nav>
                    <ul>
                        <li><a href=""><img src="/front/images/website-icon.png" /><div class="class-tooltip"><span  class="tooltip" >More properties from this agent.</span><span class="triangle" >&nbsp;</span></div></a></li>
                        <li class="hand cargoContactForm"><a href=""><img src="/front/images/email-icon.png" /><div class="class-tooltip"><span  class="tooltip" >More properties from this agent.</span><span class="triangle" >&nbsp;</span></div></a></li>
                        <li><a href=""><img src="/front/images/home-icon.png" /><div class="class-tooltip"><span  class="tooltip" >More properties from this agent.</span><span class="triangle" >&nbsp;</span></div></a></li>
                        <li><a href=""><img src="/front/images/profile-icon.png" /><div class="class-tooltip"><span  class="tooltip" >More properties from this agent.</span><span class="triangle" >&nbsp;</span></div></a></li>
                    </ul>
                </nav>
            </div>
        </section>

        <section class="tipo-profile-agente-right">
            <h3 class="font-j1 font-jred oswald">ABOUT THIS HOME</h3>
            <h4 class="font-j1 font-jred oswald">Opportunity Knocks!</h4>                    
            <p>Sayulita, Mexico</p>
            <p class="font-j2 font-jred bold">USD $1,300.000</p>
            <p class="mar-top-bot-20">We're ready to downsize.  Beautiful, custom home located 2 miles south of Sayulita near the secluded beaches of the Patzcuaro neighborhood.  This must-see TITLED property is successfully operated as a seasonal B&B Nov. through May.  Continue the dream as proprietor of your own inn while maintaining a privileged lifestyle year round.  It would also make a spectacular personal residence and/or vacation rental. All suites have private baths and separate entrance.
            </p>
            <h6 class="font-j1 font-jred oswald mar-top-bot-10">FEATURES</h6>
            <div>
                <table id="agent-feature-table"class="align-center">
                    <tr>
                        <td><span class="circle-gery-20">3</span></td>
                        <td><span class="circle-gery-20">1.5</span></td>
                        <td><span class="circle-gery-20">2</span></td>
                        <td><span class="circle-gery-20">1</span></td>
                    </tr>
                    <tr>
                        <td><img src="/front/images/bedrooms.png"/></td>
                        <td><img src="/front/images/bathrooms.png"/></td>
                        <td><img src="/front/images/pool.png"/></td>
                        <td><img src="/front/images/see-view.png"/></td>
                    </tr>
                </table>
            </div>
            <div>
                <ul class="iconos-uls">
                    <li> <span class="icon-add-this"></span></li>    
                    <li class="hand cargoContactForm"> <span class="icon-letter"></span></li>
                    <li> <span class="icon-heart"></span></li>
                    <li><span class="icon-pfd"></span></li>
                </ul>
            </div>
            <div class="doc-name"><span class="font-j1 font-jred oswald mar-top-bot-10">DOCUMENT NAME</span></div>

        </section>
        <section class="tipo-profile-agente-contact-right actualmente-hidden" >
            <form>
                <p class="fir-p oswald">Contact form<span class="hand ocultoContactForm float-right crus-close"></span><span class="hand ocultoContactForm oswald float-right mar-rig-5">CLOSE</span></p>
                <div id="wrap-grande-house-mail">
                    <p id="desc-home-mail" class="oswald font-jred">HOME DETAILS</p>
                    <div class="added-home-contacto">
                        <div class="added-thumb"><img src="/front/images/thumb-chico-casa.png"></div>
                        <div class="added-desc">
                            <p class="oswald-pink oswald">Opportunity Knocks!
                            </p><p>Stunning Sayulita Villa </p>
                            <p class="letter-pink"> USD $ 1,350,00 </p>
                        </div>
                        <div class="add-more-h"><a href="">Add more homes from this agent >></a></div>
                        <div class="remove-this"><a href="">Remove this home x</a></div>
                    </div>
                </div>
                <div id="form-ctct-chico">
                    <div><label for="">*Name:</label><input type="text" name="" id=""></div>
                    <div><label for="">*Your E-mail:</label><input type="text" name="" id=""></div>
                    <div><label for="">Phone number:</label><input type="text" name="" id=""></div>
                    <div><label for="">*Your Message:</label><textarea></textarea></div>   
                    <input type="submit" id="send-form" class="boton-css-gradient-grey boton-css-formato round-corner-5 oswald" value="SEND &gt;&gt;">

                </div>
            </form>
        </section>
        <div class="sombra-abajo-1 float-left">

        </div>
        <div id="show-agent-listings" class="trigger-sh float-left hand"><span class="font-j1 font-jred oswald mar-top-bot-5">AGENT LISTINGS</span><span class="font-jgrey float-right font-j2"><span class="flecha-all"><<</span> view all</span></div>
        <div id="show-agent-listings-div" class="show-agent-listings-hidden">
            <div id="show-agent-listings-hiddable" class="hided-now">
                <div class="property-box no-padd-left">
                    <div class="property-image-frame">
                        <img title="" alt="" src="/front/images/property1.jpg">
                    </div>
                    <div class="alto-frmt">
                        <h3 class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa</p>
                    </div>
                    <ul class="iconos-uls">
                        <li> <span class="icon-add-this"></span></li>    
                        <li> <span class="icon-letter"></span></li>
                        <li> <span class="icon-heart"></span></li>
                        <li><span class="icon-pfd"></span></li>
                    </ul>
                    <p><a class="view-details-property" href="">View Details >></a></p>
                </div>
                <div class="property-box">
                    <div class="property-image-frame">
                        <img title="" alt="" src="/front/images/property1.jpg">
                    </div>
                    <div class="alto-frmt">
                        <h3 class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa  </p>
                        <p class="letter-pink"> USD $ 1,350,00 </p>
                    </div>
                    <ul class="iconos-uls">
                        <li> <span class="icon-add-this"></span></li>    
                        <li> <span class="icon-letter"></span></li>
                        <li> <span class="icon-heart"></span></li>
                        <li><span class="icon-pfd"></span></li>
                    </ul>
                    <p><a class="view-details-property" href="">View Details >></a></p>
                </div>
                <div class="property-box no-padd-right">
                    <div class="property-image-frame">
                        <img title="" alt="" src="/front/images/property1.jpg">
                    </div>
                    <div class="alto-frmt">
                        <h3 class="oswald-pink">Opportunity Knocks!</h3>
                        <p>Stunning Sayulita Villa</p>
                    </div>
                    <ul class="iconos-uls">
                        <li> <span class="icon-add-this"></span></li>    
                        <li> <span class="icon-letter"></span></li>
                        <li> <span class="icon-heart"></span></li>
                        <li><span class="icon-pfd"></span></li>
                    </ul>
                    <p><a class="view-details-property " href="">View Details >></a></p>
                </div>
            </div>
        </div>

        <div class="custom-dashed-line mar-top-bot-20"></div>
    </div>                                      <!-- /COLUMNA LEFT---------------------- -->


    <div class="columnaright">           <!-- COLUMNA RIGHT---------------------- -->
        <?php echo $this->MenuLateral('busqueda-lateral'); ?>
        <?php echo $this->MenuLateral('lateral-detalle-homes'); ?>    
        <div class="dashed"></div>
        <?php echo $this->MenuLateral('lateral-subscribe-newsletter'); ?>
        <div class="dashed"></div>
    </div>
</div>