
<script type="text/javascript">
    $(document).ready(function(){
			
		
			
			
			
    });
		
</script>

<div class="page-wrap clear-both">
    <div class="columnaleft">     <!-- COLUMNA LEFT---------------------- -->


        <div class="colleft map-seach-rs input-default-format omi-check"> 
            <div class="oswald pestana-buy-rent-grande"><h2>Dream Home Search</h2><span id="pestaña-adv-rent" class="switchBuyRentMap round-corner-top-8 oswald top-box-shad">RENT</span><span id="pestaña-adv-buy" class="switchBuyRentMap oswald round-corner-top-8 top-box-shad ">BUY</span></div>
            <div id="pestaña-adv-buy-map" >                  
                <div class="sec-div"><span class="oswald">Map Search</span><a href="/advance-search.html" class="boton-css-gradient-grey boton-css-formato round-corner-5 oswald">ADVANCED SEARCH >></a></div>
                <p class="map-text-desc">Search for Real Estate by dragging the map with your mouse.<br/>Use the search criteria below to your revise criteria results.</p>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="searchMapRegion" class="tamano-corto">Region</label>
                    <div class="flecha-combo"><select name="searchMapRegion" id="searchMapRegion" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="searchMapCity" class="tamano-medio">City</label>
                    <div class="flecha-combo"><select name="searchMapCity" id="searchMapCity" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="searchMapBedroom" class="tamano-corto">Bedroom</label>
                    <div class="flecha-combo"><select name="searchMapBedroom" id="searchMapBedroom" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="searchMapBathroom" class="tamano-medio">Bathrooms</label>
                    <div class="flecha-combo"><select name="searchMapBathroom" id="searchMapBathroom" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="searchMapView" class="tamano-corto">View</label>
                    <div class="flecha-combo"><select name="searchMapView" id="searchMapView" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="searchMapRAreas" class="tamano-medio">Recreational Areas</label>
                    <div class="flecha-combo"><select name="searchMapRAreas" id="searchMapRAreas" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <label class="tamano-corto">Price</label>
                <div  class="refine-search-div combo-fix float-left inline-block clear-none">
                    <label for="searchMapPrice" class="tamano-corto">$</label>
                    <div class="flecha-combo"><select name="searchMapPrice" id="searchMapPrice" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                    <div  class="flecha-combo-chico-1 mar-lef-10"><select class="select-chico-1" name="priceCoinBuyt" id="priceCoinBuy" type="text"><option>USD</option><option>AUS</option><option>EUR</option></select></div>
                    <a  class="boton-css-gradient-grey boton-css-formato round-corner-5 oswald" href="">REFINE YOUR SEARCH &gt;&gt;</a>
                </div>



            </div>
            <div id="pestaña-adv-rent-map" class="hided-now">
                <div class="sec-div"><span class="oswald">Map Search</span><a href="/advance-search.html" class="boton-css-gradient-grey boton-css-formato round-corner-5 oswald">ADVANCED SEARCH >></a></div>
                <p class="map-text-desc">Search for Real Estate by dragging the map with your mouse.<br/>Use the search criteria below to your revise criteria results.</p>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="rentMapRegion" class="tamano-corto">Region</label>
                    <div class="flecha-combo"><select name="rentMapRegion" id="rentMapRegion" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="rentMapCity" class="tamano-medio">City</label>
                    <div class="flecha-combo"><select name="rentMapCity" id="rentMapCity" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="rentMapBedroom" class="tamano-corto">Bedroom</label>
                    <div class="flecha-combo"><select name="rentMapBedroom" id="rentMapBedroom" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="rentMapBathroom" class="tamano-medio">Bathrooms</label>
                    <div class="flecha-combo"><select name="rentMapBathroom" id="rentMapBathroom" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="rentMapView" class="tamano-corto">View</label>
                    <div class="flecha-combo"><select name="rentMapView" id="rentMapView" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <div class="combo-fix float-left inline-block clear-none">
                    <label for="rentMapRAreas" class="tamano-medio">Recreational Areas</label>
                    <div class="flecha-combo"><select name="rentMapRAreas" id="rentMapRAreas" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                </div>
                <label class="tamano-corto">Price</label>
                <div  class="refine-search-div combo-fix float-left inline-block clear-none">
                    <label for="rentMapPrice" class="tamano-corto">$</label>
                    <div class="flecha-combo"><select name="rentMapPrice" id="rentMapPrice" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                    <div  class="flecha-combo-chico-1 mar-lef-10"><select class="select-chico-1" name="priceCoinRent" id="priceCoinRent" type="text"><option>USD</option><option>AUS</option><option>EUR</option></select></div>

                </div>
                <div class="float-left mar-top-bot-10">
                    <label for="checkDailyRent" id="label-checkDailyRent" class="check-special-dark-black">Rent Daily</label><input id="checkDailyRent" name="checkDailyRent" type="checkbox" />
                    <label for="checkMonthlyRent" id="label-checkMonthlyRent" class="check-special-dark-black">Rent Monthly</label><input id="checkMonthlyRent" name="checkMonthlyRent" type="checkbox" />
                    <label for="checkAnnualyRent" id="label-checkAnnualyRent" class=" check-special-dark-black">Rent Annualy</label><input id="checkAnnualyRent" name="checkAnnualyRent" type="checkbox" />
                </div>
                <div class="float-left mar-top-bot-10">
                    <div class="combo-fix float-left inline-block clear-none">
                        <label for="checkIn" class="tamano-maso">Travel dates</label>
                        <div class="flecha-combo-inter"><select name="checkIn" id="checkIn" type="text"><option>Check in</option><option>Yes</option><option>No</option></select></div>
                    </div>
                    <div class="combo-fix float-left inline-block clear-none mar-lef-10">
                        <div class="flecha-combo-inter"><select name="checkOut" id="checkOut" type="text"><option>Check out</option><option>Yes</option><option>No</option></select></div>
                    </div>
                    <div class="combo-fix float-left inline-block clear-none mar-lef-20">
                        <label style="width:105px !important" for="numberBedsRent">Number of Beds</label>
                        <div class="flecha-combo-chico-1"><select class="select-chico-1" name="numberBedsRent" id="numberBedsRent" type="text"><option>4</option><option>2</option><option>3</option></select></div>
                    </div>
                </div>
                <a  class="float-right mar-rig-20 boton-css-gradient-grey boton-css-formato round-corner-5 oswald" href="">REFINE YOUR SEARCH &gt;&gt;</a>


            </div>               


            <div class="featured_container">
                <div id="linea-u">
                    <span class="red-number-props">10</span> Properties found
                    <a  class="float-right boton-css-gradient-grey boton-css-formato round-corner-5 oswald" href="">SAVE THIS SEARCH &gt;&gt;</a>
                </div>
                <div class="destinations_items_map">
                    <div class="middle_travel_map"> 
                        <div class="map_result"></div>                               
                    </div>
                    <div class="bottom_travel_map">
                    </div>
                </div>
            </div>   

            <div class="living_content_table">                         
                <table width="600" id="newspaper-map" border="2">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">ADDRESS</th>
                            <th scope="col">CITY</th>
                            <th scope="col">PRICE</th>
                            <th scope="col"> </th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="odd">
                            <td class="id">SE45</td>
                            <td>Sayulita, Mexico   </td>
                            <td>GUADALAJARA</td>
                            <td class="price">USD $ 1,350,00</td>
                            <td class="share">
                                <div class="details_list_items">
                                    <div class="heart-icon"></div>
                                    <div class="email-icon left_icon "></div>                                    
                                    <div class="add-icon"></div>                                               
                                </div> 
                            </td>
                            <td class="cross">
                                <div class="details_list_cross">
                                    <div class="cross-icon"></div> 
                                </div>                             			
                            </td>
                        </tr>
                        <tr class="even">
                            <td class="id">SE45</td>
                            <td>Sayulita, Mexico   </td>
                            <td>GUADALAJARA</td>
                            <td class="price">USD $ 1,350,00</td>
                            <td class="share">
                                <div class="details_list_items">
                                    <div class="heart-icon"></div>
                                    <div class="email-icon left_icon "></div>                                    
                                    <div class="add-icon"></div>                                               
                                </div> 
                            </td>
                            <td class="cross">
                                <div class="details_list_cross">
                                    <div class="cross-icon"></div> 
                                </div>                             			
                            </td>
                        </tr>
                        <tr class="odd">
                            <td class="id">SE45</td>
                            <td>Sayulita, Mexico   </td>
                            <td>GUADALAJARA</td>
                            <td class="price">USD $ 1,350,00</td>
                            <td class="share">
                                <div class="details_list_items">
                                    <div class="heart-icon"></div>
                                    <div class="email-icon left_icon "></div>                                    
                                    <div class="add-icon"></div>                                               
                                </div> 
                            </td>
                            <td class="cross">
                                <div class="details_list_cross">
                                    <div class="cross-icon"></div> 
                                </div>                             			
                            </td>
                        </tr>
                        <tr class="even">
                            <td class="id">SE45</td>
                            <td>Sayulita, Mexico   </td>
                            <td>GUADALAJARA</td>
                            <td class="price">USD $ 1,350,00</td>
                            <td class="share">
                                <div class="details_list_items">
                                    <div class="heart-icon"></div>
                                    <div class="email-icon left_icon "></div>                                    
                                    <div class="add-icon"></div>                                               
                                </div> 
                            </td>
                            <td class="cross">
                                <div class="details_list_cross">
                                    <div class="cross-icon"></div> 
                                </div>                             			
                            </td>
                        </tr>
                        <tr class="odd">
                            <td class="id">SE45</td>
                            <td>Sayulita, Mexico   </td>
                            <td>GUADALAJARA</td>
                            <td class="price">USD $ 1,350,00</td>
                            <td class="share">
                                <div class="details_list_items">
                                    <div class="heart-icon"></div>
                                    <div class="email-icon left_icon "></div>                                    
                                    <div class="add-icon"></div>                                               
                                </div> 
                            </td>
                            <td class="cross">
                                <div class="details_list_cross">
                                    <div class="cross-icon"></div> 
                                </div>                             			
                            </td>
                        </tr>
                        <tr class="even">
                            <td class="id">SE45</td>
                            <td>Sayulita, Mexico   </td>
                            <td>GUADALAJARA</td>
                            <td class="price">USD $ 1,350,00</td>
                            <td class="share">
                                <div class="details_list_items">
                                    <div class="heart-icon"></div>
                                    <div class="email-icon left_icon "></div>                                    
                                    <div class="add-icon"></div>                                               
                                </div> 
                            </td>
                            <td class="cross">
                                <div class="details_list_cross">
                                    <div class="cross-icon"></div> 
                                </div>                             			
                            </td>
                        </tr>
                        <tr class="odd">
                            <td class="id">SE45</td>
                            <td>Sayulita, Mexico   </td>
                            <td>GUADALAJARA</td>
                            <td class="price">USD $ 1,350,00</td>
                            <td class="share">
                                <div class="details_list_items">
                                    <div class="heart-icon"></div>
                                    <div class="email-icon left_icon "></div>                                    
                                    <div class="add-icon"></div>                                               
                                </div> 
                            </td>
                            <td class="cross">
                                <div class="details_list_cross">
                                    <div class="cross-icon"></div> 
                                </div>                             			
                            </td>
                        </tr>
                        <tr class="even">
                            <td class="id">SE45</td>
                            <td>Sayulita, Mexico   </td>
                            <td>GUADALAJARA</td>
                            <td class="price">USD $ 1,350,00</td>
                            <td class="share">
                                <div class="details_list_items">
                                    <div class="heart-icon"></div>
                                    <div class="email-icon left_icon "></div>                                    
                                    <div class="add-icon"></div>                                               
                                </div> 
                            </td>
                            <td class="cross">
                                <div class="details_list_cross">
                                    <div class="cross-icon"></div> 
                                </div>                             			
                            </td>
                        </tr>
                        <tr class="odd">
                            <td class="id">SE45</td>
                            <td>Sayulita, Mexico   </td>
                            <td>GUADALAJARA</td>
                            <td class="price">USD $ 1,350,00</td>
                            <td class="share">
                                <div class="details_list_items">
                                    <div class="heart-icon"></div>
                                    <div class="email-icon left_icon "></div>                                    
                                    <div class="add-icon"></div>                                               
                                </div> 
                            </td>
                            <td class="cross">
                                <div class="details_list_cross">
                                    <div class="cross-icon"></div> 
                                </div>                             			
                            </td>
                        </tr>
                        <tr class="even">
                            <td class="id">SE45</td>
                            <td>Sayulita, Mexico   </td>
                            <td>GUADALAJARA</td>
                            <td class="price">USD $ 1,350,00</td>
                            <td class="share">
                                <div class="details_list_items">
                                    <div class="heart-icon"></div>
                                    <div class="email-icon left_icon "></div>                                    
                                    <div class="add-icon"></div>                                               
                                </div> 
                            </td>
                            <td class="cross">
                                <div class="details_list_cross">
                                    <div class="cross-icon"></div> 
                                </div>                             			
                            </td>
                        </tr>
                        <tr class="odd">
                            <td class="id">SE45</td>
                            <td>Sayulita, Mexico   </td>
                            <td>GUADALAJARA</td>
                            <td class="price">USD $ 1,350,00</td>
                            <td class="share">
                                <div class="details_list_items">
                                    <div class="heart-icon"></div>
                                    <div class="email-icon left_icon "></div>                                    
                                    <div class="add-icon"></div>                                               
                                </div> 
                            </td>
                            <td class="cross">
                                <div class="details_list_cross">
                                    <div class="cross-icon"></div> 
                                </div>                             			
                            </td>
                        </tr>
                        <tr class="even">
                            <td class="id">SE45</td>
                            <td>Sayulita, Mexico   </td>
                            <td>GUADALAJARA</td>
                            <td class="price">USD $ 1,350,00</td>
                            <td class="share">
                                <div class="details_list_items">
                                    <div class="heart-icon"></div>
                                    <div class="email-icon left_icon "></div>                                    
                                    <div class="add-icon"></div>                                               
                                </div> 
                            </td>
                            <td class="cross">
                                <div class="details_list_cross">
                                    <div class="cross-icon"></div> 
                                </div>                             			
                            </td>
                        </tr>                                                            
                    </tbody>
                </table>                        
            </div>
            <a id="view-all-selection" class="boton-css-gradient-grey boton-css-formato round-corner-5 oswald" href="">VIEW ALL SELECTION &gt;&gt;</a>

            <div class="seccion featured-listing dash-top-black float-left"> <!-- Featured listings :::::::::::::::::::::: Revisar si se deja como DIV o Section -->
                <div><h2 class="font-j1 owsald ">Featured listings</h2><a href="">&gt;&gt; View all</a></div>


                <div class="" id="show-agent-listings-div">
                    <div class="property-box no-padd-left">
                        <div class="property-image-frame">
                            <img src="/front/images/property1.jpg" alt="" title="">
                        </div>
                        <div class="alto-frmt">
                            <h3 class="oswald-pink">Opportunity Knocks!</h3>
                            <p>Stunning Sayulita Villa</p>
                        </div>
                        <ul class="iconos-uls">
                            <li> <span class="icon-add-this"></span></li>    
                            <li> <span class="icon-letter"></span></li>
                            <li> <span class="icon-heart"></span></li>
                            <li><span class="icon-pfd"></span></li>
                        </ul>
                        <p><a href="" class="view-details-property">View Details &gt;&gt;</a></p>                                
                    </div>
                    <div class="property-box">
                        <div class="property-image-frame">
                            <img src="/front/images/property1.jpg" alt="" title="">
                        </div>
                        <div class="alto-frmt">
                            <h3 class="oswald-pink">Opportunity Knocks!</h3>
                            <p>Stunning Sayulita Villa  </p>
                            <p class="letter-pink"> USD $ 1,350,00 </p>

                        </div>
                        <ul class="iconos-uls">
                            <li> <span class="icon-add-this"></span></li>    
                            <li> <span class="icon-letter"></span></li>
                            <li> <span class="icon-heart"></span></li>
                            <li><span class="icon-pfd"></span></li>
                        </ul>
                        <p><a href="" class="view-details-property">View Details &gt;&gt;</a></p>
                    </div>
                    <div class="property-box no-padd-right">
                        <div class="property-image-frame">
                            <img src="/front/images/property1.jpg" alt="" title="">
                        </div>
                        <div class="alto-frmt">
                            <h3 class="oswald-pink">Opportunity Knocks!</h3>
                            <p>Stunning Sayulita Villa</p>
                        </div>
                        <ul class="iconos-uls">
                            <li> <span class="icon-add-this"></span></li>    
                            <li> <span class="icon-letter"></span></li>
                            <li> <span class="icon-heart"></span></li>
                            <li><span class="icon-pfd"></span></li>
                        </ul>
                        <p><a href="" class="view-details-property ">View Details &gt;&gt;</a></p>
                    </div>

                </div>



            </div>





        </div>                                      <!-- /COLUMNA LEFT---------------------- -->



        <div class="columnaright">           <!-- COLUMNA RIGHT---------------------- -->

            



        </div>
    </div>