<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>        
        <?php echo $this->headLink() ?>
        <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald">
        <link rel="stylesheet" type="text/css" href="<?php echo CST_Server_ServerStatic::getUrl(); ?>/back-css/header.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo CST_Server_ServerStatic::getUrl(); ?>/back-css/footer.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo CST_Server_ServerStatic::getUrl(); ?>/back-css/general.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo CST_Server_ServerStatic::getUrl(); ?>/back-css/estilos.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/js/general.js"></script>
    </head>
    <body>
        <div id="header-shadow-left" class="header-shadow" ></div>
        <div id="header-shadow-center" class="header-shadow" ></div>
        <div id="header-shadow-right" class="header-shadow" ></div>
        <div id="wrapper-back">
             <style>
                 .active a{
                     background: #FFCD00 !important  ; 
                 }
                 
             </style>
            <header>
                <div id="header-up">
                    <div id="header-up-left" ><img src="<?php echo CST_Server_ServerStatic::getUrl(); ?>/images/logo-back.png"/></div>
                    <div id="header-up-right" >
                        <p id="welcome-mexigo" >WELCOME TO MEXI-GO!</p>
                        <?php if(!empty($this->identityPartner)){ ?>
                        <p id="contact-short" class="oswald">
                            <span id="hi-contact">
                                <a href="">
                                    CONTACT
                                </a>
                            </span>
                            <span id="hi-nombre">
                                <?php echo $this->identityPartner->usu_nombre; ?>
                            </span>
                        </p>
                        <?php } ?>

                    </div>
                </div>
                <div id="header-down">
                    <nav>
                        <ul>
                            <li ><a href="">Marketing services</a></li>
                            <li><a href="">The magazine</a></li>
                            <li class="actual-li"><a href="sign-up-now.php">Sign up now!</a></li>
                            <li><a href="">Mexi-Go! News</a></li>
                        </ul>
                    </nav>

                    <nav id="social-links" >
                        <ul>
                            <li><a href="" class="social-icons facebook-icon">follow us facebook</a></li>
                            <li><a href="" class="social-icons twitter-icon" >follow us twitter</a></li>
                            <li><a href="" class="social-icons linked-in-icon" >follow us linked in</a></li>
                            <li><a href="" class="social-icons tumblr-icon" >follow us tumblr</a></li>
                            <li><a href="" class="social-icons pinterest-icon" >follow us pinterest</a></li>
                        </ul>
                    </nav>
                </div>
            </header>
            <div class="page-wrap">
                <?php echo $this->layout()->content ?>            
            </div>
            <footer>
                <nav class="nav-left">
                    <ul >
                        <li><a href=""><span class="bold">MARKETING SERVICES</span></a> <a href="">MEXI - GO!</a> / <a href="">ADVERTISE IN CANADA!</a> / <a href="">OUR READERS!</a> / <a href="">MEXI - GO.CA</a></li>
                        <li><a href=""><span class="bold">THE MAGAZINE</span></a> <a href="">PAPER MAGAZINE</a> / <a href="">ONLINE MAGAZINE</a></li>
                        <li><a href="sign-up-now.php"><span class="bold">SIGN UP NOW!</span></a></li>
                        <li><a href=""><span class="bold">MEXI-GO! NEWS</span></a></li>
                        <li><a href=""><span class="bold">CONTACT</span></a></li>
                    </ul>
                </nav>                
                <nav id="footer-social-links" class="nav-right">
                    <ul >
                        <li><span>SOCIAL MEDIA:</span> </li>
                        <li><a href="" class="social-icons facebook-icon">follow us facebook</a></li>
                        <li><a href="" class="social-icons twitter-icon" >follow us twitter</a></li>
                        <li><a href="" class="social-icons linked-in-icon" >follow us linked in</a></li>
                        <li><a href="" class="social-icons tumblr-icon" >follow us tumblr</a></li>
                        <li><a href="" class="social-icons pinterest-icon" >follow us pinterest</a></li>
                    </ul>
                </nav>
                <p class="copyright">&copy;2012 Mexi-Go.ca - Connecting Mexico to Canadians</p>
            </footer>
        </div>    
    </body>
</html>