<!DOCTYPE html>
<html>
    <head>
        <link id="page_favicon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA/klEQVQ4je2RsU7DMBRFMzFmyEbsIU5MnyATv4DEwB+gTnwB38MPgBSPlJmRCbEgYsEQ2+3YGCgbSy+DmyqRKLAwIHGlJz1ZV0f3XUfRv35PpBy6vW4EvvJuBFBloY2ANj8EtEyujVRZLMYlPJPQvQQtLzbDPJdoeYAsxmUA9N48y5eeyyHAJ0k8i3kyi3nSjPZhVtMHeC4x382X870Cz2WGzv8QRVshVhrI9TTDqHIg5XB9eozXcMLb403o4clypBMfoCw/GyZhUtfTDNoIbJ+/3JGy66jaCFzeH92SckgnHi0rTj7tQDfiqmucqgHgnZQ9IOWwc9EcfvMXf00fb8CbTqdooMMAAAAASUVORK5CYII=" rel="icon" type="image/x-icon">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>        
        <?php echo $this->headLink() ?>
        <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald">
        <link rel="stylesheet" type="text/css" href="/front/css/header.css" />
        <link rel="stylesheet" type="text/css" href="/front/css/footer.css" />
        <link rel="stylesheet" type="text/css" href="/front/css/general.css" />
        <link rel="stylesheet" type="text/css" href="/front/css/estilos.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="/front/js/general.js"></script>
        <script src="/front/js/photo-frame.js" type="text/javascript"></script>
        <script src="/front/js/front.js" type="text/javascript"></script>
    </head>
    <body>
        <div id="header-shadow-left" class="header-shadow" ></div>
        <div id="header-shadow-center" class="header-shadow" ></div>
        <div id="header-shadow-right" class="header-shadow" ></div>
        <div id="wrapper-back">
            <header>
                <div id="header-up">
                    <div id="header-up-left" ><a href="/"><img src="/front/images/logo-back.png"/></a></div>
                    <div id="header-up-right" >
                        <p id="welcome-mexigo" >WELCOME TO MEXI-GO!</p>
                        <p id="contact-short" class="oswald"><span id="hi-contact"><a href="">CONTACT</a></span><span id="hi-nombre">HI STEVE</span></p>

                    </div>
                </div>
                <div id="header-down" class="menu-nav-back">
                    <nav>
                        <ul>
                            <li class="menu-pri <?php echo ($_SERVER['REQUEST_URI'] == '/marketing-services.html')? 'actual-li':''?>" id="marketing_services" ><a href="/marketing-services.html">Marketing services</a></li>
                            <li class="menu-pri <?php echo ($_SERVER['REQUEST_URI'] == '/magazine.html')? 'actual-li':''?>" id="magazine"><a href="/magazine.html">The magazine</a></li>
                            <li class="menu-pri <?php echo ($_SERVER['REQUEST_URI'] == '/sign-up-now.html')? 'actual-li':''?>" id="sign_up"><a href="/sign-up-now.html">Sign up now!</a></li>
                            <li class="menu-pri <?php echo ($_SERVER['REQUEST_URI'] == '/news.html')? 'actual-li':''?>" id="news"><a href="/news.html">Mexi-Go! News</a></li>
                        </ul>
                    </nav>
                    <nav id="social-links" >
                        <ul>
                            <li><a href="https://www.facebook.com/MexiGoProperties" class="social-icons facebook-icon">follow us facebook</a></li>
                            <li><a href="https://twitter.com/MexigoProperty" class="social-icons twitter-icon" >follow us twitter</a></li>
                            <li><a href="http://www.linkedin.com/company/2285345?trk=tyah" class="social-icons linked-in-icon" >follow us linked in</a></li>
                            <li><a href="" class="social-icons tumblr-icon" >follow us tumblr</a></li>
                            <li><a href="http://pinterest.com/madelinemilne/mexico-travels/" class="social-icons pinterest-icon" >follow us pinterest</a></li>
                        </ul>
                    </nav>
                </div>
            </header>
            <div id="central-content" <?php echo (!empty($this->class_div))? $this->class_div:'';?>>
                <?php echo $this->layout()->content ?> 
            </div>
            <footer class="footer-back">   
                <nav class="nav-left">
                <ul >
                    <li><a href=""><span class="bold">MARKETING SERVICES</span></a> <a href="">MEXI - GO!</a> / <a href="">ADVERTISE IN CANADA!</a> / <a href="">OUR READERS!</a> / <a href="">MEXI - GO.CA</a></li>
                    <li><a href=""><span class="bold">THE MAGAZINE</span></a> <a href="">PAPER MAGAZINE</a> / <a href="">ONLINE MAGAZINE</a></li>
                    <li><a href="sign-up-now.php"><span class="bold">SIGN UP NOW!</span></a></li>
                    <li><a href=""><span class="bold">MEXI-GO! NEWS</span></a></li>
                    <li><a href=""><span class="bold">CONTACT</span></a></li>
                </ul>
                </nav>                
                <nav id="footer-social-links" class="nav-right">
                        <ul >
                            <li><span>SOCIAL MEDIA:</span> </li>
                            <li><a href="https://www.facebook.com/MexiGoProperties" class="social-icons facebook-icon">follow us facebook</a></li>
                            <li><a href="https://twitter.com/MexigoProperty" class="social-icons twitter-icon" >follow us twitter</a></li>
                            <li><a href="http://www.linkedin.com/company/2285345?trk=tyah" class="social-icons linked-in-icon" >follow us linked in</a></li>
                            <li><a href="" class="social-icons tumblr-icon" >follow us tumblr</a></li>
                            <li><a href="http://pinterest.com/madelinemilne/mexico-travels/" class="social-icons pinterest-icon" >follow us pinterest</a></li>
                        </ul>
                    </nav>
                <p class="copyright">&copy;2012 Mexi-Go.ca - Connecting Mexico to Canadians</p>
            </footer>
        </div>    
    </body>
</html>
