<?php echo $this->MenuLateral('menu-magazine');?>
<section id="block-center" class="magazine">
    <div class="center-paragraph">
        <div class="photo-frame">
            <img src="/front/images/img-10.jpg" alt="" title="" />
        </div>
        <div class="clear-both"></div>
        <h1 class="big-title oswald align-center">MORE MEXICO! MORE OFTEN!</h1>
        <h2 class="Oswald-normal-300 no-margin align-center">Now published online every month!</h2>
        <div class="orange-box">
            <p>
                Mexi-Go! Magazine will now publish an online magazine every month and every 3 months will continue to print 25,000 copies of the high quality Mexi-Go! magazine that our clients and viewers love to read.
                Each issue will feature articles on Canadians in Mexico, lifestyle, culture, retirement, investment, travel and real estate. 
                We are bringing more Mexico to Canada than ever before!
            </p>
        </div>
        <div class="align-center">
            <p class="orange-letter oswald">ADVERTISE NOW</p>
            <input type="button" id="btn-become-partner" class="generals-buttons no-margin" value="BECOME A CONTRIBUTOR">
            </p>
        </div>
        <div class="separator-20"></div>
        <p class="orange-letter oswald">ADVERTISE NOW</p>
        <p>
            Emailed to 14,000+ readers each month, the new online
            magazine will remain online at www.mexi-go.ca.
            Each issue will be emailed to our readers each month, and 
            promoted through various social media and PR campaigns including Facebook and Twitter. 
            Currently each issue recieves approximately 10,000 online views in addition to the 25,000 printed copies.
        </p>
        <div class="align-center">
            <div class="separator-20"></div>
            <img src="/front/images/mexigo-ipad-magazine.png"><br/>
            <input type="button" id="btn-become-partner" class="generals-buttons no-margin" value="VIEW ONLINE MAGAZINES"><br/>
            <div class="separator-5"></div>
            <input type="button" id="btn-become-partner" class="generals-buttons no-margin" value="BECOME A CONTRIBUTOR">
        </div>
    </div>
</section>
<?php echo $this->MenuLateral('rigth-colum');?>