<section id="left-content">
    <div class="photo-frame">
        <img src="/front/images/image-news.jpg" alt="" title="" />
    </div>

    <div class="tooltip-arrow">&nbsp;</div>
    <div class="style2-shadow paragraph-tooltip-style box efecto2">
        <h3 class="h3-cms h3-tooltip">Lorem Ipsum Dolor</h3>
        <p class="little-grey-oblique-letter">19th April 2012</p>
        <h4 class="h4-cms">Lorem Ipsum Dolor</h4>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent molestie magna quis mauris semper eget scelerisque elit ornare. Integer scelerisque sollicitudin felis, a ultricies ante consectetur ac. Duis sit amet ligula eros. Nullam ultrices leo eu metus egestas vulputate. Fusce sit amet nisi nisl. Nulla facilisi. 
        </p>
    </div>
    <div class="separator-40"></div>
    <img src="/front/images/mexigo-logo.png" />
    <div class="separator-20"></div>
    <div class="tooltip-arrow">&nbsp;</div>
    <div class="style2-shadow paragraph-tooltip-style box efecto2">
        <h3 class="h3-cms h3-tooltip">Lorem Ipsum Dolor</h3>
        <p class="little-grey-oblique-letter">19th April 2012</p>
        <h4 class="h4-cms">Lorem Ipsum Dolor</h4>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent molestie magna quis mauris semper eget scelerisque elit ornare. Integer scelerisque sollicitudin felis, a ultricies ante consectetur ac. Duis sit amet ligula eros. Nullam ultrices leo eu metus egestas vulputate. Fusce sit amet nisi nisl. Nulla facilisi. 
        </p>
    </div>
</section>
<div class="news-box col col_5">
    <div class="side_element">
        <h2>Mexi-Go! News</h2>
        <p class="oswald">Recive Updates</p>
        <form id="submit-mail">
            <input type="text" class="default-input" value="Type your e-mail address">
            <a class="no-margen-left grey-gradient default-button button-shadow oswald" href="">SUBMIT >></a>
        </form>
        <div class="clear-both"></div>
        <h3>Recent NEWS</h3>
        <ul class="recent">
            <li><a title="Making a jQuery pagination system" href="article.html">Ut eget metus nibh, nec scelerisque sem. Nulla dui purus, pellentesque sit amet rutrum </a><p>12th Febrary 2012</p></li>
            <li><a title="Making a jQuery pagination system" href="article.html">Ut eget metus nibh, nec scelerisque sem. Nulla dui purus, pellentesque sit amet rutrum </a><p>12th Febrary 2012</p></li>
            <li><a title="Making a jQuery pagination system" href="article.html">Ut eget metus nibh, nec scelerisque sem. Nulla dui purus, pellentesque sit amet rutrum </a><p>12th Febrary 2012</p></li>
        </ul>	
    </div><!-- side_element -->
    <div id="categories" class="side_element">
        <h3>CATEGORIES</h3>
        <a class="no-margen-left grey-gradient default-button button-shadow" href="">Moving to Mexico</a>
        <a class="no-margen-left grey-gradient default-button button-shadow" href="">Mexico Real Estate</a>
        <a class="no-margen-left grey-gradient default-button button-shadow" href="">Canadians in Mexico</a>
        <a class="no-margen-left grey-gradient default-button button-shadow" href="">Retirement</a>
        <a class="no-margen-left grey-gradient default-button button-shadow" href="">Travel inmexico</a>
        <a class="no-margen-left grey-gradient default-button button-shadow" href="">Baja California Sur</a>
        <a class="no-margen-left grey-gradient default-button button-shadow" href="">Buying Real Estate in Mexico</a>
        <a class="no-margen-left grey-gradient default-button button-shadow" href="">Cabo San Lucas</a>
        <a class="no-margen-left grey-gradient default-button button-shadow oswald" href="">Puerto Pallarta Real Estate</a>
    </div>
    <div id="archives" class="side_element">
        <h3>ARCHIVES</h3>
        <ul>
            <li>
                May 2012
            </li>
            <li>
                April 2012
            </li>
            <li>
                March 2012
            </li>
            <li>
                February 2012
            </li>
            <li>
                January 2012
            </li>
            <li>
                December 2012
            </li>
            <li>
                October 2012
            </li>
            <li>
                September 2012
            </li>
            <li>
                August 2012
            </li>
        </ul>

    </div>
</div>