<div id="central-content">
    <p class="oswald" id="my-account">My Account</p>
    <aside class="oswald" id="block-left">
        <p class=" bg-white" id="hi-lateral">HI blackswaninteractive</p>
        <div id="color-fondo">

            <p class="lateral-selected " id="account-settings-menu"><a href="account-settings.php">ACCOUNT SETTINGS</a></p>
            <nav>
                <div class="menu-lateral-bg-gris-oscuro">
                    <p class="text-white " id="manage-your-style">Manage your</p>
                    <ul>
                        <li class="text-yellow menu-lateral-relative"><a title="go to profile page" href="profile-page.php">PROFILE PAGE</a></li>
                        <li class="lateral-selected text-yellow "><a title="go to agents" href="agents.php">AGENTS</a></li>
                        <li class="text-yellow menu-lateral-relative"><a title="go to real estate listings" href="real-estate-listings.php">REAL ESTATE LISTINGS</a></li>
                    </ul>
                </div>
                <ul>
                    <li class="text-yellow menu-lateral-bg-gris-claro" id="menu-buy"><a href="">BUY</a></li>
                    <li class="lateral-selected"><a href="">EMAIL PREFERENCES</a></li>
                    <li><a href="reset-password">ACCOUNT PASSWORD</a></li>
                    <li><a href="">SIGN OUT</a></li>
                </ul>
            </nav>    
        </div>
        <div id="linea-fondo">
        </div>
    </aside>
    <section id="block-right">
        <h2 class="h2-cms oswald">About this home</h2>
        <p id="number-published"><span>Home / Features</span></p>

        <div id="listings-about">
            <form id="listings-about-form" method="post" action="">
                <fieldset><legend class="oswald">ABOUT THIS HOME</legend>
                    <p class="listings-about-header-1 oswald"><span>STATUS</span></p>
                    <div class="combo-fix">
                        <label for="available">Available</label>
                        <div class="flecha-combo">
                            <select name="available" id="available" type="text">
                                <?php foreach($this->listAvailable as $index=>$value): ?>
                                <option value='<?php echo $index;?>'><?php echo $value;?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div><br>
                    <p class="listings-about-header-1 oswald"><span>SELECT PROPERTY TYPE</span></p>
                    <div class="combo-fix float-left inline-block clear-none">
                        <label for="listingStatus">Listing Status</label>
                        <div class="flecha-combo">
                            <select name="listingStatus" id="listingStatus" type="text">
                                <?php foreach($this->listPropertyStatus as $index=>$value):?>
                                <option value="<?php echo $index; ?>"><?php echo $value; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="combo-fix float-left inline-block clear-none">
                        <label class="label-special-width" for="propertyType">Property Type</label>
                        <div class="flecha-combo">
                            <select name="propertyType" id="propertyType" type="text">
                                <?php foreach($this->listPropertyType as $index=>$value):?>
                                <option value="<?php echo $index; ?>"><?php echo $value; ?></option>
                                <?php endforeach; ?>

                            </select>
                        </div>
                    </div><br>
                    <p class="listings-about-header-1 oswald"><span>PRICE</span></p>
                    <div class="combo-fix">
                        <label for="priceValue">$ </label>
                        <input type="text" class="float-left special-margen-right" name="priceValue" id="priceValue">
                        <div class="flecha-combo-chico-1"><select class="select-chico-1" name="priceCoin" id="priceCoin" type="text"><option>USD</option><option>AUS</option><option>EUR</option></select></div>
                    </div>
                    <p class="listings-about-header-1 oswald"><span>PROPERTY DETAILS</span></p>
                    <div class="combo-fix">
                        <label for="houseValue">House</label>
                        <input type="text" class="float-left special-margen-right" name="houseValue" id="houseValue">
                        <div class="flecha-combo-chico-1"><select class="select-chico-1" name="houseMedida" id="houseMedida" type="text"><option>M²</option><option>Yes</option><option>No</option></select></div>
                    </div>
                    <div class="combo-fix">
                        <label for="landValue">Land</label>
                        <input type="text" class="float-left special-margen-right" name="landValue" id="landValue">
                        <div class="flecha-combo-chico-1"><select class="select-chico-1" name="landMedida" id="landMedida" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                    </div>
                    <p class="listings-about-header-1 oswald"><span>SELECT FEATURES</span></p>
                    <div class="margin-bottom-special">
                        <div class="combo-fix float-left inline-block clear-none">
                            <label for="bedroom">Bedroom</label>
                            <div class="flecha-combo">
                                <select name="bedroom" id="bedroom" type="text">
                                    <?php foreach($this->listBedroom as $index=>$value): ?>
                                <option value='<?php echo $index;?>'><?php echo $value;?></option>
                                <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="combo-fix float-left inline-block clear-none">
                            <label class="label-special-width" for="bathrooms">Bathrooms</label>
                            <div class="flecha-combo">
                                <select name="bathrooms" id="bathrooms" type="text">
                                    <?php foreach($this->listBathrooms as $index=>$value): ?>
                                <option value='<?php echo $index;?>'><?php echo $value;?></option>
                                <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="margin-bottom-special">
                        <div class="combo-fix float-left inline-block clear-none">
                            <label for="style">Style</label>
                            <div class="flecha-combo">
                                <select name="style" id="style" type="text">
                                <?php foreach($this->listPropertyStyle as $index=>$value):?>
                                <option value="<?php echo $index; ?>"><?php echo $value; ?></option>
                                <?php endforeach; ?>

                                </select>
                            </div>
                        </div>
                        <div class="combo-fix float-left inline-block clear-none">
                            <label class="label-special-width" for="keyword">Keyword</label>
                            <input type="text" class="float-left" name="keyword" id="keyword">
                        </div>
                    </div>
                    <div class="margin-bottom-special">
                        <div class="combo-fix float-left inline-block clear-none">
                            <label for="garage">Garage</label>
                            <div class="flecha-combo">
                                <select name="garage" id="garage" type="text">
                                <?php foreach($this->listGarage as $index=>$value): ?>
                                <option value='<?php echo $index;?>'><?php echo $value;?></option>
                                <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="combo-fix float-left inline-block clear-none">
                            <label class="label-special-width" for="address">Address</label>
                            <input type="text" class="float-left" name="address" id="address">
                        </div>
                    </div>
                    <div class="margin-bottom-special">
                        <div class="combo-fix float-left inline-block clear-none">
                            <label for="view">View</label>
                            <div class="flecha-combo">
                                <select name="view" id="view" type="text">
                                <?php foreach($this->listPropertyView as $index=>$value):?>
                                <option value="<?php echo $index; ?>"><?php echo $value; ?></option>
                                <?php endforeach; ?>

                                </select>
                            </div>
                        </div>
                        <div class="combo-fix float-left inline-block clear-none">
                            <label class="label-special-width" for="size">Size (sq.ft.)</label>
                            <input type="text" class="float-left special-margen-right" name="size" id="size">
                        </div>
                    </div>
                    <div class="combo-fix">
                        <label for="recreation">Recreational Areas</label>
                        <div class="flecha-combo">
                            <select name="recreation" id="recreation" type="text">
                                <?php foreach($this->listRecreation as $index=>$value): ?>
                                <option value='<?php echo $index;?>'><?php echo $value;?></option>
                                <?php endforeach; ?>

                            </select>
                        </div>
                    </div>
                    <p class="listings-about-header-2 oswald"><span>FEATURES</span></p>
                    <div class="contenedor-picks-1">
                        <?php
                        $cantSubCat = count($this->listFeatures);
                        $cantColumn = (int) ($cantSubCat / 3);
                        $residuo = (int) ($cantSubCat % 3);
                        $output1 = array_slice($this->listFeatures, 0, ($cantColumn), true);      // returns "c", "d", and "e"
                        $output2 = array_slice($this->listFeatures, $cantColumn, $cantColumn, true);  // returns "d"
                        $output3 = array_slice($this->listFeatures, 2 * $cantColumn, $cantColumn + $residuo, true);   // returns "a", "b", and "c"
                        $arrayApplianve = array($output1, $output2, $output3);
                        ?>
                        <?php
                        foreach ($arrayApplianve as $indexFeature => $valueFeature):
                            switch ($indexFeature) {
                                case 0:
                                    $class = 'pick-izq-2';
                                    break;
                                case 1:
                                    $class = 'pick-med-2';
                                    break;
                                case 2:
                                    $class = 'pick-der-2';
                                    break;
                            }
                            ?>
                            <div class="<?php echo $class; ?>">
                                <?php foreach ($valueFeature as $index => $value): ?>
                                    <?php
//                                                                        if(isset($this->listingSubcategoriaRel[$index])) {
//                                                                            $checked = 'checked="checked"';
//                                                                        } else{
//                                                                            $checked='';
//                                                                        }
                                    ?>
        <!--                                                                        <input <?php echo $checked ?>  value="<?php echo $index ?>" name="profileSubCategoria[]" id="check<?php echo $index ?>" type="checkbox"><label for="check<?php echo $index ?>" class="label-check2"><?php echo $value ?></label>-->
                                    <label class="label-check3 check-special" id="label-checkFeature<?php echo $index ?>" for="checkFeature<?php echo $index ?>"><?php echo $value ?></label><input type="checkbox" value="<?php echo $index ?>" name="featureFeature[]" id="checkFeature<?php echo $index ?>">
                                <?php endforeach; ?>
                            </div>
                        <?php endforeach; ?>
                    </div>

                    <p class="listings-about-header-3 oswald"><span>OUT BUILDINGS</span></p>
                    <div class="contenedor-picks-2">
<?php
                        $cantSubCat = count($this->listBuildings);
                        $cantColumn = (int) ($cantSubCat / 3);
                        $residuo = (int) ($cantSubCat % 3);
                        $output1 = array_slice($this->listBuildings, 0, ($cantColumn), true);      // returns "c", "d", and "e"
                        $output2 = array_slice($this->listBuildings, $cantColumn, $cantColumn, true);  // returns "d"
                        $output3 = array_slice($this->listBuildings, 2 * $cantColumn, $cantColumn + $residuo, true);   // returns "a", "b", and "c"
                        $arrayApplianve = array($output1, $output2, $output3);
                        ?>
                        <?php
                        foreach ($arrayApplianve as $indexFeature => $valueFeature):
                            switch ($indexFeature) {
                                case 0:
                                    $class = 'pick-izq-2';
                                    break;
                                case 1:
                                    $class = 'pick-med-2';
                                    break;
                                case 2:
                                    $class = 'pick-der-2';
                                    break;
                            }
                            ?>
                            <div class="<?php echo $class; ?>">
                                <?php foreach ($valueFeature as $index => $value): ?>
                                    <?php
//                                                                        if(isset($this->listingSubcategoriaRel[$index])) {
//                                                                            $checked = 'checked="checked"';
//                                                                        } else{
//                                                                            $checked='';
//                                                                        }
                                    ?>
                                    <label class="label-check3 check-special" id="label-checkBulinding<?php echo $index ?>" for="checkBulinding<?php echo $index ?>"><?php echo $value ?></label><input type="checkbox" value="<?php echo $index ?>" name="featureBulinding[]" id="checkBulinding<?php echo $index ?>"/>
                                <?php endforeach; ?>
                            </div>
                        <?php endforeach; ?>
                    </div>

                    <p class="listings-about-header-3 oswald"><span>APPLIANCES</span></p>
                    <div class="contenedor-picks-3">
<?php
                        $cantSubCat = count($this->listAppliances);
                        $cantColumn = (int) ($cantSubCat / 3);
                        $residuo = (int) ($cantSubCat % 3);
                        $output1 = array_slice($this->listAppliances, 0, ($cantColumn), true);      // returns "c", "d", and "e"
                        $output2 = array_slice($this->listAppliances, $cantColumn, $cantColumn, true);  // returns "d"
                        $output3 = array_slice($this->listAppliances, 2 * $cantColumn, $cantColumn + $residuo, true);   // returns "a", "b", and "c"
                        $arrayApplianve = array($output1, $output2, $output3);
                        ?>
                        <?php
                        foreach ($arrayApplianve as $indexFeature => $valueFeature):
                            switch ($indexFeature) {
                                case 0:
                                    $class = 'pick-izq-2';
                                    break;
                                case 1:
                                    $class = 'pick-med-2';
                                    break;
                                case 2:
                                    $class = 'pick-der-2';
                                    break;
                            }
                            ?>
                            <div class="<?php echo $class; ?>">
                                <?php foreach ($valueFeature as $index => $value): ?>
                                    <?php
//                                                                        if(isset($this->listingSubcategoriaRel[$index])) {
//                                                                            $checked = 'checked="checked"';
//                                                                        } else{
//                                                                            $checked='';
//                                                                        }
                                    ?>
                                    <label class="label-check3 check-special" id="label-checkAppliances<?php echo $index ?>" for="checkAppliances<?php echo $index ?>"><?php echo $value ?></label><input value="<?php echo $index ?>" type="checkbox" name="featureAppliances[]" id="checkAppliances<?php echo $index ?>"/>
                                <?php endforeach; ?>
                            </div>
                        <?php endforeach; ?>
                        
                    </div>
                    <div class="hr-gris-div"></div>
                    <p class="oswald" id="botonera">
                        <span>Draft</span><input type="submit" value="SAVE &gt;&gt;" class="boton-css-formato boton-css-gradient-yellow oswald round-corner-5">
                        <a class="float-right boton-css-formato boton-css-gradient-yellow round-corner-5" href="">NEXT &gt;&gt;</a>
                    </p>
                </fieldset>
            </form>


        </div>
    </section>
</div>