<div id="central-content">
                    <p class="oswald" id="my-account">My Account</p>
                    <aside class="oswald" id="block-left">
    <p class=" bg-white" id="hi-lateral">HI blackswaninteractive</p>
    <div id="color-fondo">
    
    <p class="lateral-selected " id="account-settings-menu"><a href="account-settings.php">ACCOUNT SETTINGS</a></p>
    <nav>
        <div class="menu-lateral-bg-gris-oscuro">
        <p class="text-white " id="manage-your-style">Manage your</p>
        <ul>
            <li class="text-yellow menu-lateral-relative"><a title="go to profile page" href="profile-page.php">PROFILE PAGE</a></li>
            <li class="lateral-selected text-yellow "><a title="go to agents" href="agents.php">AGENTS</a></li>
            <li class="text-yellow menu-lateral-relative"><a title="go to real estate listings" href="real-estate-listings.php">REAL ESTATE LISTINGS</a></li>
        </ul>
        </div>
        <ul>
            <li class="text-yellow menu-lateral-bg-gris-claro" id="menu-buy"><a href="">BUY</a></li>
            <li class="lateral-selected"><a href="">EMAIL PREFERENCES</a></li>
            <li><a href="reset-password">ACCOUNT PASSWORD</a></li>
            <li><a href="">SIGN OUT</a></li>
        </ul>
    </nav>    
    </div>
    <div id="linea-fondo">
    </div>
</aside>
                    <section id="block-right">
                            <h2 class="h2-cms oswald">About this home</h2>
                            <p id="number-published"><span>Home / Features</span></p>
                            
                            <div id="listings-about">
								<form id="listings-about-form">
								<fieldset><legend class="oswald">ABOUT THIS HOME</legend>
                                <p class="listings-about-header-1 oswald"><span>STATUS</span></p>
								<div class="combo-fix">
									<label for="available">Available</label>
									<div class="flecha-combo"><select name="available" id="available" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                                </div><br>
								<p class="listings-about-header-1 oswald"><span>SELECT PROPERTY TYPE</span></p>
								<div class="combo-fix float-left inline-block clear-none">
									<label for="listingStatus">Listing Status</label>
									<div class="flecha-combo"><select name="listingStatus" id="listingStatus" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                                </div>
								<div class="combo-fix float-left inline-block clear-none">
									<label class="label-special-width" for="propertyType">Property Type</label>
									<div class="flecha-combo"><select name="propertyType" id="propertyType" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                                </div><br>
								<p class="listings-about-header-1 oswald"><span>PRICE</span></p>
								<div class="combo-fix">
									<label for="priceValue">$ </label>
									<input type="text" class="float-left special-margen-right" name="priceValue" id="priceValue">
									<div class="flecha-combo-chico-1"><select class="select-chico-1" name="priceCoin" id="priceCoin" type="text"><option>USD</option><option>AUS</option><option>EUR</option></select></div>
                                </div>
								<p class="listings-about-header-1 oswald"><span>PROPERTY DETAILS</span></p>
								<div class="combo-fix">
									<label for="houseValue">House</label>
									<input type="text" class="float-left special-margen-right" name="houseValue" id="houseValue">
									<div class="flecha-combo-chico-1"><select class="select-chico-1" name="houseMedida" id="houseMedida" type="text"><option>M²</option><option>Yes</option><option>No</option></select></div>
                                </div>
								<div class="combo-fix">
									<label for="landValue">Land</label>
									<input type="text" class="float-left special-margen-right" name="landValue" id="landValue">
									<div class="flecha-combo-chico-1"><select class="select-chico-1" name="landMedida" id="landMedida" type="text"><option>Any</option><option>Yes</option><option>No</option></select></div>
                                </div>
								<p class="listings-about-header-1 oswald"><span>SELECT FEATURES</span></p>
								<div class="margin-bottom-special">
								<div class="combo-fix float-left inline-block clear-none">
									<label for="bedroom">Bedroom</label>
									<div class="flecha-combo"><select name="bedroom" id="bedroom" type="text"><option>Any</option><option>1</option><option>2</option></select></div>
                                </div>
								<div class="combo-fix float-left inline-block clear-none">
									<label class="label-special-width" for="bathrooms">Bathrooms</label>
									<div class="flecha-combo"><select name="bathrooms" id="bathrooms" type="text"><option>Any</option><option>1</option><option>2</option></select></div>
                                </div>
								</div>
								<div class="margin-bottom-special">
								<div class="combo-fix float-left inline-block clear-none">
									<label for="style">Style</label>
									<div class="flecha-combo"><select name="style" id="style" type="text"><option>Any</option><option>1</option><option>2</option></select></div>
                                </div>
								<div class="combo-fix float-left inline-block clear-none">
									<label class="label-special-width" for="keyword">Keyword</label>
									<input type="text" class="float-left" name="keyword" id="keyword">
                                </div>
								</div>
								<div class="margin-bottom-special">
								<div class="combo-fix float-left inline-block clear-none">
									<label for="garage">Garage</label>
									<div class="flecha-combo"><select name="garage" id="garage" type="text"><option>Any</option><option>1</option><option>2</option></select></div>
                                </div>
								<div class="combo-fix float-left inline-block clear-none">
									<label class="label-special-width" for="address">Address</label>
									<input type="text" class="float-left" name="address" id="address">
                                </div>
								</div>
								<div class="margin-bottom-special">
								<div class="combo-fix float-left inline-block clear-none">
									<label for="view">View</label>
									<div class="flecha-combo"><select name="view" id="view" type="text"><option>Any</option><option>1</option><option>2</option></select></div>
                                </div>
								<div class="combo-fix float-left inline-block clear-none">
									<label class="label-special-width" for="size">Size (sq.ft.)</label>
									<input type="text" class="float-left special-margen-right" name="size" id="size">
                                </div>
								</div>
								<div class="combo-fix">
									<label for="recreation">Recreational Areas</label>
									<div class="flecha-combo"><select name="recreation" id="recreation" type="text"><option>Any</option><option>1</option><option>2</option></select></div>
                                </div>
								<p class="listings-about-header-2 oswald"><span>FEATURES</span></p>
								<div class="contenedor-picks-1">
									<div class="pick-izq-2">
									<label class="label-check3 check-special" id="label-checkBBQ" for="checkBBQ">BBQ Area</label><input type="checkbox" name="checkBBQ" id="checkBBQ">
									<label class=" label-check3 check-special" id="label-checkBeach" for="checkBeach">Beach Club</label><input type="checkbox" id="checkBeach">
									<label class="label-check3 check-special" id="label-checkBeamed" for="checkBeamed">Beamed Ceilings</label><input type="checkbox" id="checkBeamed">
									<label class="label-check3 check-special" id="label-checkBreakfast" for="checkBreakfast">Breakfast Nook</label><input type="checkbox" id="checkBreakfast">
									<label class="label-check3 check-special" id="label-checkCable" for="checkCable">Cable Television</label><input type="checkbox" id="checkCable">
									<label class="label-check3 check-special" id="label-checkCathedral" for="checkCathedral">Cathedral Ceilings</label><input type="checkbox" id="checkCathedral">
									<label class="label-check3 check-special" id="label-checkDeck" for="checkDeck">Deck</label><input type="checkbox" id="checkDeck">
									<label class="label-check3 check-special" id="label-checkFence" for="checkFence">Fence / Wall</label><input type="checkbox" id="checkFence">
									<label class="label-check3 check-special" id="label-checkFireplace" for="checkFireplace">Fireplace</label><input type="checkbox" id="checkFireplace">
									<label class="label-check3 check-special" id="label-checkFountain" for="checkFountain">Fountain</label><input type="checkbox" id="checkFountain">
									<label class="label-check3 check-special" id="label-checkGames" for="checkGames">Games Room</label><input type="checkbox" id="checkGames">
									</div>
									<div class="pick-med-2">
									<label class="label-check3 check-special" id="label-checkGarden" for="checkGarden">Garden</label><input type="checkbox" name="checkGarden" id="checkGarden">
									<label class="label-check3 check-special" id="label-checkGated" for="checkGated">Gated</label><input type="checkbox" id="checkGated">
									<label class="label-check3 check-special" id="label-checkGuarded" for="checkGuarded">Guarded</label><input type="checkbox" id="checkGuarded">
									<label class="label-check3 check-special" id="label-checkGym" for="checkGym">Gym</label><input type="checkbox" id="checkGym">
									<label class="label-check3 check-special" id="label-checkHighInternet" for="checkHighInternet">High Speed Internet</label><input type="checkbox" id="checkHighInternet">
									<label class="label-check3 check-special" id="label-checkHotTub" for="checkHotTub">Hot Tub</label><input type="checkbox" id="checkHotTub">
									<label class="label-check3 check-special" id="label-checkPalapa" for="checkPalapa">Palapa</label><input type="checkbox" id="checkPalapa">
									<label class="label-check3 check-special" id="label-checkPatio" for="checkPatio">Patio</label><input type="checkbox" id="checkPatio">
									<label class="label-check3 check-special" id="label-checkPool" for="checkPool">Pool</label><input type="checkbox" id="checkPool">
									<label class="label-check3 check-special" id="label-checkElevator" for="checkElevator">Private Elevator</label><input type="checkbox" id="checkElevator">
									<label class="label-check3 check-special" id="label-checkRoofTerrace" for="checkRoofTerrace">Roof Top Terrace</label><input type="checkbox" id="checkRoofTerrace">
									</div>
									<div class="pick-der-2">
										<label class="label-check3 check-special" id="label-checkSatelite" for="checkSatelite">Satellite Television</label><input type="checkbox" name="checkSatelite" id="checkSatelite">
									<label class="label-check3 check-special" id="label-checkSauna" for="checkSauna">Sauna</label><input type="checkbox" id="checkSauna">
									<label class="label-check3 check-special" id="label-checkSecondKitchen" for="checkSecondKitchen">Second Kitchen</label><input type="checkbox" id="checkSecondKitchen">
									<label class="label-check3 check-special" id="label-checkSpa" for="checkSpa">Spa</label><input type="checkbox" id="checkSpa">
									<label class="label-check3 check-special" id="label-checkStorage" for="checkStorage">Storage Area</label><input type="checkbox" id="checkStorage">
									<label class="label-check3 check-special" id="label-checkSwimBar" for="checkSwimBar">Swim-up Bar</label><input type="checkbox" id="checkSwimBar">
									<label class="label-check3 check-special" id="label-checkTennis" for="checkTennis">Tennis Court</label><input type="checkbox" id="checkTennis">
									<label class="label-check3 check-special" id="label-checkTerrace" for="checkTerrace">Terrace</label><input type="checkbox" id="checkTerrace">
									<label class="label-check3 check-special" id="label-checkTheater" for="checkTheater">Theater</label><input type="checkbox" id="checkTheater">
									<label class="label-check3 check-special" id="label-checkWineCellar" for="checkWineCellar">Wine Cellar</label><input type="checkbox" id="checkWineCellar">
									<label class="label-check3 check-special" id="label-checkWifi" for="checkWifi">Wireless Internet</label><input type="checkbox" id="checkWifi">
			
									</div>
								</div>
								
								<p class="listings-about-header-3 oswald"><span>OUT BUILDINGS</span></p>
								<div class="contenedor-picks-2">
									<div class="pick-izq-2">
										<label class="label-check3 check-special" id="label-checkBarn" for="checkBarn">Barn / Stable</label><input type="checkbox" name="checkBBQ" id="checkBarn">
										<label class="label-check3 check-special" id="label-checkBoatLift" for="checkBoatLift">Boatlift</label><input type="checkbox" id="checkBoatLift">
										<label class="label-check3 check-special" id="label-checkCarPort" for="checkCarPort">Car Port</label><input type="checkbox" id="checkCarPort">
										<label class="label-check3 check-special" id="label-checkCasita" for="checkCasita">Casita</label><input type="checkbox" id="checkCasita">
									
									</div>
									<div class="pick-med-2">
										<label class="label-check3 check-special" id="label-checkDock" for="checkDock">Dock / Pier</label><input type="checkbox" name="checkDock" id="checkDock">
										<label class="label-check3 check-special" id="label-checkGazebo" for="checkGazebo">Gazebo</label><input type="checkbox" id="checkGazebo">
										<label class="label-check3 check-special" id="label-checkMaidsQuarters" for="checkMaidsQuarters">Maids Quarters</label><input type="checkbox" id="checkMaidsQuarters">
										<label class="label-check3 check-special" id="label-checkPergola" for="checkPergola">Pergola</label><input type="checkbox" id="checkPergola">								
									</div>
									<div class="pick-der-2">
										<label class="label-check3 check-special" id="label-checkPoolHouse" for="checkPoolHouse">Pool House</label><input type="checkbox" name="checkPoolHouse" id="checkPoolHouse">
										<label class="label-check3 check-special" id="label-checkStudio" for="checkStudio">Studio</label><input type="checkbox" id="checkStudio">
									
			
									</div>
								</div>
								
								<p class="listings-about-header-3 oswald"><span>APPLIANCES</span></p>
								<div class="contenedor-picks-3">
									<div class="pick-izq-2">
									<label class="label-check3 check-special" id="label-checkAirConditioning" for="checkAirConditioning">Air Conditioning</label><input type="checkbox" name="checkAirConditioning" id="checkBBQ">
									<label class="label-check3 check-special" id="label-checkCeilingFan" for="checkCeilingFan">Ceiling Fans</label><input type="checkbox" id="checkCeilingFan">
									<label class="label-check3 check-special" id="label-checkCentralVac" for="checkCentralVac">Central Vac</label><input type="checkbox" id="checkCentralVac">
									<label class="label-check3 check-special" id="label-checkClothesDryer" for="checkClothesDryer">Clothes Dryer</label><input type="checkbox" id="checkClothesDryer">
									<label class="label-check3 check-special" id="label-checkClothesWasher" for="checkClothesWasher">Clothes washer</label><input type="checkbox" id="checkClothesWasher">
									<label class="label-check3 check-special" id="label-checkCompactorVac" for="checkCompactorVac">Compactor Vac</label><input type="checkbox" id="checkCompactorVac">
									<label class="label-check3 check-special" id="label-checkDish" for="checkDish">Dishwasher</label><input type="checkbox" id="checkDish">
									</div>
									<div class="pick-med-2">
										<label class="label-check3 check-special" id="label-checkDisposal" for="checkDisposal">Disposal</label><input type="checkbox" name="checkGarden" id="checkDisposal">
									<label class="label-check3 check-special" id="label-checkFreezer" for="checkFreezer">Freezer</label><input type="checkbox" id="checkFreezer">
									<label class="label-check3 check-special" id="label-checkIceMaker" for="checkIceMaker">Ice Maker</label><input type="checkbox" id="checkIceMaker">
									<label class="label-check3 check-special" id="label-checkMicrowave" for="checkMicrowave">Microwave</label><input type="checkbox" id="checkMicrowave">
									<label class="label-check3 check-special" id="label-checkMiniSplit" for="checkMiniSplit">Mini-Split</label><input type="checkbox" id="checkMiniSplit">
									<label class="label-check3 check-special" id="label-checkOvenElectric" for="checkOvenElectric">Oven: Electric</label><input type="checkbox" id="checkOvenElectric">
									<label class="label-check3 check-special" id="label-checkOvenGas" for="checkOvenGas">Oven: Gas</label><input type="checkbox" id="checkOvenGas">
									</div>
									<div class="pick-der-2">
										<label class="label-check3 check-special" id="label-checkRangeElectric" for="checkRangeElectric">Range: Electric</label><input type="checkbox" name="checkSatelite" id="checkRangeElectric">
									<label class="label-check3 check-special" id="label-checkRangeGas" for="checkRangeGas">Range: Gas</label><input type="checkbox" id="checkRangeGas">
									<label class="label-check3 check-special" id="label-checkRefrigerator" for="checkRefrigerator">Refrigerator</label><input type="checkbox" id="checkRefrigerator">
									<label class="label-check3 check-special" id="label-checkWaterHeater" for="checkWaterHeater">Water Heater</label><input type="checkbox" id="checkWaterHeater">
									<label class="label-check3 check-special" id="label-checkWaterPurification" for="checkWaterPurification">Water Purification</label><input type="checkbox" id="checkWaterPurification">
									<label class="label-check3 check-special" id="label-checkWineFridge" for="checkWineFridge">Wine Fridge</label><input type="checkbox" id="checkWineFridge">
									
									</div>
								</div>
								<div class="hr-gris-div"></div>
								<p class="oswald" id="botonera">
								<span>Draft</span><input type="submit" value="SAVE &gt;&gt;" class="boton-css-formato boton-css-gradient-yellow oswald round-corner-5">
								<a class="float-right boton-css-formato boton-css-gradient-yellow round-corner-5" href="">NEXT &gt;&gt;</a>
								</p>
								</fieldset>
								</form>
								
                                
                            </div>
                    </section>
                </div>