<div id="central-content">
    <p class="oswald" id="my-account">My Account</p>
    <aside class="oswald" id="block-left">
        <p class=" bg-white" id="hi-lateral">HI blackswaninteractive</p>
        <div id="color-fondo">

            <p class="lateral-selected " id="account-settings-menu"><a href="account-settings.php">ACCOUNT SETTINGS</a></p>
            <nav>
                <div class="menu-lateral-bg-gris-oscuro">
                    <p class="text-white " id="manage-your-style">Manage your</p>
                    <ul>
                        <li class="text-yellow menu-lateral-relative"><a title="go to profile page" href="profile-page.php">PROFILE PAGE</a></li>
                        <li class="lateral-selected text-yellow "><a title="go to agents" href="agents.php">AGENTS</a></li>
                        <li class="text-yellow menu-lateral-relative"><a title="go to real estate listings" href="real-estate-listings.php">REAL ESTATE LISTINGS</a></li>
                    </ul>
                </div>
                <ul>
                    <li class="text-yellow menu-lateral-bg-gris-claro" id="menu-buy"><a href="">BUY</a></li>
                    <li class="lateral-selected"><a href="">EMAIL PREFERENCES</a></li>
                    <li><a href="reset-password">ACCOUNT PASSWORD</a></li>
                    <li><a href="">SIGN OUT</a></li>
                </ul>
            </nav>    
        </div>
        <div id="linea-fondo">
        </div>
    </aside>
    <section id="block-right">
        <h2 class="h2-cms oswald">Agents</h2>
        <p id="number-published"><span>Agents / Listings</span></p>
        <div class="search-field-p oswald">Add homes to: USE AGENT NAME <span><form><input type="text" value="   Search"><input type="submit"></form></span></div>
        <div class="wrapper-agent-listings-2">
            <!--<div class="">-->
            <hr class="hr-custom">
            <div class="paginador">
                <span class="previous"><a href="">&lt;&lt; previous</a></span>
                <span class="number"><a href="">1</a></span>
                <span class="number actual"><a href="">2</a></span>
                <span class="puntos"></span>
                <span class="number "><a href="">10</a></span>
                <span class="next"><a href="">next &gt;&gt;</a></span>
            </div>
            <hr class="hr-custom">
            <!--</div>-->

            
       <?php  if(count($this->listPropertiesAgent)>0):?>
                            
                            <table id="tabla-agentes-listings">
                                <tbody><tr>
                                    <th class="th1"></th>
                                    <th class="th2"></th>
                                    <th class="th3"></th>
                                    <th class="th4">Featured</th>
                                    <th class="th5"></th>
                                </tr>
                                <?php foreach($this->listPropertiesAgent AS $value):?>
                                <tr>
                                    <td class="td1 oswald">
                                        <a href="">
                                            <img src="/../../static/images/ticked-icon.png">
                                        </a>
                                    </td>
                                    <td class="td2 house-thumb">
                                        <a href="">   
                                            <?php if(!empty($value['img_source'])):?>
                                            <img src="/../../dinamic/partner/real-estate/img/<?php echo $value['img_source']?>" 
                                            title="<?php echo $valor['img_title']?>" width="104px" height="74px">
                                            <?php else: ?> 
                                           <img src="/../public/dinamic/partner/real-estate/img/no-image.png" 
                                            title="No image avaiable">
                                           <?php endif;?>
                                        </a>
                                        These home are currently visible in your profile
                                    </td>
                                    <td class="td3"><p>
                                            <span class="house-title oswald">Oportunity Knocks!</span><br>
                                            <span class="house-geo"><?php echo $value['img_title']?></span><br>
                                            <span class="house-price ">USD $ <?php echo $value['pro_price']?></span>
                                        </p><p></p></td>
                                    <td class="td4">
                                        <img  src="/../static/images/black-star.png" />
                                    </td>
                                    <td class="td5 oswald">
                                        <a class="boton-yellow-1" href="">PREVIEW &gt;</a><a></a>
                                        <a class="boton-grey-3" 
                                           href="/partner/real-estate/delete-house/ida/<?php echo $this->age_id?>/idh/<?php echo $value['pro_id'] ?>">
                                            DELETE THIS HOME &gt;
                                        </a><a></a>
                                    </td>
                                </tr>
                            <?php  endforeach;?>
                                </tbody></table>
                            <?php endif;
                             if(!empty($this->listPropertiesNotAgent)):?>                            
                            <table id="tabla-agentes-listings-not-added">
                                <tbody><tr>
                                    <th class="th1"></th>
                                    <th class="th2"></th>
                                    <th class="th3"></th>
                                    <th class="th4">Featured</th>
                                    <th class="th5"></th>
                                </tr>
                                <?php foreach($this->listPropertiesNotAgent AS $value):?>
                                <tr>
                                    <td class="td1 oswald">
                                        <a href="/partner/real-estate/agent-assign/ida/<?php ?>/idh/">
                                            <img src="/../static/images/plus-icon.png">
                                        </a>
                                    </td>
                                    <td class="td2 no-house-thumb">
                                        <a href="">   
                                            <?php if(!empty($value['img_source'])):?>
                                            <img src="/../../dinamic/partner/real-estate/img/<?php echo $value['img_source']?>" 
                                            title="<?php echo $valor['img_title']?>" width="104px" height="74px">
                                            <?php else: ?> 
                                           <img src="/../public/dinamic/partner/real-estate/img/no-image.png" 
                                            title="No image avaiable">
                                           <?php endif;?>
                                        </a>
                                    </td>
                                    <td class="td3 oswald"><p>No info available</p><p></p></td>
                                    <td class="td4"><img src="/../static/images/black-star.png"></td>
                                    <td class="td5 oswald"><a class="boton-yellow-1" href="">PREVIEW &gt;</a><a></a>
                                        <a class="boton-yellow-3" 
                                           href="/partner/real-estate/agent-assign/ida/<?php echo $this->age_id?>/idh/<?php echo $value['pro_id'] ?>">
                                            ADD THIS HOME &gt;&gt;
                                        </a><a>
                                            
                                        </a></td>
                                </tr>
                               <?php endforeach;?>
                            </tbody></table>
                            <?php endif;?>
            
            
            <hr class="hr-custom">
            <div class="paginador">
                <span class="previous"><a href="">&lt;&lt; previous</a></span>
                <span class="number"><a href="">1</a></span>
                <span class="number actual"><a href="">2</a></span>
                <span class="puntos"></span>
                <span class="number "><a href="">10</a></span>
                <span class="next"><a href="">next &gt;&gt;</a></span>
            </div>
            <p class="align-center"><input type="submit" value="SAVE AND CONTINUE &gt;&gt;" class="oswald boton-yellow-4 hand"></p>
        </div>
    </section>
</div>