<div id="central-content">
                    <p class="oswald" id="my-account">My Account</p>
                    <aside class="oswald" id="block-left">
    <p class=" bg-white" id="hi-lateral">HI blackswaninteractive</p>
    <div id="color-fondo">
    
    <p class="lateral-selected " id="account-settings-menu"><a href="account-settings.php">ACCOUNT SETTINGS</a></p>
    <nav>
        <div class="menu-lateral-bg-gris-oscuro">
        <p class="text-white " id="manage-your-style">Manage your</p>
        <ul>
            <li class="text-yellow menu-lateral-relative"><a title="go to profile page" href="profile-page.php">PROFILE PAGE</a></li>
            <li class="lateral-selected text-yellow "><a title="go to agents" href="agents.php">AGENTS</a></li>
            <li class="text-yellow menu-lateral-relative"><a title="go to real estate listings" href="real-estate-listings.php">REAL ESTATE LISTINGS</a></li>
        </ul>
        </div>
        <ul>
            <li class="text-yellow menu-lateral-bg-gris-claro" id="menu-buy"><a href="">BUY</a></li>
            <li class="lateral-selected"><a href="">EMAIL PREFERENCES</a></li>
            <li><a href="reset-password">ACCOUNT PASSWORD</a></li>
            <li><a href="">SIGN OUT</a></li>
        </ul>
    </nav>    
    </div>
    <div id="linea-fondo">
    </div>
</aside>
                    <section id="block-right">
                            <h2 class="h2-cms oswald">
                                <?php echo isset($this->tituloH1)?$this->tituloH1 :
                                    'Real estate listings' ?></h2>
                            <p id="number-published">
                                <?php echo isset($this->tituloH2)? $this->tituloH2:
                                "<span>Your current Listings:</span> You have 
                                    <span>1 of 100</span> Listings Published</p>";?></p>
                            <div class="wrapper-agent-listings-2">
                            <!--<div class="">-->
                            <table id="tabla-agentes">
                                <tbody><tr>
                                    <th id="th1">PLAN DETAILS</th>
                                    <th id="th2"></th>
                                    <th id="th3">Time Left</th>
                                    <th id="th4">Status</th>
                                    <th id="th5">Subscription</th>
                                </tr>
                                <tr>
                                    <td class="oswald" id="td1"><p>SILVER PACKAGE</p><p></p></td>
                                    <td id="td2"><p>100 Listings<br>200 sales agents</p><p></p></td>
                                    <td id="td3"><span>months</span> 5</td>
                                    <td class="oswald" id="td4"><img src="images/black-star.png"><br>5 FEATURED</td>
                                    <td class="oswald" id="td5"><a class="boton-yellow-2" href="">BUY MORE &gt;&gt;</a> </td>
                                </tr>
                            </tbody></table>
                                <div id="registros-agentes">
                                    <p class="align-right">
                                        <a class="add-agents oswald" 
                                           href="/partner/agent/create">
                                            Add Agents
                                        </a>
                                    </p>
                                <div class="paginador">
                                    <span class="previous"><a href="">&lt;&lt; previous</a></span>
                                    <span class="number"><a href="">1</a></span>
                                    <span class="number actual"><a href="">2</a></span>
                                    <span class="puntos"></span>
                                    <span class="number "><a href="">10</a></span>
                                    <span class="next"><a href="">next &gt;&gt;</a></span>
                                </div>
                                <hr class="hr-custom">
                            <!--</div>-->
                            <h3>
                                <span class="oswald">Published</span>
                                (These homes arre currently visible in your profile)
                            </h3>
                            <?php  if(count($this->listPropertiesAgent)>0):?>
                            
                            <table id="tabla-agentes-listings">
                                <tbody><tr>
                                    <th class="th1"></th>
                                    <th class="th2"></th>
                                    <th class="th3"></th>
                                    <th class="th4">Featured</th>
                                    <th class="th5"></th>
                                </tr>
                                <?php foreach($this->listPropertiesAgent AS $value):?>
                                <tr>
                                    <td class="td1 oswald">
                                        <a href="">
                                            <img src="/../../static/images/ticked-icon.png">
                                        </a>
                                    </td>
                                    <td class="td2 house-thumb">
                                        <img width="104px" height="74px"
                                         src="/../../dinamic/partner/real-estate/img/<?php echo $value['img_source']?>">
                                        These home are currently visible in your profile</td>
                                    <td class="td3"><p>
                                            <span class="house-title oswald">Oportunity Knocks!</span><br>
                                            <span class="house-geo"><?php echo $value['img_title']?></span><br>
                                            <span class="house-price ">USD $ <?php echo $value['pro_price']?></span>
                                        </p><p></p></td>
                                    <td class="td4">
                                        <img  src="/../static/images/black-star.png" />
                                    </td>
                                    <td class="td5 oswald">
                                        <a class="boton-yellow-1" href="">EDIT &gt;&gt;</a><a></a><a class="boton-yellow-1" href="">PREVIEW &gt;</a><a></a><a class="boton-yellow-2" href="">UNPUBLISH &gt;&gt;</a><a></a></td>
                                </tr>
                            <?php  endforeach;?>
                                </tbody></table>
                            <?php endif?>
                            <?php if(!empty($this->listPropertiesNotAgent)):?>
                            <h3><span class="oswald">Draft</span> (These home will not be visible in your profile until you publish them)</h3>
                            <table id="tabla-agentes-listings-not-added">
                                <tbody><tr>
                                    <th class="th1"></th>
                                    <th class="th2"></th>
                                    <th class="th3"></th>
                                    <th class="th4">Featured</th>
                                    <th class="th5"></th>
                                </tr>
                                <?php foreach($this->listPropertiesNotAgent AS $valor):?>
                                <tr>
                                    <td class="td1 oswald">
                                        <a href="">                                            
                                            <img src="/../public/dinamic/partner/real-estate/img/<?php echo $valor['img_source']?>" 
                                            title="<?php echo $valor['img_title']?>">">
                                        </a>
                                    </td>
                                    <td class="td2 no-house-thumb"></td>
                                    <td class="td3 oswald"><p>No info available</p><p></p></td>
                                    <td class="td4"><img src="/../public/static/images/black-star.png"></td>
                                    <td class="td5 oswald"><a class="boton-yellow-1" href="">EDIT &gt;&gt;</a>
                                        <a></a>
                                        <a class="boton-yellow-1" href="">PREVIEW &gt;&gt;</a>
                                        <a></a>
                                        <a class="boton-yellow-2" href="">PUBLISH &gt;&gt;</a>
                                        <a></a>
                                    </td>
                                </tr>
                               <?php endforeach;?>
                            </tbody></table>
                            <?php endif;?>
                            <hr class="hr-custom">
                            <div class="paginador">
                                    <span class="previous"><a href="">&lt;&lt; previous</a></span>
                                    <span class="number"><a href="">1</a></span>
                                    <span class="number actual"><a href="">2</a></span>
                                    <span class="puntos"></span>
                                    <span class="number "><a href="">10</a></span>
                                    <span class="next"><a href="">next &gt;&gt;</a></span>
                                </div>
                            <p class="align-center"><input type="submit" value="SAVE AND CONTINUE &gt;&gt;" class="oswald boton-yellow-4 hand"></p>
                            <hr class="hr-custom">
                                <p class="auto-renewal">Auto Renewal ON</p>
                                </div>
                            </div>
                    </section>
            </div>