<div id="central-content">
    <p class="oswald" id="my-account">My Account</p>
    <aside class="oswald" id="block-left">
        <p class=" bg-white" id="hi-lateral">HI blackswaninteractive</p>
        <div id="color-fondo">
            <?php echo $this->navigation()->menu()->render();?>
        </div>
        <div id="linea-fondo">
        </div>
    </aside>
    <section id="block-right">
        <form class="form-account-setting" id="form-profile-page" action=""
              method="post" 'enctype='multipart/form-data'>
            <h2 class="h2-cms oswald">Agents</h2>
            <p id="number-published"><span>Create a new member profile</span></p>
            <fieldset id="agent-contact-details"><legend class="oswald">AGENT CONTACT DETAILS</legend>
                <div class="agent-image">
                    <label for="profileCompany">Agent Photo:</label>  
                    <div class="drop-image"></div>
                    <div class="drop-image-text">
                        <input type="file" name="image" >
                        <p>This is the image we use to<br> represent you on Mexi-Go</p>
                        <p>Your logo is shown at 145 x 145 pixels:</p>
                    </div>
                </div>
                <label for="profileFirstName">*First Name:</label>
                <input type="text" name="profileCompany" id="profileFirstName"><br>
                <label for="profileLastName">*Last Name:</label>
                <input type="text" name="profileCompany" id="profileLastName"><br>
                <div class="fields">
                    <label for="profileEmail">*Email Address:</label>
                    <input type="text" name="profileEmail" id="profileEmail"><span class="email-icon"></span>
                    <p>
                        Emails sent through the contact form on your listings will be forwarded to this address.
                    </p>
                </div>
                <label for="profileWebsite">Website:</label>
                <input type="text" name="profileWebsite" id="profileWebsite"><span class="website-icon"></span><br>
                <label for="profileBrokerage">Brokerage:</label>
                <input type="text" name="profileWebsite" id="profileBrokerage"><br>
                <table id="agent-description-table">
                    <tbody>
                        <tr>
                            <td>
                                <label for="profileAgentProfile">Agent Profile:</label><br>
                                <img title="" alt="" src="images/profile-icon.png">
                            </td>
                            <td>
                                <textarea name="profileDescription" id="agentDescription">Write a short description that will appear on your profile.</textarea>
                            </td>
                        </tr>
                    </tbody>
                </table>


            </fieldset>
            <hr class="hr-gris">
            <fieldset id="location-information"><legend class="oswald">Primary Location</legend>
<!--                <div class="combo-fix">
                    <label for="accountCountry">Country:</label>
                    <div class="flecha-combo"><select type="text" id="accountCountry" name="accountCountry"><option>Uruguay</option><option>Brasil</option></select></div>
                </div><br>-->
                <div class="combo-fix">
                    <label for="accountState">Region:</label>
                    <div class="flecha-combo"><select type="text" id="accountState" name="accountState"><option>Montevideo</option><option>Maldonado</option></select></div>
                </div><br>
                <div class="combo-fix">
                    <label for="accountCity">City:</label>
                    <div class="flecha-combo"><select type="text" id="accountCity" name="accountCity"><option>Montevideo</option><option>Maldonado</option></select></div>
                </div><br>
                <div class="combo-fix">
                    <label for="accountState">State/Province:</label>
                    <div class="flecha-combo"><select type="text" id="accountState" name="accountState"><option>Montevideo</option><option>Maldonado</option></select></div>
                </div><br>

            </fieldset>
            <fieldset id="location-information"><legend class="oswald">Secondary Location</legend>
<!--                <div class="combo-fix">
                    <label for="accountCountry">Country:</label>
                    <div class="flecha-combo"><select type="text" id="accountCountry" name="accountCountry"><option>Uruguay</option><option>Brasil</option></select></div>
                    <input type="button" value="ADD ANOTHER LOCATION &gt;&gt;" class="grey-button button-shadow">
                </div>-->
                <div class="combo-fix">
                    <label for="accountState">Region:</label>
                    <div class="flecha-combo"><select type="text" id="accountState" name="accountState"><option>Montevideo</option><option>Maldonado</option></select></div>
                </div><br>
                <div class="combo-fix">
                    <label for="accountCity">City:</label>
                    <div class="flecha-combo"><select type="text" id="accountCity" name="accountCity"><option>Montevideo</option><option>Maldonado</option></select></div>
                </div><br>
                <div class="combo-fix">
                    <label for="accountState">State/Province:</label>
                    <div class="flecha-combo"><select type="text" id="accountState" name="accountState"><option>Montevideo</option><option>Maldonado</option></select></div>
                </div><br>
                <hr class="hr-gris hr-gris-clear">
                <label for="accountPhonePre">Phone:</label>
                <input type="text" name="accountPhonePre" class="campo-chico-3" id="accountPhonePre">
                -
                <input type="text" name="accountPhone1" class="campo-chico-3" id="accountPhone1">
                -
                <input type="text" name="accountPhone2" class="campo-chico-3" id="accountPhone2">
                <br>
                <label for="accountPhonePre">Mobile Phone:</label>
                <input type="text" name="accountPhonePre" class="campo-chico-3" id="accountPhonePre">
                -
                <input type="text" name="accountPhone1" class="campo-chico-3" id="accountPhone1">
                -
                <input type="text" name="accountPhone2" class="campo-chico-3" id="accountPhone2">
                <br>
                <hr class="hr-gris">
                <p class="align-center"><input type="submit" class="oswald generals-buttons hand" value="SAVE AND CONTINUE &gt;&gt;"></p>
            </fieldset>
        </form>
    </section>
</div>