<div id="central-content">
    <p class="oswald" id="my-account">My Account</p>
    <aside class="oswald" id="block-left">
        <p class=" bg-white" id="hi-lateral">HI blackswaninteractive</p>
        <div id="color-fondo">

            <?php echo $this->navigation()->menu()->render(); ?>
        </div>
        <div id="linea-fondo">
        </div>
    </aside>
    <section id="block-right">
        <form id="reset-pass" class="form-account-setting" method="post" action="">
            <h2 class="oswald h2-cms">Reset Password</h2>
            <p>Please enter your new password below</p>
            <label for="accountCurrentPass">Current Password:</label><br>
            <input type="text" id="accountCurrentPass" name="accountCurrentPass"><br>
            <label for="accountNewPass">New Password:</label><br>
            <input type="text" id="accountNewPass" name="accountNewPass" value="5 or more characters"><br>
            <label for="accountVerifyPass">Verify Password:</label><br>
            <input align="middle" type="text" id="accountVerifyPass" name="accountVerifyPass" value="5 or more characters"><br>

            <input id="save-reset-pass" class="hand boton-yellow-1  oswald" type="submit" value="SAVE &gt;&gt;"><br>
            <a href="" class="oswald">Forgot your password?</a>
        </form>
    </section>
</div>