<div id="search-form-lat">
    <div id="pestana-buy-lat" class="oswald round-corner-top-8 top-box-shad">BUY</div>
    <div id="pestana-rent-lat" class="oswald round-corner-top-8 top-box-shad">RENT</div>

    <div id="cuerpo-search-buy-lat">
        <p class="search-tit font-j1 oswald">Dream Home Search>></p>
        <p class="mar-top-bot-5 oswald">Region</p>
        <div class="combo-fix float-left inline-block clear-none">
            <div class="flecha-combo-variante-largo"><select name="region-filter" id="region-filter" type="text"><option>Any</option><option>YES</option></select></div>

        </div>
        <p class="mar-top-bot-10 oswald">PRICE</p>
        <div class="combo-fix float-left inline-block clear-none">
            <label class="frmt-label-combo pad-lef-rig-5" for="">$</label>
            <div class="flecha-combo-variante"><select name="price-filter" id="price-filter" type="text"><option>No Minimum</option><option>YES</option></select></div>
            <div class="mar-lef-5 flecha-combo-chico-1-variante"><select class="select-chico-1" name="moneda-filter" id="moneda-filter" type="text"><option>USD</option><option>AUS</option><option>EUR</option></select></div>
        </div>                        
        <div id="block-beds">
            <img src="/front/images/bedrooms-w.png" /><br/>
            <span>Bedrooms</span>
            <div class="combo-fix inline-block clear-none">
                <div class="flecha-combo-variante-medio"><select name="bedroom-filter" id="bedroom-filter" type="text"><option>No Preference</option><option>YES</option></select></div>
            </div>
        </div>
        <div id="block-bath">
            <img src="/front/images/bathrooms-w.png" /><br/>
            <span>Bathrooms</span>
            <div class="combo-fix inline-block clear-none">
                <div class="flecha-combo-variante-medio"><select name="bath-filter" id="bath-filter" type="text"><option>No Preference</option><option>YES</option></select></div>
            </div>
        </div>
        <div class="moreoptions moreoptions-lateral">
            <p class="search-tit  oswald">SELECT AREA</p>
            <label for="city-more-filter">City</label><br/>
            <div class="mar-lef-20 flecha-combo-variante"><select type="text" id="city-more-filter" name="city-more-filter"><option>Any</option><option>YES</option></select></div><br/>
            <p class="search-tit  oswald">STATUS</p>
            <label for="available-more-filter">Available</label><br/>
            <div class="mar-lef-20 flecha-combo-variante"><select type="text" id="available-more-filter" name="available-more-filter"><option>Any</option><option>YES</option></select></div><br/>
            <p class="search-tit  oswald">SELECT PROPERTY TYPE</p>
            <label for="listing-status-more-filter">Listing Status</label><br/>
            <div class="mar-lef-20 flecha-combo-variante"><select type="text" id="listing-status-more-filter" name="listing-status-more-filter"><option>Any</option><option>YES</option></select></div><br/>
            <label for="property-type-more-filter">Property Type</label><br/>
            <div class="mar-lef-20 flecha-combo-variante"><select type="text" id="property-type-more-filter" name="property-type-more-filter"><option>Any</option><option>YES</option></select></div><br/>
            <p class="search-tit  oswald">PROPERTY DETAILS</p>
            <label for="house-more-filter">House</label><br/>
            <div class="mar-lef-20"><input type="text" id="house-more-filter" name="house-more-filter" class="input-text-variant"/></div>
            <div class=" flecha-combo-chico-1-variante"><select type="text" id="medida-house-more-filter" name="medida-house-more-filter" class="select-chico-1"><option>m&sup2;</option><option>AUS</option><option>EUR</option></select></div>
            <label for="land-more-filter">Land</label><br/>
            <div class="mar-lef-20"><input type="text" id="land-more-filter" name="land-more-filter" class="input-text-variant"/></div>
            <div class=" flecha-combo-chico-1-variante"><select type="text" id="medida-land-more-filter" name="medida-land-more-filter" class="select-chico-1"><option>m&sup2;</option><option>AUS</option><option>EUR</option></select></div>
            <p class="search-tit  oswald">SELECT FEATURES</p>
            <label for="style-more-filter">Style</label><br/>
            <div class="mar-lef-20 flecha-combo-variante"><select type="text" id="style-more-filter" name="style-more-filter"><option>Any</option><option>YES</option></select></div><br/>
            <label for="garage-more-filter">Garage</label><br/>
            <div class="mar-lef-20 flecha-combo-variante"><select type="text" id="garage-more-filter" name="garage-more-filter"><option>Any</option><option>YES</option></select></div><br/>
            <label for="view-more-filter">View</label><br/>
            <div class="mar-lef-20 flecha-combo-variante"><select type="text" id="view-more-filter" name="view-more-filter"><option>Any</option><option>YES</option></select></div><br/>
            <label for="recreation-more-filter">Recreational Areas</label><br/>
            <div class="mar-lef-20 flecha-combo-variante"><select type="text" id="recreation-more-filter" name="recreation-more-filter"><option>Any</option><option>YES</option></select></div><br/>
            <label for="address-more-filter">Address</label><br/>
            <div class="mar-lef-20 flecha-combo-variante"><select type="text" id="address-more-filter" name="address-more-filter"><option>Any</option><option>YES</option></select></div><br/>
            <label for="size-more-filter">Size(sq.ft.)</label><br/>
            <div class="mar-lef-20 flecha-combo-variante"><select type="text" id="size-more-filter" name="size-more-filter"><option>Any</option><option>YES</option></select></div><br/>
            <label for="keyword-more-filter">Keyword</label><br/>
            <div class="mar-lef-20"><input type="text" id="keyword-more-filter" name="keyword-more-filter" class="input-text-variant"/></div><br/>
            <p class="search-tit-center  oswald">AMENITIES</p>
            <p class="search-tit-center  oswald">OUT BUILDINGS</p>
            <p class="search-tit-center  oswald">APPLIANCES</p>
        </div>
        <p id="more-filters-search" class="open" style="display:block ">MORE FILTERS</p>
        <div><div class="moreoptions_text">
                <a href=""><p>Advanced Search >></p></a>
                <a href=""><p>Map Search >></p></a>
            </div>
            <div class="moreoptions_line"></div>
            <input class="moreoptions_submit" type="submit" value="">
        </div>
        <p id="more-filters-search" class="open" style="display:none ">LESS FILTERS</p>





    </div>


    <div id="cuerpo-search-rent-lat" >
        <div class="top-box-shad float-left">
            <p class="search-tit font-j1 oswald">Dream Vacation Search>></p>
            <div class="destinations"><p class="mar-lef-20 mar-top-bot-5 oswald">DESTINATIONS</p></div>
            <div class="region">
                <p class="mar-top-bot-5 oswald mar-lef-20 ">Regions</p>
            </div>
            <div class="combo-fix float-left inline-block clear-none">
                <div class="flecha-combo-variante-largo"><select name="region-filter" id="region-filter" type="text"><option>Any</option><option>YES</option></select></div>

            </div>
            <div class="region">
                <p class="mar-top-bot-5 oswald mar-lef-20 ">Travel Dates</p>
                <div class="align-center-travel-date">
                    <div class="combo-fix inline-block clear-none">
                        <div class="flecha-combo-variante-medio"><select type="text" id="rent-checkin-search-filter" name="rent-checkin-search-filter"><option>Check in</option><option>YES</option></select></div>
                    </div>
                    <div class="combo-fix inline-block clear-none">
                        <div class="flecha-combo-variante-medio"><select type="text" id="rent-checkout-search-filter" name="rent-checkout-search-filter"><option>Check out</option><option>YES</option></select></div>
                    </div>
                </div>
            </div>
            <div id="subblk-left" class="omi-check">
                <label for="checkDailyRentLat" id="label-checkDailyRentLat" class="oswald check-special-dark-black">Rent Daily</label><input id="checkDailyRentLat" name="checkDailyRentLat" type="checkbox" /><br/>
                <label for="checkMonthlyRentLat" id="label-checkMonthlyRentLat" class="oswald check-special-dark-black">Rent Monthly</label><input id="checkMonthlyRentLat" name="checkMonthlyRentLat" type="checkbox" /><br/>
                <label for="checkAnnualyRentLat" id="label-checkAnnualyRentLat" class="oswald check-special-dark-black">Rent Annualy</label><input id="checkAnnualyRenLatt" name="checkAnnualyRentLat" type="checkbox" /><br/>
            </div>
            <div id="subblk-right" >
                <span id="numer-bds" class="oswald">Number<br/>of beds</span>
                <div class="float-left mar-lef-5 flecha-combo-chico-1-variante"><select type="text" id="no-bed-rent-filter" name="no-bed-rent-filter" class="select-chico-1"><option>4</option><option>2</option><option>1</option></select></div>
            </div>
            <div><div class="moreoptions_text">
                    <a href=""><p class="mar-lef-20" >Advanced Search >></p></a>
                    <a href=""><p class="mar-lef-20">Map Search >></p></a>
                </div>
                <div class="moreoptions_line"></div>
                <input id="moreoptions_submit_rent" class="moreoptions_submit" type="submit" value="">
            </div>
        </div>                        
    </div>
</div>

