<div id="blok-videos-slidr" class="hiden-now">
    <div id="gall-principal_video" class="shadow-gall">
        <div id="cont_slide_video_adentro">
            <?php
            echo "<style>";
            $arrayImagenesSlideEjemplo = array("imagen1", "imagen2", "imagen3", "imagen4", "imagen5", "imagen6", "imagen7", "imagen8", "imagen9", "imagen10");
            $cont = 0;
            foreach ($arrayImagenesSlideEjemplo as $imgRow) {
                $imageHeight = 332;
                $imageWidth = 590;
                echo '#slide_vid_' . ($cont + 1) . '{top:-' . ($imageHeight * $cont) . 'px;left:' . ($imageWidth * $cont) . 'px} ';
                $cont++;
            }
            echo '</style>';
            ?>
            <input type="hidden" id="slide_corriendo_video" name="slide_corriendo" value="no" /> 
            <div id="slide_vid_1" class="video_slide actual_vid_slide" ><iframe width="590" height="332" src="http://www.youtube.com/embed/olsD3gzdbOQ" frameborder="0" allowfullscreen></iframe></div>
            <div id="slide_vid_2" class="video_slide " ><iframe src="http://player.vimeo.com/video/23073862?byline=0&amp;portrait=0" width="590" height="332" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> <p><a href="http://vimeo.com/23073862">Champions timelapse</a> from <a href="http://vimeo.com/luiscaldevilla">Luis Caldevilla</a> on <a href="http://vimeo.com">Vimeo</a>.</p></div>
            <div id="slide_vid_3" class="video_slide " ><iframe width="590" height="332" src="http://www.youtube.com/embed/olsD3gzdbOQ" frameborder="0" allowfullscreen></iframe></div>
            <div id="slide_vid_4" class="video_slide " ><iframe src="http://player.vimeo.com/video/23073862?byline=0&amp;portrait=0" width="590" height="332" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> <p><a href="http://vimeo.com/23073862">Champions timelapse</a> from <a href="http://vimeo.com/luiscaldevilla">Luis Caldevilla</a> on <a href="http://vimeo.com">Vimeo</a>.</p></div>                            
            <div id="slide_vid_5" class="video_slide "  ><iframe width="590" height="332" src="http://www.youtube.com/embed/olsD3gzdbOQ" frameborder="0" allowfullscreen></iframe></div>
            <div id="slide_vid_6" class="video_slide "  ><iframe width="590" height="332" src="http://www.youtube.com/embed/olsD3gzdbOQ" frameborder="0" allowfullscreen></iframe></div>
            <div id="slide_vid_7" class="video_slide " ><iframe src="http://player.vimeo.com/video/23073862?byline=0&amp;portrait=0" width="590" height="332" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> <p><a href="http://vimeo.com/23073862">Champions timelapse</a> from <a href="http://vimeo.com/luiscaldevilla">Luis Caldevilla</a> on <a href="http://vimeo.com">Vimeo</a>.</p></div>
            <div id="slide_vid_8" class="video_slide "  ><iframe width="590" height="332" src="http://www.youtube.com/embed/olsD3gzdbOQ" frameborder="0" allowfullscreen></iframe></div>
            <div id="slide_vid_9" class="video_slide " ><iframe src="http://player.vimeo.com/video/23073862?byline=0&amp;portrait=0" width="590" height="332" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> <p><a href="http://vimeo.com/23073862">Champions timelapse</a> from <a href="http://vimeo.com/luiscaldevilla">Luis Caldevilla</a> on <a href="http://vimeo.com">Vimeo</a>.</p></div>
            <div id="slide_vid_10" class="video_slide "  ><iframe width="590" height="332" src="http://www.youtube.com/embed/olsD3gzdbOQ" frameborder="0" allowfullscreen></iframe></div>
        </div>
    </div>
    <div id="gall-thumbs-wrap-video">
        <div id="gall-flecha-izq-video"></div>
        <div id="gall-nav-med-video">
            <div id="cont-tumbs-gal-vid">
                <div id="thumb_slide_vid_1" class="thumb-video-active slideToVideo shadow-gall gall-thumb-avance"><img src="/front/images/galeria-thumb-demo.jpg"/></div>
                <div id="thumb_slide_vid_2" class="slideToVideo shadow-gall gall-thumb-avance"><img src="/front/images/galeria-thumb-demo.jpg"/></div>
                <div id="thumb_slide_vid_3" class="slideToVideo shadow-gall gall-thumb-avance"><img src="/front/images/galeria-thumb-demo.jpg"/></div>
                <div id="thumb_slide_vid_4" class="slideToVideo shadow-gall gall-thumb-avance"><img src="/front/images/galeria-thumb-demo.jpg"/></div>
                <div id="thumb_slide_vid_5" class="slideToVideo shadow-gall gall-thumb-avance"><img src="/front/images/galeria-thumb-demo.jpg"/></div>
                <div id="thumb_slide_vid_6" class="slideToVideo shadow-gall gall-thumb-avance"><img src="/front/images/galeria-thumb-demo.jpg"/></div>
                <div id="thumb_slide_vid_7" class="slideToVideo shadow-gall gall-thumb-avance"><img src="/front/images/galeria-thumb-demo.jpg"/></div>
                <div id="thumb_slide_vid_8" class="slideToVideo shadow-gall gall-thumb-avance"><img src="/front/images/galeria-thumb-demo.jpg"/></div>
                <div id="thumb_slide_vid_9" class="slideToVideo shadow-gall gall-thumb-avance"><img src="/front/images/galeria-thumb-demo.jpg"/></div>
                <div id="thumb_slide_vid_10" class="slideToVideo shadow-gall gall-thumb-avance"><img src="/front/images/galeria-thumb-demo.jpg"/></div>    
            </div>
        </div>
        <div id="gall-flecha-der-video"></div>

    </div>
</div>