<div id="lateral-detalle-home">
    <h4 class="oswald">DETAILS</h4>
    <p><span class="lat-estilo-span oswald">Status:</span><span class="lat-estilo-span-right">Available</span></p>
    <p><span class="lat-estilo-span oswald">Listing Status:</span><span class="lat-estilo-span-right">For Sale / Residential</span></p>
    <p><span class="lat-estilo-span oswald">Property Type:</span><span class="lat-estilo-span-right">Single Family Home</span></p>
    <p>
        <span class="lat-estilo-span oswald">Price:</span>
    <div class="lat-estilo-span-right formato-combito"><div class="flecha-combo-chico-1 float-left"><select class="select-chico-1" name="landMedida" id="landMedida" type="text"><option>USD</option><option>AUS</option><option>EUR</option></select></div>
        <span class="float-left mar-lef-5">$1,350,000</span>
    </div>
</p>
<p><span class="lat-estilo-span oswald">Location:</span><span class="lat-estilo-span-right">Patzucuato 500, Sayulita, Sayulita Mexico</span> </p>
<p><span class="lat-estilo-span oswald">Style:</span><span class="lat-estilo-span-right">Multi-Storey</span></p>
<p><span class="lat-estilo-span oswald">Year Built:</span><span class="lat-estilo-span-right">2007</span></p>
<p><span class="lat-estilo-span oswald">House Size:</span>
<div class="lat-estilo-span-right formato-combito">
    <span class="float-left mar-rig-5">9/10</span>
    <div class="flecha-combo-chico-1 float-left"><select class="select-chico-1" name="landMedida" id="landMedida" type="text"><option>sq.ft.</option><option>mts</option></select></div>
</div>
</p>
<p><span class="lat-estilo-span oswald">Land size:</span>
<div class="lat-estilo-span-right formato-combito">
    <span class="float-left mar-rig-5">9075</span>
    <div class="flecha-combo-chico-1 float-left"><select class="select-chico-1" name="landMedida" id="landMedida" type="text"><option>sq.ft.</option><option>mts</option></select></div>
</div>
</p>
<p><span class="lat-estilo-span oswald">Garage:</span><span class="lat-estilo-span-right">Detached</span></p>
<p><span class="lat-estilo-span oswald">Garage Cars:</span><span class="lat-estilo-span-right">2</span></p>
<div>
    <p><span class="lat-estilo-span oswald">Features:</span><span class="lat-estilo-span-right">BBQ Area, Beamed Ceilings, Cathedral Ceilings, Fence / Wall, High Speed Internet, Patio, Pool, Roof Top Terrace, Satellite Television, Second Kitchen, Storage Area, Terrace, Wireless Internet</span></p>
</div>
<p><span class="lat-estilo-span oswald">Out Buildings:</span><span class="lat-estilo-span-right">Casita, Pergola</span></p>
<p><span class="lat-estilo-span oswald">Appliances:</span><span class="lat-estilo-span-right">Air Conditioning, Ceiling Fans, Clothes Dryer, Clothes Washer, Dishwasher, Freezer, Ice Maker, Microwave, Mini-Split, Oven: Electric, Oven: Gas.</span></p>
<p><span class="lat-estilo-span oswald">Views:</span><span class="lat-estilo-span-right">Ocean</span></p>
<p><span class="lat-estilo-span oswald">Submisson Date:</span><span class="lat-estilo-span-right">08-06-2011</span></p>
<p><span class="lat-estilo-span oswald">Last Update:</span><span class="lat-estilo-span-right">09-03-2011</span></p>

</div>