<aside id="block-left" class="oswald">
    <p id="hi-lateral" class=" bg-white">HI blackswaninteractive</p>
    <div id="color-fondo">
    
    <p id="account-settings-menu" class="lateral-selected " ><a href="/partner/account-settings">ACCOUNT SETTINGS</a></p>
    <nav>
        <div class="menu-lateral-bg-gris-oscuro">
        <p id="manage-your-style" class="text-white ">Manage your</p>
        <ul>
            <li class="text-yellow menu-lateral-relative" ><a href="/partner/profiler" title="go to profile page">PROFILE PAGE</a></li>
            <li class="lateral-selected text-yellow " ><a href="/partner/agent" title="go to agents">AGENTS</a></li>
            <li class="text-yellow menu-lateral-relative" ><a href="/partner/real-estate" title="go to real estate listings">REAL ESTATE LISTINGS</a></li>
        </ul>
        </div>
        <ul>
            <li id="menu-buy" class="text-yellow menu-lateral-bg-gris-claro"><a href="">BUY</a></li>
            <li class="lateral-selected"><a href="/partner/my-account/email-preferences">EMAIL PREFERENCES</a></li>
            <li><a href="/partner/my-account/account-password">ACCOUNT PASSWORD</a></li>
            <li><a href="/partner/my-account/sign-out">SIGN OUT</a></li>
        </ul>
    </nav>    
    </div>
    <div id="linea-fondo">
    </div>
</aside>