<aside id="block-left" class="oswald">
    <div id="color-fondo">    
        <p id="account-settings-menu" class="<?php echo ($_SERVER['REQUEST_URI'] == '/partners/print-magazine.html')? 'lateral-selected':'';?>" ><a href="/partner/print-magaz">PRINT MAGAZINE</a></p>   
        <p id="account-settings-menu" class="<?php echo ($_SERVER['REQUEST_URI'] == '/partners/online-magazine.html')? 'lateral-selected':'';?>" ><a href="/partner/online-magazine.html">ONLINE MAGAZINE</a></p>    
    </div>
    <div id="linea-fondo">
    </div>
</aside>