<ul class="menu-buying-selling ">
    <li><a href="" class="active-menu oswald">BUYING REAL ESTATE</a></li>
    <li><a href="" class="oswald">FAQ ON BUYING</a></li>
    <li><a href="" class="oswald">FAQ ON MORTAGES</a></li>
    <li><a href="" class="oswald">CLOSING COSTS</a></li>
    <li><a href="" class="oswald">TITLE INSURANCE</a></li>
    <li><a href="" class="oswald">NOTARY AND LAWYERS</a></li>
    <li><a href="" class="oswald">HOLDING TITLE</a></li>
</ul>