<aside class="oswald" id="right-column">
    <div class="boxes boxes-right">
        <div class="div-center">
            <fieldset>
                <legend><h2>Mexi-Go! News</h2></legend>
                <div class="image-frame">
                    <img title="" alt="" src="/front/images/slide5.jpg">
                </div>
                <h3>Lore impsum dolor</h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec fermentum massa...
                </p>
                <a class="read-more" href="/partners/news.html">Read More &gt;&gt;</a>
            </fieldset>
            <div class="botom-bar">&nbsp;</div>
        </div>
    </div>
    <div class="boxes boxes-right">
        <div class="div-center">
            <h2>Work with the Best</h2>
            <div class="sing-up-box">
                Sing Up
            </div>
            <p>
                Online and in print we promote the lifestyle and culture of Mexico Directly to the most qualified Canadian demographic
            </p>
            <input type="button" id="btn-become-partner" class="generals-buttons yellow-button-shadow" value="BECOME A CONTRIBUTOR">
        </div>
    </div>
    <div class="boxes boxes-right">
        <div class="div-center">
            <h2>ONLINE AND IN PRINT</h2>
            <div class="grey-box">
                <p>
                    Elevate and enchance your listing Impress your clients.
                    Attract Canadian buyers.							
                </p>
                <h4>MEXI-GO.CA ONLINE</h4>
                <h4 class="yellow-text">REAL ESTATES LISTINGS ONLINE ADVERTISINGS PRINT MAGAZINE</h4>
            </div>
        </div>
    </div>
    <div class="boxes boxes-right">
        <div class="div-center">
            <h2>Magazine</h2>
            <div class="magazine-box">
                <img alt="" title="" src="/front/images/magazine.png">
            </div>
            <div class="learn-more">
                <a href="/magazine.html">
                    <input type="button" id="btn-learn-more" class="generals-buttons yellow-button-shadow" value="LEARN MORE">
                </a>
            </div>
        </div>
    </div>
</aside>